/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			var s = String(n).split('.'),
				v0 = !s[1],
				t0 = Number(s[0]) == n,
				n10 = t0 && s[0].slice(-1),
				n100 = t0 && s[0].slice(-2);
			if (ord)
				return n10 == 1 && n100 != 11
					? 'one'
					: n10 == 2 && n100 != 12
						? 'two'
						: n10 == 3 && n100 != 13
							? 'few'
							: 'other';
			return n == 1 && v0 ? 'one' : 'other';
		}
	},
	messages: {
		'"Web Maker" <0>CHill</0>.': '"Web Maker" <0>CHill</0>.',
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.',
		'Add Library': 'Add Library',
		'Add a JS/CSS library': 'Add a JS/CSS library',
		'Add library': 'Add library',
		Assets: 'Assets',
		Chat: 'Chat',
		'Choose from popular libraries': 'Choose from popular libraries',
		'Clear console (CTRL + L)': 'Clear console (CTRL + L)',
		'Clear console (works when console input is focused)':
			'Clear console (works when console input is focused)',
		'Close saved creations pane': 'Close saved creations pane',
		'Close saved creations panel & modals':
			'Close saved creations panel & modals',
		Console: 'Console',
		'Detach Preview': 'Detach Preview',
		'Detach preview': 'Detach preview',
		Discuss: 'Discuss',
		Donate: 'Donate',
		'Double click to toggle console': 'Double click to toggle console',
		'Download game as zip': 'Download game as zip',
		'Edit on CodePen': 'Edit on CodePen',
		Editor: 'Editor',
		'Emmet code completion': 'Emmet code completion',
		Export: 'Export',
		'Export all your creations into a single importable file.':
			'Export all your creations into a single importable file.',
		Find: 'Find',
		'Find & replace': 'Find & replace',
		Fork: 'Fork',
		'Fork this creation': 'Fork this creation',
		Get: 'Get',
		Global: 'Global',
		Help: 'Help',
		Import: 'Import',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			"Import your creations. Only the file that you export through the 'Export' button can be imported.",
		'Indent code left': 'Indent code left',
		'Indent code right': 'Indent code right',
		'Keyboard Shortcuts': 'Keyboard Shortcuts',
		'Keyboard shortcuts': 'Keyboard shortcuts',
		License: 'License',
		'Like this app? Please <0>rate it here</0>.':
			'Like this app? Please <0>rate it here</0>.',
		'Like this extension? Please <0>rate it here</0>.':
			'Like this extension? Please <0>rate it here</0>.',
		Login: 'Login',
		'Login/Signup': 'Login/Signup',
		'Made with <0>\uD83D\uDC96</0>& <1> \uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Made with <0>\uD83D\uDC96</0>& <1> \uD83D\uDE4C</1> by <2>Kushagra Gour</2>',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>',
		'Mail me': 'Mail me',
		Manage: 'Manage',
		'Manage your PRO subscription': 'Manage your PRO subscription',
		'My Library': 'My Library',
		'My Library ({0})': function (a) {
			return ['My Library (', a('0'), ')'];
		},
		New: 'New',
		'No match found.': 'No match found.',
		'Note: You can load external scripts from following domains:':
			'Note: You can load external scripts from following domains:',
		'Note: You can load external scripts only from following domains:':
			'Note: You can load external scripts only from following domains:',
		'Nothing saved here.': 'Nothing saved here.',
		Open: 'Open',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'Open a saved creation (Ctrl/\u2318 + O)',
		'Open list of saved creations': 'Open list of saved creations',
		'Powered by cdnjs': 'Powered by cdnjs',
		'Put each library in new line': 'Put each library in new line',
		'Read more': 'Read more',
		'Read the documentation.': 'Read the documentation.',
		'Realign code': 'Realign code',
		'Refresh preview': 'Refresh preview',
		'Report a bug': 'Report a bug',
		'Review Web Maker': 'Review Web Maker',
		Run: 'Run',
		'Run Prettier': 'Run Prettier',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'Run preview (Ctrl/\u2318 + Shift + 5)',
		Save: 'Save',
		'Save as HTML file': 'Save as HTML file',
		'Save current creation (Ctrl/\u2318 + S)':
			'Save current creation (Ctrl/\u2318 + S)',
		'Save current creations': 'Save current creations',
		'Search your creations here...': 'Search your creations here...',
		'See Changelog': 'See Changelog',
		'See awesome libraries used': 'See awesome libraries used',
		'See changelog': 'See changelog',
		'See profile or Logout': 'See profile or Logout',
		'Select next match': 'Select next match',
		'Select previous match': 'Select previous match',
		Settings: 'Settings',
		Share: 'Share',
		'Share Web Maker': 'Share Web Maker',
		'Share this creation publicly': 'Share this creation publicly',
		Signup: 'Signup',
		'Single line comment': 'Single line comment',
		'Start a new creation': 'Start a new creation',
		'Support the developer': 'Support the developer',
		'Support the developer by pledging some amount':
			'Support the developer by pledging some amount',
		'Switch to full screen preview': 'Switch to full screen preview',
		'Switch to layout with all vertical panes':
			'Switch to layout with all vertical panes',
		'Switch to layout with preview on bottom':
			'Switch to layout with preview on bottom',
		'Switch to layout with preview on left':
			'Switch to layout with preview on left',
		'Switch to layout with preview on left"':
			'Switch to layout with preview on left"',
		'Switch to layout with preview on right':
			'Switch to layout with preview on right',
		'Take screenshot of preview': 'Take screenshot of preview',
		'Toggle console': 'Toggle console',
		'Toggle full screen preview': 'Toggle full screen preview',
		"Tweet about 'Web Maker'": "Tweet about 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>',
		'Type here to search libraries': 'Type here to search libraries',
		'Upgrade to PRO and get some advanced superpowers!':
			'Upgrade to PRO and get some advanced superpowers!',
		'Upload Image': 'Upload Image',
		'Upload/Use assets': 'Upload/Use assets'
	}
};
