/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			var s = String(n).split('.'),
				v0 = !s[1],
				t0 = Number(s[0]) == n,
				n10 = t0 && s[0].slice(-1),
				n100 = t0 && s[0].slice(-2);
			if (ord)
				return n10 == 1 && n100 != 11
					? 'one'
					: n10 == 2 && n100 != 12
						? 'two'
						: n10 == 3 && n100 != 13
							? 'few'
							: 'other';
			return n == 1 && v0 ? 'one' : 'other';
		}
	},
	messages: {
		'"Web Maker" <0>CHill</0>.': '"Web Maker" <0>CHill</0>.',
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.',
		'(Experimental) Switches from CodeMirror to Monaco. Many other settings might not be available in Monaco.':
			'(Experimental) Switches from CodeMirror to Monaco. Many other settings might not be available in Monaco.',
		'2 files mode creations available in Free plan. To create unlimited files mode creations, upgrade to <0/>.':
			'2 files mode creations available in Free plan. To create unlimited files mode creations, upgrade to <0/>.',
		'3 separate panes to write HTML, CSS and JavaScript. Good for quickly testing something.':
			'3 separate panes to write HTML, CSS and JavaScript. Good for quickly testing something.',
		'Add Library': 'Add Library',
		'Add a JS/CSS library': 'Add a JS/CSS library',
		'Add collection': 'Add collection',
		'Add library': 'Add library',
		'Add the closing tag automatically on seeing an opening tag in HTML':
			'Add the closing tag automatically on seeing an opening tag in HTML',
		Advanced: 'Advanced',
		All: 'All',
		Assets: 'Assets',
		'Assets feature is available in PRO plan.':
			'Assets feature is available in PRO plan.',
		'Atomic CSS configuration': 'Atomic CSS configuration',
		'Auto-close tags': 'Auto-close tags',
		'Auto-complete suggestions': 'Auto-complete suggestions',
		'Auto-preview': 'Auto-preview',
		'Auto-save': 'Auto-save',
		'Auto-save keeps saving your code at regular intervals after you hit save manually the first time':
			'Auto-save keeps saving your code at regular intervals after you hit save manually the first time',
		Chat: 'Chat',
		'Choose from popular libraries': 'Choose from popular libraries',
		'Clear console (CTRL + L)': 'Clear console (CTRL + L)',
		'Clear console (works when console input is focused)':
			'Clear console (works when console input is focused)',
		'Click to change': 'Click to change',
		'Click to edit': 'Click to edit',
		'Close saved creations pane': 'Close saved creations pane',
		'Close saved creations panel & modals':
			'Close saved creations panel & modals',
		'Code blast!': 'Code blast!',
		Collab: 'Collab',
		'Collab Session': 'Collab Session',
		'Collaboration unavailable offline': 'Collaboration unavailable offline',
		'Collection name': 'Collection name',
		'Configure and customize settings by clicking the gear icon (<0><1/></0>) in bottom right of the app.':
			'Configure and customize settings by clicking the gear icon (<0><1/></0>) in bottom right of the app.',
		Console: 'Console',
		'Copy URL (or keep clicking to copy other formats)':
			'Copy URL (or keep clicking to copy other formats)',
		'Copy link': 'Copy link',
		'Create New': 'Create New',
		'Custom font name here': 'Custom font name here',
		'Default CSS preprocessor': 'Default CSS preprocessor',
		'Default HTML preprocessor': 'Default HTML preprocessor',
		'Default JavaScript preprocessor': 'Default JavaScript preprocessor',
		'Default Preprocessors': 'Default Preprocessors',
		Delete: 'Delete',
		'Detach Preview': 'Detach Preview',
		'Detach preview': 'Detach preview',
		Discuss: 'Discuss',
		"Don't ask me again": "Don't ask me again",
		Donate: 'Donate',
		'Double click to toggle code pane': 'Double click to toggle code pane',
		'Double click to toggle console': 'Double click to toggle console',
		'Download game as zip': 'Download game as zip',
		'Drop files or click here to upload': 'Drop files or click here to upload',
		'Edit on CodePen': 'Edit on CodePen',
		Editor: 'Editor',
		'Emmet code completion': 'Emmet code completion',
		'Enjoy wonderful particle blasts while you type':
			'Enjoy wonderful particle blasts while you type',
		Export: 'Export',
		'Export all your creations into a single importable file.':
			'Export all your creations into a single importable file.',
		'Fast/light-weight version': 'Fast/light-weight version',
		'Feedback & Suggestions': 'Feedback & Suggestions',
		'Fetching files...': 'Fetching files...',
		'File should be max 300KB in size': 'File should be max 300KB in size',
		'Files modes is currently only available in Web app. <0>Try the Web app now</0>.':
			'Files modes is currently only available in Web app. <0>Try the Web app now</0>.',
		Find: 'Find',
		'Find & replace': 'Find & replace',
		'Follow <0>@webmakerApp</0> to know about the new upcoming features!':
			'Follow <0>@webmakerApp</0> to know about the new upcoming features!',
		Font: 'Font',
		'Font Size': 'Font Size',
		Fork: 'Fork',
		'Fork this creation': 'Fork this creation',
		'Format Code': 'Format Code',
		'Format code': 'Format code',
		Fun: 'Fun',
		General: 'General',
		Get: 'Get',
		Global: 'Global',
		'Grid view': 'Grid view',
		Help: 'Help',
		'Hi, <0>Kushagra</0> here! Web Maker is a free and open-source project. To keep myself motivated for working on such open-source and free <1>side projects</1>, I am accepting donations. Your pledge, no matter how small, will act as an appreciation towards my work and keep me going forward making Web Maker more awesome\uD83D\uDD25. So please consider donating. \uD83D\uDE4F\uD83C\uDFFC (could be as small as $1/month).':
			'Hi, <0>Kushagra</0> here! Web Maker is a free and open-source project. To keep myself motivated for working on such open-source and free <1>side projects</1>, I am accepting donations. Your pledge, no matter how small, will act as an appreciation towards my work and keep me going forward making Web Maker more awesome\uD83D\uDD25. So please consider donating. \uD83D\uDE4F\uD83C\uDFFC (could be as small as $1/month).',
		'Hover/Focus to preview': 'Hover/Focus to preview',
		'I wish Web Maker could...': 'I wish Web Maker could...',
		'If any loop iteration takes more than the defined time, it is detected as a potential infinite loop and further iterations are stopped.':
			'If any loop iteration takes more than the defined time, it is detected as a potential infinite loop and further iterations are stopped.',
		'If you are an existing Chrome extension user, you can import your creations from there to here. <0>Learn how to export/import</0>.':
			'If you are an existing Chrome extension user, you can import your creations from there to here. <0>Learn how to export/import</0>.',
		Import: 'Import',
		'Import your creations in your account':
			'Import your creations in your account',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			"Import your creations. Only the file that you export through the 'Export' button can be imported.",
		'Indent code left': 'Indent code left',
		'Indent code right': 'Indent code right',
		Indentation: 'Indentation',
		'Indentation Size': 'Indentation Size',
		"It's okay if you don't want to. You can simply logout and access them anytime on this browser.":
			"It's okay if you don't want to. You can simply logout and access them anytime on this browser.",
		'Join a community of 70,000+ Developers':
			'Join a community of 70,000+ Developers',
		'Js13kGames Mode': 'Js13kGames Mode',
		'Key bindings': 'Key bindings',
		'Keyboard Shortcuts': 'Keyboard Shortcuts',
		'Keyboard shortcuts': 'Keyboard shortcuts',
		Language: 'Language',
		'Leave Session': 'Leave Session',
		'Lets start!': 'Lets start!',
		License: 'License',
		'Like this app? Please <0>rate it here</0>.':
			'Like this app? Please <0>rate it here</0>.',
		'Like this extension? Please <0>rate it here</0>.':
			'Like this extension? Please <0>rate it here</0>.',
		'Line wrap': 'Line wrap',
		'List view': 'List view',
		'Loads the last open creation when app starts':
			'Loads the last open creation when app starts',
		Login: 'Login',
		'Login & upgrade to PRO': 'Login & upgrade to PRO',
		'Login / Signup': 'Login / Signup',
		'Login with Github': 'Login with Github',
		'Login with Google': 'Login with Google',
		'Login/Signup': 'Login/Signup',
		'Made with <0>\uD83D\uDC96</0>& <1> \uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Made with <0>\uD83D\uDC96</0>& <1> \uD83D\uDE4C</1> by <2>Kushagra Gour</2>',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>',
		'Mail me': 'Mail me',
		'Make a monthly pledge on Patreon': 'Make a monthly pledge on Patreon',
		'Make the app ready to build some games for <0>Js13kGames</0>.':
			'Make the app ready to build some games for <0>Js13kGames</0>.',
		Manage: 'Manage',
		'Manage your PRO subscription': 'Manage your PRO subscription',
		'Manage your code in files. Just like you would have files on your local machine.':
			'Manage your code in files. Just like you would have files on your local machine.',
		'Maximize pane': 'Maximize pane',
		'Maximum time allowed in a loop iteration':
			'Maximum time allowed in a loop iteration',
		'Minimise pane': 'Minimise pane',
		'Most recent first': 'Most recent first',
		'Most upvoted first': 'Most upvoted first',
		'Multiplayer session active': 'Multiplayer session active',
		'My Library': 'My Library',
		'My Library ({0})': function (a) {
			return ['My Library (', a('0'), ')'];
		},
		New: 'New',
		'No feedback yet. Be the first!': 'No feedback yet. Be the first!',
		'No files uploaded yet': 'No files uploaded yet',
		'No items in this collection.': 'No items in this collection.',
		'No match found.': 'No match found.',
		'Note: You can load external scripts from following domains:':
			'Note: You can load external scripts from following domains:',
		'Note: You can load external scripts only from following domains:':
			'Note: You can load external scripts only from following domains:',
		'Nothing saved here.': 'Nothing saved here.',
		'Once you stop typing, the preview waits for this much time before getting updated. Too low value might choke your browser!':
			'Once you stop typing, the preview waits for this much time before getting updated. Too low value might choke your browser!',
		Open: 'Open',
		'Open Web Maker anytime by clicking the<0><1/></0> button in top-right side of your browser.':
			'Open Web Maker anytime by clicking the<0><1/></0> button in top-right side of your browser.',
		'Open Web Maker anytime by visiting <0>https://webmaker.app/create/</0> - Even when you are offline! It just works! \uD83D\uDE31 <1>Drag the following bookmarklet</1> on your bookmark bar to create a quick access shortcut:':
			'Open Web Maker anytime by visiting <0>https://webmaker.app/create/</0> - Even when you are offline! It just works! \uD83D\uDE31 <1>Drag the following bookmarklet</1> on your bookmark bar to create a quick access shortcut:',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'Open a saved creation (Ctrl/\u2318 + O)',
		'Open list of saved creations': 'Open list of saved creations',
		'Or, make a one time donation': 'Or, make a one time donation',
		'Other font from system': 'Other font from system',
		Participants: 'Participants',
		'Powered by cdnjs': 'Powered by cdnjs',
		'Preserve console logs': 'Preserve console logs',
		'Preserve last written code': 'Preserve last written code',
		'Preserves the console logs across your preview refreshes':
			'Preserves the console logs across your preview refreshes',
		'Preview refresh wait time': 'Preview refresh wait time',
		'Preview will refresh when you resize the preview pane':
			'Preview will refresh when you resize the preview pane',
		'Put each library in new line': 'Put each library in new line',
		'Read more': 'Read more',
		'Read the documentation.': 'Read the documentation.',
		'Realign code': 'Realign code',
		'Refresh preview': 'Refresh preview',
		'Refresh preview on resize': 'Refresh preview on resize',
		"Refreshes the preview as you code. Otherwise use the 'Run' button":
			"Refreshes the preview as you code. Otherwise use the 'Run' button",
		'Replace new tab page': 'Replace new tab page',
		'Report a bug': 'Report a bug',
		'Review Web Maker': 'Review Web Maker',
		Run: 'Run',
		'Run Prettier': 'Run Prettier',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'Run preview (Ctrl/\u2318 + Shift + 5)',
		Save: 'Save',
		'Save as HTML file': 'Save as HTML file',
		'Save current creation (Ctrl/\u2318 + S)':
			'Save current creation (Ctrl/\u2318 + S)',
		'Save current creations': 'Save current creations',
		'Search files': 'Search files',
		'Search your creations here...': 'Search your creations here...',
		'See Changelog': 'See Changelog',
		'See awesome libraries used': 'See awesome libraries used',
		'See changelog': 'See changelog',
		'See profile or Logout': 'See profile or Logout',
		'Select next match': 'Select next match',
		'Select previous match': 'Select previous match',
		Settings: 'Settings',
		Share: 'Share',
		'Share Link': 'Share Link',
		'Share Web Maker': 'Share Web Maker',
		'Share this creation publicly': 'Share this creation publicly',
		'Share this link with others to let them join your session.':
			'Share this link with others to let them join your session.',
		Signup: 'Signup',
		'Single line comment': 'Single line comment',
		Spaces: 'Spaces',
		'Start Blank': 'Start Blank',
		'Start Blank in File Mode': 'Start Blank in File Mode',
		'Start New Collab Session': 'Start New Collab Session',
		"Start a collaborative editing session and invite others to code together in real-time. Everyone can see each other's cursors and edits.":
			"Start a collaborative editing session and invite others to code together in real-time. Everyone can see each other's cursors and edits.",
		'Start a new creation': 'Start a new creation',
		'Start multiplayer collaboration session':
			'Start multiplayer collaboration session',
		Submit: 'Submit',
		'Submitted on:': 'Submitted on:',
		'Submitting...': 'Submitting...',
		'Support the Developer': 'Support the Developer',
		'Support the developer': 'Support the developer',
		'Support the developer by pledging some amount':
			'Support the developer by pledging some amount',
		'Switch to full screen preview': 'Switch to full screen preview',
		'Switch to layout with all vertical panes':
			'Switch to layout with all vertical panes',
		'Switch to layout with preview on bottom':
			'Switch to layout with preview on bottom',
		'Switch to layout with preview on left':
			'Switch to layout with preview on left',
		'Switch to layout with preview on left"':
			'Switch to layout with preview on left"',
		'Switch to layout with preview on right':
			'Switch to layout with preview on right',
		'Switch to lighter version for better performance. Removes things like blur etc.':
			'Switch to lighter version for better performance. Removes things like blur etc.',
		Tabs: 'Tabs',
		'Take screenshot of preview': 'Take screenshot of preview',
		Theme: 'Theme',
		'Toggle code pane': 'Toggle code pane',
		'Toggle console': 'Toggle console',
		'Toggle full screen preview': 'Toggle full screen preview',
		'Toggle wrapping of long sentences onto new line':
			'Toggle wrapping of long sentences onto new line',
		'Turning this on will start showing Web Maker in every new tab you open':
			'Turning this on will start showing Web Maker in every new tab you open',
		'Turns on the auto-completion suggestions as you type':
			'Turns on the auto-completion suggestions as you type',
		"Tweet about 'Web Maker'": "Tweet about 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>',
		'Type here to search libraries': 'Type here to search libraries',
		'Upgrade to PRO': 'Upgrade to PRO',
		'Upgrade to PRO and get some advanced superpowers!':
			'Upgrade to PRO and get some advanced superpowers!',
		'Upload Image': 'Upload Image',
		'Upload/Use assets': 'Upload/Use assets',
		'Use Monaco Editor': 'Use Monaco Editor',
		'Use experimental Monaco editor': 'Use experimental Monaco editor',
		'Vote for features you want to see or suggest new ones.':
			'Vote for features you want to see or suggest new ones.',
		'Welcome to Web Maker': 'Welcome to Web Maker',
		'Yes, please import': 'Yes, please import',
		'You have <0>{oldSavedCreationsCount}</0> creations saved in your local machine. Do you want to import those creations in your account so they are more secure and accessible anywhere?':
			function (a) {
				return [
					'You have <0>',
					a('oldSavedCreationsCount'),
					'</0> creations saved in your local machine. Do you want to import those creations in your account so they are more secure and accessible anywhere?'
				];
			}
	}
};
