/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			if (ord) return n == 1 ? 'one' : 'other';
			return n >= 0 && n < 2 ? 'one' : 'other';
		}
	},
	messages: {
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" est <0>open-source</0> sous la <1>MIT License</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.',
		'(Experimental) Switches from CodeMirror to Monaco. Many other settings might not be available in Monaco.':
			'(Exp\xE9rimental) Passe de CodeMirror \xE0 Monaco. De nombreux autres param\xE8tres pourraient ne pas \xEAtre disponibles dans Monaco.',
		'2 files mode creations available in Free plan. To create unlimited files mode creations, upgrade to <0/>.':
			'2 cr\xE9ations de mode fichiers disponibles dans le plan gratuit. Pour cr\xE9er des cr\xE9ations de mode fichiers illimit\xE9es, passez \xE0 <0/>.',
		'3 separate panes to write HTML, CSS and JavaScript. Good for quickly testing something.':
			'3 panneaux s\xE9par\xE9s pour \xE9crire HTML, CSS et JavaScript. Bon pour tester rapidement quelque chose.',
		'Add Library': 'Ajouter une biblioth\xE8que',
		'Add a JS/CSS library': 'Ajouter une biblioth\xE8que JS/CSS',
		'Add collection': 'Ajouter une collection',
		'Add library': 'Ajouter une biblioth\xE8que',
		'Add the closing tag automatically on seeing an opening tag in HTML':
			"Ajoutez automatiquement la balise de fermeture en voyant une balise d'ouverture en HTML",
		Advanced: 'Avanc\xE9',
		All: 'Tout',
		Assets: 'Actifs',
		'Assets feature is available in PRO plan.':
			'La fonctionnalit\xE9 Actifs est disponible dans le plan PRO.',
		'Atomic CSS configuration': 'Configuration CSS atomique',
		'Auto-close tags': 'Fermeture automatique des balises',
		'Auto-complete suggestions': 'Suggestions de saisie automatique',
		'Auto-preview': 'Aper\xE7u automatique',
		'Auto-save': 'Sauvegarde automatique',
		'Auto-save keeps saving your code at regular intervals after you hit save manually the first time':
			'La sauvegarde automatique continue de sauvegarder votre code \xE0 intervalles r\xE9guliers apr\xE8s que vous ayez enregistr\xE9 manuellement la premi\xE8re fois',
		'Choose from popular libraries':
			'Choisissez parmi des biblioth\xE8ques populaires',
		'Clear console (CTRL + L)': 'Effacer la console (CTRL + L)',
		'Clear console (works when console input is focused)':
			"Effacer la console (fonctionne lorsque l'entr\xE9e de la console est focalis\xE9e)",
		'Click to change': 'Cliquez pour changer',
		'Click to edit': 'Cliquez pour \xE9diter',
		'Close saved creations pane':
			'Fermer le panneau des cr\xE9ations sauvegard\xE9es',
		'Close saved creations panel & modals':
			'Fermer le panneau des cr\xE9ations sauvegard\xE9es et les modales',
		'Code blast!': 'Explosion de code !',
		Collab: 'Collab',
		'Collab Session': 'Session de collaboration',
		'Collaboration unavailable offline':
			'Collaboration indisponible hors ligne',
		'Collection name': 'Nom de la collection',
		'Configure and customize settings by clicking the gear icon (<0><1/></0>) in bottom right of the app.':
			"Configurez et personnalisez les param\xE8tres en cliquant sur l'ic\xF4ne d'engrenage (<0><1/></0>) en bas \xE0 droite de l'application.",
		Console: 'Console',
		'Copy URL (or keep clicking to copy other formats)':
			"Copier l'URL (ou continuez \xE0 cliquer pour copier d'autres formats)",
		'Copy link': 'Copier le lien',
		'Create New': 'Cr\xE9er Nouveau',
		'Custom font name here': 'Nom de la police personnalis\xE9e ici',
		'Default CSS preprocessor': 'Pr\xE9processeur CSS par d\xE9faut',
		'Default HTML preprocessor': 'Pr\xE9processeur HTML par d\xE9faut',
		'Default JavaScript preprocessor':
			'Pr\xE9processeur JavaScript par d\xE9faut',
		'Default Preprocessors': 'Pr\xE9processeurs par d\xE9faut',
		Delete: 'Supprimer',
		'Detach preview': "D\xE9tacher l'aper\xE7u",
		Discuss: 'Discuter',
		"Don't ask me again": 'Ne me demandez plus',
		'Double click to toggle code pane':
			'Double-cliquez pour basculer le panneau de code',
		'Double click to toggle console': 'Double-cliquez pour basculer la console',
		'Download game as zip': 'T\xE9l\xE9charger le jeu au format zip',
		'Drop files or click here to upload':
			'D\xE9posez des fichiers ou cliquez ici pour t\xE9l\xE9charger',
		'Edit on CodePen': 'Modifier sur CodePen',
		Editor: '\xC9diteur',
		'Emmet code completion': 'Compl\xE9tion de code Emmet',
		'Enjoy wonderful particle blasts while you type':
			'Profitez de merveilleuses explosions de particules pendant que vous tapez',
		Export: 'Exporter',
		'Export all your creations into a single importable file.':
			'Exportez toutes vos cr\xE9ations dans un seul fichier importable.',
		'Fast/light-weight version': 'Version rapide/l\xE9g\xE8re',
		'Feedback & Suggestions': 'Retour & Suggestions',
		'Fetching files...': 'R\xE9cup\xE9ration des fichiers...',
		'File should be max 300KB in size':
			'Le fichier doit faire au maximum 300 Ko',
		'Files modes is currently only available in Web app. <0>Try the Web app now</0>.':
			"Les modes de fichiers ne sont actuellement disponibles que dans l'application Web. <0>Essayez l'application Web maintenant</0>.",
		Find: 'Trouver',
		'Find & replace': 'Trouver & remplacer',
		'Follow <0>@webmakerApp</0> to know about the new upcoming features!':
			'Suivez <0>@webmakerApp</0> pour conna\xEEtre les nouvelles fonctionnalit\xE9s \xE0 venir !',
		Font: 'Police',
		'Font Size': 'Taille de police',
		Fork: 'Fork',
		'Fork this creation': 'Forker cette cr\xE9ation',
		'Format Code': 'Format de code',
		'Format code': 'Format de code',
		Fun: 'Amusant',
		General: 'G\xE9n\xE9ral',
		Get: 'Obtenir',
		Global: 'Global',
		'Grid view': 'Vue en grille',
		Help: 'Aide',
		'Hi, <0>Kushagra</0> here! Web Maker is a free and open-source project. To keep myself motivated for working on such open-source and free <1>side projects</1>, I am accepting donations. Your pledge, no matter how small, will act as an appreciation towards my work and keep me going forward making Web Maker more awesome\uD83D\uDD25. So please consider donating. \uD83D\uDE4F\uD83C\uDFFC (could be as small as $1/month).':
			"Salut, <0>Kushagra</0> ici ! Web Maker est un projet gratuit et open-source. Pour me garder motiv\xE9 \xE0 travailler sur de tels <1>projets secondaires</1> open-source et gratuits, j'accepte des dons. Votre contribution, peu importe sa taille, agira comme une appr\xE9ciation de mon travail et me permettra d'aller de l'avant pour rendre Web Maker encore plus g\xE9nial\uD83D\uDD25. Alors, merci de consid\xE9rer faire un don. \uD83D\uDE4F\uD83C\uDFFC (cela pourrait \xEAtre aussi petit que 1 $/mois).",
		'Hover/Focus to preview': 'Survolez/Focalisez pour pr\xE9visualiser',
		'I wish Web Maker could...': 'Je souhaite que Web Maker puisse...',
		'If any loop iteration takes more than the defined time, it is detected as a potential infinite loop and further iterations are stopped.':
			'Si une it\xE9ration de boucle prend plus de temps que le temps d\xE9fini, elle est d\xE9tect\xE9e comme une boucle infinie potentielle et les it\xE9rations suivantes sont arr\xEAt\xE9es.',
		'If you are an existing Chrome extension user, you can import your creations from there to here. <0>Learn how to export/import</0>.':
			"Si vous \xEAtes un utilisateur existant de l'extension Chrome, vous pouvez importer vos cr\xE9ations d'ici vers l\xE0. <0>Apprenez \xE0 exporter/importer</0>.",
		Import: 'Importer',
		'Import your creations in your account':
			'Importez vos cr\xE9ations dans votre compte',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			"Importez vos cr\xE9ations. Seul le fichier que vous exportez via le bouton 'Exporter' peut \xEAtre import\xE9.",
		'Indent code left': 'Indenter le code \xE0 gauche',
		'Indent code right': 'Indenter le code \xE0 droite',
		Indentation: 'Indentation',
		'Indentation Size': "Taille de l'indentation",
		"It's okay if you don't want to. You can simply logout and access them anytime on this browser.":
			"C'est okay si vous ne voulez pas. Vous pouvez simplement vous d\xE9connecter et y acc\xE9der \xE0 tout moment sur ce navigateur.",
		'Join a community of 70,000+ Developers':
			'Rejoignez une communaut\xE9 de plus de 70 000 d\xE9veloppeurs',
		'Js13kGames Mode': 'Mode Js13kGames',
		'Key bindings': 'Raccourcis clavier',
		'Keyboard Shortcuts': 'Raccourcis clavier',
		'Keyboard shortcuts': 'Raccourcis clavier',
		Language: 'Langue',
		'Leave Session': 'Quitter la session',
		'Lets start!': 'Commen\xE7ons !',
		License: 'Licence',
		'Like this app? Please <0>rate it here</0>.':
			'Aimez-vous cette application ? Veuillez <0>la noter ici</0>.',
		'Line wrap': 'Retour \xE0 la ligne',
		'List view': 'Vue en liste',
		'Loads the last open creation when app starts':
			"Charge la derni\xE8re cr\xE9ation ouverte lorsque l'application d\xE9marre",
		'Login & upgrade to PRO': 'Connexion et mise \xE0 niveau vers PRO',
		'Login / Signup': 'Connexion / Inscription',
		'Login with Github': 'Connexion avec Github',
		'Login with Google': 'Connexion avec Google',
		'Login/Signup': 'Connexion/Inscription',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Fait avec <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> par <2>Kushagra Gour</2>',
		'Mail me': '\xC9cris-moi',
		'Make a monthly pledge on Patreon': 'Faites un don mensuel sur Patreon',
		'Make the app ready to build some games for <0>Js13kGames</0>.':
			"Pr\xE9parez l'application \xE0 cr\xE9er des jeux pour <0>Js13kGames</0>.",
		Manage: 'G\xE9rer',
		'Manage your PRO subscription': 'G\xE9rer votre abonnement PRO',
		'Manage your code in files. Just like you would have files on your local machine.':
			'G\xE9rez votre code dans des fichiers. Tout comme vous auriez des fichiers sur votre machine locale.',
		'Maximize pane': 'Agrandir le panneau',
		'Maximum time allowed in a loop iteration':
			'Temps maximum autoris\xE9 dans une it\xE9ration de boucle',
		'Minimise pane': 'R\xE9duire le panneau',
		'Most recent first': 'Les plus r\xE9cents en premier',
		'Most upvoted first': 'Les plus vot\xE9s en premier',
		'Multiplayer session active': 'Session multijoueur active',
		'My Library': 'Ma Biblioth\xE8que',
		New: 'Nouveau',
		'No feedback yet. Be the first!':
			'Pas encore de retour. Soyez le premier !',
		'No files uploaded yet': "Aucun fichier t\xE9l\xE9charg\xE9 pour l'instant",
		'No items in this collection.':
			'Aucun \xE9l\xE9ment dans cette collection.',
		'No match found.': 'Aucun r\xE9sultat trouv\xE9.',
		'Note: You can load external scripts only from following domains:':
			'Remarque : Vous ne pouvez charger des scripts externes que depuis les domaines suivants :',
		'Nothing saved here.': "Rien n'est enregistr\xE9 ici.",
		'Once you stop typing, the preview waits for this much time before getting updated. Too low value might choke your browser!':
			"Une fois que vous arr\xEAtez de taper, l'aper\xE7u attend ce temps avant de se mettre \xE0 jour. Une valeur trop basse pourrait bloquer votre navigateur !",
		Open: 'Ouvrir',
		'Open Web Maker anytime by clicking the<0><1/></0> button in top-right side of your browser.':
			'Ouvrez Web Maker \xE0 tout moment en cliquant sur le<0><1/></0> bouton en haut \xE0 droite de votre navigateur.',
		'Open Web Maker anytime by visiting <0>https://webmaker.app/create/</0> - Even when you are offline! It just works! \uD83D\uDE31 <1>Drag the following bookmarklet</1> on your bookmark bar to create a quick access shortcut:':
			"Ouvrez Web Maker \xE0 tout moment en visitant <0>https://webmaker.app/create/</0> - M\xEAme lorsque vous \xEAtes hors ligne ! \xC7a fonctionne ! \uD83D\uDE31 <1>Faites glisser le bookmarklet suivant</1> sur votre barre de favoris pour cr\xE9er un raccourci d'acc\xE8s rapide :",
		'Open a saved creation (Ctrl/\u2318 + O)':
			'Ouvrir une cr\xE9ation enregistr\xE9e (Ctrl/\u2318 + O)',
		'Open list of saved creations':
			'Ouvrir la liste des cr\xE9ations enregistr\xE9es',
		'Or, make a one time donation': 'Ou, faites un don unique',
		'Other font from system': 'Autre police du syst\xE8me',
		Participants: 'Participants',
		'Powered by cdnjs': 'Propuls\xE9 par cdnjs',
		'Preserve console logs': 'Conserver les journaux de la console',
		'Preserve last written code': 'Conserver le dernier code \xE9crit',
		'Preserves the console logs across your preview refreshes':
			"Conserve les journaux de la console lors de vos actualisations d'aper\xE7u",
		'Preview refresh wait time':
			"Temps d'attente pour l'actualisation de l'aper\xE7u",
		'Preview will refresh when you resize the preview pane':
			"L'aper\xE7u se mettra \xE0 jour lorsque vous redimensionnerez le panneau d'aper\xE7u",
		'Put each library in new line':
			'Mettez chaque biblioth\xE8que sur une nouvelle ligne',
		'Read more': 'En savoir plus',
		'Read the documentation.': 'Lisez la documentation.',
		'Realign code': 'R\xE9ajuster le code',
		'Refresh preview': "Actualiser l'aper\xE7u",
		'Refresh preview on resize':
			"Actualiser l'aper\xE7u lors du redimensionnement",
		"Refreshes the preview as you code. Otherwise use the 'Run' button":
			"Actualise l'aper\xE7u pendant que vous codez. Sinon, utilisez le bouton 'Ex\xE9cuter'",
		'Replace new tab page': 'Remplacer la page nouvel onglet',
		'Report a bug': 'Signaler un bug',
		'Review Web Maker': '\xC9valuer Web Maker',
		Run: 'Ex\xE9cuter',
		'Run Prettier': 'Ex\xE9cuter Prettier',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			"Ex\xE9cuter l'aper\xE7u (Ctrl/\u2318 + Shift + 5)",
		Save: 'Enregistrer',
		'Save as HTML file': 'Enregistrer en tant que fichier HTML',
		'Save current creation (Ctrl/\u2318 + S)':
			'Enregistrer la cr\xE9ation actuelle (Ctrl/\u2318 + S)',
		'Save current creations': 'Enregistrer les cr\xE9ations actuelles',
		'Search files': 'Rechercher des fichiers',
		'Search your creations here...': 'Recherchez vos cr\xE9ations ici...',
		'See awesome libraries used':
			'Voir les biblioth\xE8ques g\xE9niales utilis\xE9es',
		'See changelog': 'Voir le changelog',
		'See profile or Logout': 'Voir le profil ou Se d\xE9connecter',
		'Select next match': 'S\xE9lectionner la correspondance suivante',
		'Select previous match':
			'S\xE9lectionner la correspondance pr\xE9c\xE9dente',
		Settings: 'Param\xE8tres',
		Share: 'Partager',
		'Share Link': 'Partager le lien',
		'Share Web Maker': 'Partager Web Maker',
		'Share this creation publicly': 'Partager cette cr\xE9ation publiquement',
		'Share this link with others to let them join your session.':
			"Partagez ce lien avec d'autres pour leur permettre de rejoindre votre session.",
		'Single line comment': 'Commentaire sur une seule ligne',
		Spaces: 'Espaces',
		'Start Blank': 'D\xE9marrer vide',
		'Start Blank in File Mode': 'D\xE9marrer vide en mode fichier',
		'Start New Collab Session':
			'D\xE9marrer une nouvelle session de collaboration',
		"Start a collaborative editing session and invite others to code together in real-time. Everyone can see each other's cursors and edits.":
			"D\xE9marrez une session d'\xE9dition collaborative et invitez d'autres \xE0 coder ensemble en temps r\xE9el. Tout le monde peut voir les curseurs et les modifications des autres.",
		'Start a new creation': 'D\xE9marrer une nouvelle cr\xE9ation',
		'Start multiplayer collaboration session':
			'D\xE9marrer une session de collaboration multijoueur',
		Submit: 'Soumettre',
		'Submitted on:': 'Soumis le :',
		'Submitting...': 'Soumission en cours...',
		'Support the Developer': 'Soutenir le d\xE9veloppeur',
		'Switch to layout with all vertical panes':
			'Passer \xE0 une mise en page avec tous les panneaux verticaux',
		'Switch to layout with preview on bottom':
			'Passer \xE0 une mise en page avec un aper\xE7u en bas',
		'Switch to layout with preview on left':
			'Passer \xE0 une mise en page avec un aper\xE7u \xE0 gauche',
		'Switch to layout with preview on right':
			'Passer \xE0 une mise en page avec un aper\xE7u \xE0 droite',
		'Switch to lighter version for better performance. Removes things like blur etc.':
			'Passer \xE0 une version plus l\xE9g\xE8re pour de meilleures performances. Supprime des \xE9l\xE9ments comme le flou, etc.',
		Tabs: 'Onglets',
		'Take screenshot of preview':
			"Prendre une capture d'\xE9cran de l'aper\xE7u",
		Theme: 'Th\xE8me',
		'Toggle code pane': 'Basculer le panneau de code',
		'Toggle console': 'Basculer la console',
		'Toggle full screen preview': "Basculer l'aper\xE7u en plein \xE9cran",
		'Toggle wrapping of long sentences onto new line':
			'Basculer le passage des longues phrases \xE0 la nouvelle ligne',
		'Turning this on will start showing Web Maker in every new tab you open':
			'Activer cette option affichera Web Maker dans chaque nouvel onglet que vous ouvrez',
		'Turns on the auto-completion suggestions as you type':
			'Active les suggestions de compl\xE9tion automatique au fur et \xE0 mesure que vous tapez',
		"Tweet about 'Web Maker'": "Tweeter \xE0 propos de 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'Tweetez vos demandes de fonctionnalit\xE9s, commentaires et suggestions \xE0 <0>@webmakerApp</0>',
		'Type here to search libraries':
			'Tapez ici pour rechercher des biblioth\xE8ques',
		'Upgrade to PRO': 'Passer \xE0 PRO',
		'Upgrade to PRO and get some advanced superpowers!':
			'Passez \xE0 PRO et obtenez des super-pouvoirs avanc\xE9s !',
		'Upload Image': 'T\xE9l\xE9charger une image',
		'Upload/Use assets': 'T\xE9l\xE9charger/Utiliser des ressources',
		'Use Monaco Editor': "Utiliser l'\xE9diteur Monaco",
		'Use experimental Monaco editor':
			"Utiliser l'\xE9diteur Monaco exp\xE9rimental",
		'Vote for features you want to see or suggest new ones.':
			'Votez pour les fonctionnalit\xE9s que vous souhaitez voir ou sugg\xE9rez-en de nouvelles.',
		'Welcome to Web Maker': 'Bienvenue sur Web Maker',
		'Yes, please import': 'Oui, veuillez importer',
		'You have <0>{oldSavedCreationsCount}</0> creations saved in your local machine. Do you want to import those creations in your account so they are more secure and accessible anywhere?':
			function (a) {
				return [
					'Vous avez <0>',
					a('oldSavedCreationsCount'),
					"</0> cr\xE9ations enregistr\xE9es sur votre machine locale. Voulez-vous importer ces cr\xE9ations dans votre compte afin qu'elles soient plus s\xE9curis\xE9es et accessibles partout ?"
				];
			}
	}
};
