/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			if (ord)
				return n == 1
					? 'one'
					: n == 2 || n == 3
						? 'two'
						: n == 4
							? 'few'
							: n == 6
								? 'many'
								: 'other';
			return n >= 0 && n <= 1 ? 'one' : 'other';
		}
	},
	messages: {
		'"Web Maker" <0>CHill</0>.': '"Web Maker" <0>CHill</0>.',
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.',
		'Add Library':
			'\u0932\u093E\u0907\u092C\u094D\u0930\u0947\u0930\u0940 \u091C\u094B\u0921\u093C\u0947\u0902',
		'Add a JS/CSS library': 'Add a JS/CSS library',
		'Add library':
			'\u0932\u093E\u0907\u092C\u094D\u0930\u0947\u0930\u0940 \u091C\u094B\u0921\u093C\u0947\u0902',
		Assets: 'Assets',
		Chat: 'Chat',
		'Choose from popular libraries': 'Choose from popular libraries',
		'Clear console (CTRL + L)': 'Clear console (CTRL + L)',
		'Clear console (works when console input is focused)':
			'Clear console (works when console input is focused)',
		'Close saved creations pane': 'Close saved creations pane',
		'Close saved creations panel & modals':
			'Close saved creations panel & modals',
		Console: 'Console',
		'Detach Preview': 'Detach Preview',
		'Detach preview': 'Detach preview',
		Discuss: 'Discuss',
		Donate: '\u0926\u093E\u0928 \u0915\u0930\u0947\u0902',
		'Double click to toggle console': 'Double click to toggle console',
		'Download game as zip': 'Download game as zip',
		'Edit on CodePen': 'Edit on CodePen',
		Editor: 'Editor',
		'Emmet code completion': 'Emmet code completion',
		Export: 'Export',
		'Export all your creations into a single importable file.':
			'Export all your creations into a single importable file.',
		Find: 'Find',
		'Find & replace': 'Find & replace',
		Fork: 'Fork',
		'Fork this creation': 'Fork this creation',
		Get: 'Get',
		Global: 'Global',
		Help: 'Help',
		Import: 'Import',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			"Import your creations. Only the file that you export through the 'Export' button can be imported.",
		'Indent code left': 'Indent code left',
		'Indent code right': 'Indent code right',
		'Keyboard Shortcuts': 'Keyboard Shortcuts',
		'Keyboard shortcuts': 'Keyboard shortcuts',
		License: 'License',
		'Like this app? Please <0>rate it here</0>.':
			'Like this app? Please <0>rate it here</0>.',
		'Like this extension? Please <0>rate it here</0>.':
			'Like this extension? Please <0>rate it here</0>.',
		Login: '\u0932\u0949\u0917\u093F\u0928',
		'Login/Signup':
			'\u0932\u0949\u0917\u093F\u0928 / \u0938\u093E\u0907\u0928\u092A',
		'Made with <0>\uD83D\uDC96</0>& <1> \uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'<0>\uD83D\uDC96</0> \u0914\u0930 <1> \uD83D\uDE4C</1> \u0938\u0947 <2>\u0915\u0941\u0936\u093E\u0917\u094D\u0930 \u0917\u094C\u0930</2> \u0926\u094D\u0935\u093E\u0930\u093E \u092C\u0928\u093E\u092F\u093E \u0917\u092F\u093E',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>',
		'Mail me': 'Mail me',
		Manage: 'Manage',
		'Manage your PRO subscription': 'Manage your PRO subscription',
		'My Library': 'My Library',
		'My Library ({0})': function (a) {
			return [
				'\u092E\u0947\u0930\u0940 \u0930\u091A\u0928\u093E\u090F\u0901 (',
				a('0'),
				')'
			];
		},
		New: '\u0928\u092F\u093E \u092C\u0928\u093E\u090F\u0901',
		'No match found.':
			'\u0915\u0941\u091B \u0928\u0939\u0940\u0902 \u092E\u093F\u0932\u093E',
		'Note: You can load external scripts from following domains:':
			'Note: You can load external scripts from following domains:',
		'Note: You can load external scripts only from following domains:':
			'Note: You can load external scripts only from following domains:',
		'Nothing saved here.': 'Nothing saved here.',
		Open: '\u0916\u094B\u0932\u0947\u0902',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'Open a saved creation (Ctrl/\u2318 + O)',
		'Open list of saved creations': 'Open list of saved creations',
		'Powered by cdnjs': 'Powered by cdnjs',
		'Put each library in new line':
			'\u0939\u0930 \u0932\u093E\u0907\u092C\u094D\u0930\u0947\u0930\u0940 \u0928\u0908 \u0932\u093E\u0907\u0928 \u092E\u0948\u0902 \u0932\u093F\u0916\u0947\u0902',
		'Read more': '\u0914\u0930 \u091C\u093E\u0928\u0947\u0902',
		'Read the documentation.': 'Read the documentation.',
		'Realign code': 'Realign code',
		'Refresh preview': 'Refresh preview',
		'Report a bug': 'Report a bug',
		'Review Web Maker': 'Review Web Maker',
		Run: '\u091A\u0932\u093E\u090F\u0901',
		'Run Prettier': 'Run Prettier',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'Run preview (Ctrl/\u2318 + Shift + 5)',
		Save: '\u0938\u0941\u0930\u0915\u094D\u0937\u093F\u0924 \u0915\u0930\u0947\u0902',
		'Save as HTML file': 'Save as HTML file',
		'Save current creation (Ctrl/\u2318 + S)':
			'Save current creation (Ctrl/\u2318 + S)',
		'Save current creations': 'Save current creations',
		'Search your creations here...': 'Search your creations here...',
		'See Changelog': 'See Changelog',
		'See awesome libraries used': 'See awesome libraries used',
		'See changelog': 'See changelog',
		'See profile or Logout': 'See profile or Logout',
		'Select next match': 'Select next match',
		'Select previous match': 'Select previous match',
		Settings: 'Settings',
		Share: 'Share',
		'Share Web Maker': 'Share Web Maker',
		'Share this creation publicly': 'Share this creation publicly',
		Signup: 'Signup',
		'Single line comment': 'Single line comment',
		'Start a new creation': 'Start a new creation',
		'Support the developer': 'Support the developer',
		'Support the developer by pledging some amount':
			'Support the developer by pledging some amount',
		'Switch to full screen preview': 'Switch to full screen preview',
		'Switch to layout with all vertical panes':
			'Switch to layout with all vertical panes',
		'Switch to layout with preview on bottom':
			'Switch to layout with preview on bottom',
		'Switch to layout with preview on left':
			'Switch to layout with preview on left',
		'Switch to layout with preview on left"':
			'Switch to layout with preview on left"',
		'Switch to layout with preview on right':
			'Switch to layout with preview on right',
		'Take screenshot of preview': 'Take screenshot of preview',
		'Toggle console': 'Toggle console',
		'Toggle full screen preview': 'Toggle full screen preview',
		"Tweet about 'Web Maker'": "Tweet about 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'\u0939\u0932\u0935\u093E \u0939\u093F\u092F\u093E\u0901 \u092F\u0947 \u0924\u094B <0>\u091A\u092E\u092A\u094D\u0930\u0936</0>',
		'Type here to search libraries': 'Type here to search libraries',
		'Upgrade to PRO and get some advanced superpowers!':
			'Upgrade to PRO and get some advanced superpowers!',
		'Upload Image': 'Upload Image',
		'Upload/Use assets': 'Upload/Use assets'
	}
};
