/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			if (ord) return 'other';
			return 'other';
		}
	},
	messages: {
		'"Web Maker" <0>CHill</0>.': '"Web Maker" <0>CHill</0>.',
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" \u662F <0>\u5F00\u6E90</0> \u7684\uFF0C\u9075\u5FAA <1>MIT \u8BB8\u53EF\u8BC1</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'\'\u54CE\u5440\uFF01\u6240\u9009\u6587\u4EF6\u5DF2\u635F\u574F\u3002\u8BF7\u9009\u62E9\u4E00\u4E2A\u901A\u8FC7\u70B9\u51FB "\u5BFC\u51FA" \u6309\u94AE\u751F\u6210\u7684\u6587\u4EF6\u3002',
		'(Experimental) Switches from CodeMirror to Monaco. Many other settings might not be available in Monaco.':
			'\uFF08\u5B9E\u9A8C\u6027\uFF09\u4ECE CodeMirror \u5207\u6362\u5230 Monaco\u3002\u8BB8\u591A\u5176\u4ED6\u8BBE\u7F6E\u53EF\u80FD\u5728 Monaco \u4E2D\u4E0D\u53EF\u7528\u3002',
		'2 files mode creations available in Free plan. To create unlimited files mode creations, upgrade to <0/>.':
			'\u514D\u8D39\u8BA1\u5212\u4E2D\u53EF\u521B\u5EFA 2 \u4E2A\u6587\u4EF6\u6A21\u5F0F\u3002\u8981\u521B\u5EFA\u65E0\u9650\u6587\u4EF6\u6A21\u5F0F\uFF0C\u8BF7\u5347\u7EA7\u5230 <0/>\u3002',
		'3 separate panes to write HTML, CSS and JavaScript. Good for quickly testing something.':
			'3 \u4E2A\u72EC\u7ACB\u7684\u7A97\u683C\u7528\u4E8E\u7F16\u5199 HTML\u3001CSS \u548C JavaScript\u3002\u9002\u5408\u5FEB\u901F\u6D4B\u8BD5\u67D0\u4E9B\u5185\u5BB9\u3002',
		'Add Library': '\u6DFB\u52A0\u5E93',
		'Add a JS/CSS library': '\u6DFB\u52A0 JS/CSS \u5E93',
		'Add collection': '\u6DFB\u52A0\u96C6\u5408',
		'Add library': '\u6DFB\u52A0\u5E93',
		'Add the closing tag automatically on seeing an opening tag in HTML':
			'\u5728 HTML \u4E2D\u770B\u5230\u5F00\u6807\u7B7E\u65F6\u81EA\u52A8\u6DFB\u52A0\u95ED\u5408\u6807\u7B7E',
		Advanced: '\u9AD8\u7EA7',
		All: '\u6240\u6709',
		Assets: '\u8D44\u4EA7',
		'Assets feature is available in PRO plan.':
			'\u8D44\u4EA7\u529F\u80FD\u5728 PRO \u8BA1\u5212\u4E2D\u53EF\u7528\u3002',
		'Atomic CSS configuration': '\u539F\u5B50 CSS \u914D\u7F6E',
		'Auto-close tags': '\u81EA\u52A8\u5173\u95ED\u6807\u7B7E',
		'Auto-complete suggestions': '\u81EA\u52A8\u5B8C\u6210\u5EFA\u8BAE',
		'Auto-preview': '\u81EA\u52A8\u9884\u89C8',
		'Auto-save': '\u81EA\u52A8\u4FDD\u5B58',
		'Auto-save keeps saving your code at regular intervals after you hit save manually the first time':
			'\u81EA\u52A8\u4FDD\u5B58\u4F1A\u5728\u60A8\u7B2C\u4E00\u6B21\u624B\u52A8\u70B9\u51FB\u4FDD\u5B58\u540E\u5B9A\u671F\u4FDD\u5B58\u60A8\u7684\u4EE3\u7801',
		Chat: 'Chat',
		'Choose from popular libraries':
			'\u4ECE\u6D41\u884C\u5E93\u4E2D\u9009\u62E9',
		'Clear console (CTRL + L)': '\u6E05\u9664\u63A7\u5236\u53F0 (CTRL + L)',
		'Clear console (works when console input is focused)':
			'\u6E05\u9664\u63A7\u5236\u53F0\uFF08\u5728\u63A7\u5236\u53F0\u8F93\u5165\u6846\u805A\u7126\u65F6\u6709\u6548\uFF09',
		'Click to change': '\u70B9\u51FB\u66F4\u6539',
		'Click to edit': '\u70B9\u51FB\u7F16\u8F91',
		'Close saved creations pane':
			'\u5173\u95ED\u5DF2\u4FDD\u5B58\u521B\u4F5C\u7A97\u683C',
		'Close saved creations panel & modals':
			'\u5173\u95ED\u5DF2\u4FDD\u5B58\u521B\u4F5C\u9762\u677F\u548C\u6A21\u6001\u6846',
		'Code blast!': '\u4EE3\u7801\u7206\u53D1\uFF01',
		Collab: '\u534F\u4F5C',
		'Collab Session': '\u534F\u4F5C\u4F1A\u8BAE',
		'Collaboration unavailable offline':
			'\u79BB\u7EBF\u65F6\u65E0\u6CD5\u534F\u4F5C',
		'Collection name': '\u96C6\u5408\u540D\u79F0',
		'Configure and customize settings by clicking the gear icon (<0><1/></0>) in bottom right of the app.':
			'\u901A\u8FC7\u70B9\u51FB\u5E94\u7528\u53F3\u4E0B\u89D2\u7684\u9F7F\u8F6E\u56FE\u6807 (<0><1/></0>) \u6765\u914D\u7F6E\u548C\u81EA\u5B9A\u4E49\u8BBE\u7F6E\u3002',
		Console: '\u63A7\u5236\u53F0',
		'Copy URL (or keep clicking to copy other formats)':
			'\u590D\u5236 URL\uFF08\u6216\u7EE7\u7EED\u70B9\u51FB\u4EE5\u590D\u5236\u5176\u4ED6\u683C\u5F0F\uFF09',
		'Copy link': '\u590D\u5236\u94FE\u63A5',
		'Create New': '\u521B\u5EFA\u65B0\u5185\u5BB9',
		'Custom font name here':
			'\u5728\u6B64\u8F93\u5165\u81EA\u5B9A\u4E49\u5B57\u4F53\u540D\u79F0',
		'Default CSS preprocessor': '\u9ED8\u8BA4 CSS \u9884\u5904\u7406\u5668',
		'Default HTML preprocessor': '\u9ED8\u8BA4 HTML \u9884\u5904\u7406\u5668',
		'Default JavaScript preprocessor':
			'\u9ED8\u8BA4 JavaScript \u9884\u5904\u7406\u5668',
		'Default Preprocessors': '\u9ED8\u8BA4\u9884\u5904\u7406\u5668',
		Delete: '\u5220\u9664',
		'Detach Preview': 'Detach Preview',
		'Detach preview': '\u5206\u79BB\u9884\u89C8',
		Discuss: '\u8BA8\u8BBA',
		"Don't ask me again": '\u4E0D\u8981\u518D\u95EE\u6211',
		Donate: 'Donate',
		'Double click to toggle code pane':
			'\u53CC\u51FB\u5207\u6362\u4EE3\u7801\u9762\u677F',
		'Double click to toggle console':
			'\u53CC\u51FB\u5207\u6362\u63A7\u5236\u53F0',
		'Download game as zip': '\u4E0B\u8F7D\u6E38\u620F\u4E3A zip',
		'Drop files or click here to upload':
			'\u62D6\u653E\u6587\u4EF6\u6216\u70B9\u51FB\u6B64\u5904\u4E0A\u4F20',
		'Edit on CodePen': '\u5728 CodePen \u4E0A\u7F16\u8F91',
		Editor: '\u7F16\u8F91\u5668',
		'Emmet code completion': 'Emmet \u4EE3\u7801\u8865\u5168',
		'Enjoy wonderful particle blasts while you type':
			'\u5728\u8F93\u5165\u65F6\u4EAB\u53D7\u7CBE\u5F69\u7684\u7C92\u5B50\u7206\u70B8',
		Export: '\u5BFC\u51FA',
		'Export all your creations into a single importable file.':
			'\u5C06\u60A8\u6240\u6709\u7684\u521B\u4F5C\u5BFC\u51FA\u4E3A\u4E00\u4E2A\u53EF\u5BFC\u5165\u7684\u6587\u4EF6\u3002',
		'Fast/light-weight version': '\u5FEB\u901F/\u8F7B\u91CF\u7EA7\u7248\u672C',
		'Feedback & Suggestions': '\u53CD\u9988\u4E0E\u5EFA\u8BAE',
		'Fetching files...': '\u6B63\u5728\u83B7\u53D6\u6587\u4EF6...',
		'File should be max 300KB in size':
			'\u6587\u4EF6\u5927\u5C0F\u5E94\u6700\u5927\u4E3A 300KB',
		'Files modes is currently only available in Web app. <0>Try the Web app now</0>.':
			'\u6587\u4EF6\u6A21\u5F0F\u76EE\u524D\u4EC5\u5728Web\u5E94\u7528\u7A0B\u5E8F\u4E2D\u53EF\u7528\u3002<0>\u7ACB\u5373\u5C1D\u8BD5Web\u5E94\u7528\u7A0B\u5E8F</0>\u3002',
		Find: '\u67E5\u627E',
		'Find & replace': '\u67E5\u627E\u548C\u66FF\u6362',
		'Follow <0>@webmakerApp</0> to know about the new upcoming features!':
			'\u5173\u6CE8 <0>@webmakerApp</0> \u4EE5\u4E86\u89E3\u5373\u5C06\u63A8\u51FA\u7684\u65B0\u529F\u80FD\uFF01',
		Font: '\u5B57\u4F53',
		'Font Size': '\u5B57\u4F53\u5927\u5C0F',
		Fork: '\u5206\u53C9',
		'Fork this creation': '\u5206\u53C9\u6B64\u521B\u4F5C',
		'Format Code': '\u683C\u5F0F\u5316\u4EE3\u7801',
		'Format code': '\u683C\u5F0F\u5316\u4EE3\u7801',
		Fun: '\u4E50\u8DA3',
		General: '\u5E38\u89C4',
		Get: '\u83B7\u53D6',
		Global: '\u5168\u5C40',
		'Grid view': '\u7F51\u683C\u89C6\u56FE',
		Help: '\u5E2E\u52A9',
		'Hi, <0>Kushagra</0> here! Web Maker is a free and open-source project. To keep myself motivated for working on such open-source and free <1>side projects</1>, I am accepting donations. Your pledge, no matter how small, will act as an appreciation towards my work and keep me going forward making Web Maker more awesome\uD83D\uDD25. So please consider donating. \uD83D\uDE4F\uD83C\uDFFC (could be as small as $1/month).':
			'\u55E8\uFF0C<0>Kushagra</0>\u5728\u8FD9\u91CC\uFF01Web Maker\u662F\u4E00\u4E2A\u514D\u8D39\u548C\u5F00\u6E90\u7684\u9879\u76EE\u3002\u4E3A\u4E86\u4FDD\u6301\u6211\u5728\u8FD9\u6837\u7684\u5F00\u6E90\u548C\u514D\u8D39<1>\u526F\u9879\u76EE</1>\u4E0A\u7684\u5DE5\u4F5C\u52A8\u529B\uFF0C\u6211\u6B63\u5728\u63A5\u53D7\u6350\u8D60\u3002\u60A8\u7684\u627F\u8BFA\uFF0C\u65E0\u8BBA\u591A\u5C0F\uFF0C\u90FD\u5C06\u4F5C\u4E3A\u5BF9\u6211\u5DE5\u4F5C\u7684\u8BA4\u53EF\uFF0C\u5E76\u8BA9\u6211\u7EE7\u7EED\u52AA\u529B\u8BA9Web Maker\u53D8\u5F97\u66F4\u68D2\uD83D\uDD25\u3002\u6240\u4EE5\u8BF7\u8003\u8651\u6350\u8D60\u3002\uD83D\uDE4F\uD83C\uDFFC\uFF08\u53EF\u4EE5\u5C0F\u5230\u6BCF\u6708$1\uFF09\u3002',
		'Hover/Focus to preview': '\u60AC\u505C/\u805A\u7126\u4EE5\u9884\u89C8',
		'I wish Web Maker could...': '\u6211\u5E0C\u671BWeb Maker\u80FD\u591F...',
		'If any loop iteration takes more than the defined time, it is detected as a potential infinite loop and further iterations are stopped.':
			'\u5982\u679C\u4EFB\u4F55\u5FAA\u73AF\u8FED\u4EE3\u8D85\u8FC7\u5B9A\u4E49\u7684\u65F6\u95F4\uFF0C\u5C06\u88AB\u68C0\u6D4B\u4E3A\u6F5C\u5728\u7684\u65E0\u9650\u5FAA\u73AF\uFF0C\u5E76\u505C\u6B62\u8FDB\u4E00\u6B65\u7684\u8FED\u4EE3\u3002',
		'If you are an existing Chrome extension user, you can import your creations from there to here. <0>Learn how to export/import</0>.':
			'\u5982\u679C\u60A8\u662F\u73B0\u6709\u7684Chrome\u6269\u5C55\u7528\u6237\uFF0C\u53EF\u4EE5\u4ECE\u90A3\u91CC\u5BFC\u5165\u60A8\u7684\u521B\u4F5C\u5230\u8FD9\u91CC\u3002<0>\u4E86\u89E3\u5982\u4F55\u5BFC\u51FA/\u5BFC\u5165</0>\u3002',
		Import: '\u5BFC\u5165',
		'Import your creations in your account':
			'\u5728\u60A8\u7684\u5E10\u6237\u4E2D\u5BFC\u5165\u60A8\u7684\u521B\u4F5C',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			'\u5BFC\u5165\u60A8\u7684\u521B\u4F5C\u3002\u53EA\u6709\u901A\u8FC7\u201C\u5BFC\u51FA\u201D\u6309\u94AE\u5BFC\u51FA\u7684\u6587\u4EF6\u624D\u80FD\u88AB\u5BFC\u5165\u3002',
		'Indent code left': '\u5DE6\u7F29\u8FDB\u4EE3\u7801',
		'Indent code right': '\u53F3\u7F29\u8FDB\u4EE3\u7801',
		Indentation: '\u7F29\u8FDB',
		'Indentation Size': '\u7F29\u8FDB\u5927\u5C0F',
		"It's okay if you don't want to. You can simply logout and access them anytime on this browser.":
			'\u5982\u679C\u60A8\u4E0D\u60F3\u8FD9\u6837\u4E5F\u6CA1\u5173\u7CFB\u3002\u60A8\u53EF\u4EE5\u7B80\u5355\u5730\u6CE8\u9500\uFF0C\u5E76\u968F\u65F6\u5728\u6B64\u6D4F\u89C8\u5668\u4E0A\u8BBF\u95EE\u5B83\u4EEC\u3002',
		'Join a community of 70,000+ Developers':
			'\u52A0\u5165\u4E00\u4E2A\u62E5\u670970,000+\u5F00\u53D1\u8005\u7684\u793E\u533A',
		'Js13kGames Mode': 'Js13kGames \u6A21\u5F0F',
		'Key bindings': '\u6309\u952E\u7ED1\u5B9A',
		'Keyboard Shortcuts': '\u952E\u76D8\u5FEB\u6377\u952E',
		'Keyboard shortcuts': '\u952E\u76D8\u5FEB\u6377\u952E',
		Language: '\u8BED\u8A00',
		'Leave Session': '\u79BB\u5F00\u4F1A\u8BDD',
		'Lets start!': '\u8BA9\u6211\u4EEC\u5F00\u59CB\u5427\uFF01',
		License: '\u8BB8\u53EF\u8BC1',
		'Like this app? Please <0>rate it here</0>.':
			'\u559C\u6B22\u8FD9\u4E2A\u5E94\u7528\u5417\uFF1F\u8BF7\u5728\u8FD9\u91CC<0>\u8BC4\u5206</0>\u3002',
		'Like this extension? Please <0>rate it here</0>.':
			'Like this extension? Please <0>rate it here</0>.',
		'Line wrap': '\u6362\u884C',
		'List view': '\u5217\u8868\u89C6\u56FE',
		'Loads the last open creation when app starts':
			'\u5E94\u7528\u542F\u52A8\u65F6\u52A0\u8F7D\u6700\u540E\u6253\u5F00\u7684\u521B\u4F5C',
		Login: 'Login',
		'Login & upgrade to PRO': '\u767B\u5F55\u5E76\u5347\u7EA7\u5230 PRO',
		'Login / Signup': '\u767B\u5F55 / \u6CE8\u518C',
		'Login with Github': '\u4F7F\u7528 Github \u767B\u5F55',
		'Login with Google': '\u4F7F\u7528 Google \u767B\u5F55',
		'Login/Signup': '\u767B\u5F55/\u6CE8\u518C',
		'Made with <0>\uD83D\uDC96</0>& <1> \uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Made with <0>\uD83D\uDC96</0>& <1> \uD83D\uDE4C</1> by <2>Kushagra Gour</2>',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'\u7531 <2>Kushagra Gour</2> \u5236\u4F5C\uFF0C\u5E26\u7740 <0>\uD83D\uDC96</0> \u548C <1>\uD83D\uDE4C</1>',
		'Mail me': '\u7ED9\u6211\u53D1\u90AE\u4EF6',
		'Make a monthly pledge on Patreon':
			'\u5728 Patreon \u4E0A\u6BCF\u6708\u652F\u6301',
		'Make the app ready to build some games for <0>Js13kGames</0>.':
			'\u8BA9\u5E94\u7528\u51C6\u5907\u597D\u4E3A <0>Js13kGames</0> \u521B\u5EFA\u4E00\u4E9B\u6E38\u620F\u3002',
		Manage: '\u7BA1\u7406',
		'Manage your PRO subscription': '\u7BA1\u7406\u60A8\u7684 PRO \u8BA2\u9605',
		'Manage your code in files. Just like you would have files on your local machine.':
			'\u5728\u6587\u4EF6\u4E2D\u7BA1\u7406\u60A8\u7684\u4EE3\u7801\u3002\u5C31\u50CF\u60A8\u5728\u672C\u5730\u8BA1\u7B97\u673A\u4E0A\u62E5\u6709\u6587\u4EF6\u4E00\u6837\u3002',
		'Maximize pane': '\u6700\u5927\u5316\u9762\u677F',
		'Maximum time allowed in a loop iteration':
			'\u5FAA\u73AF\u8FED\u4EE3\u4E2D\u5141\u8BB8\u7684\u6700\u5927\u65F6\u95F4',
		'Minimise pane': '\u6700\u5C0F\u5316\u9762\u677F',
		'Most recent first': '\u6700\u65B0\u7684\u5728\u524D',
		'Most upvoted first': '\u6700\u591A\u8D5E\u540C\u7684\u5728\u524D',
		'Multiplayer session active':
			'\u591A\u4EBA\u6E38\u620F\u4F1A\u8BDD\u6D3B\u8DC3',
		'My Library': '\u6211\u7684\u5E93',
		'My Library ({0})': function (a) {
			return ['My Library (', a('0'), ')'];
		},
		New: '\u65B0\u5EFA',
		'No feedback yet. Be the first!':
			'\u8FD8\u6CA1\u6709\u53CD\u9988\u3002\u6210\u4E3A\u7B2C\u4E00\u4E2A\uFF01',
		'No files uploaded yet': '\u5C1A\u672A\u4E0A\u4F20\u6587\u4EF6',
		'No items in this collection.':
			'\u6B64\u96C6\u5408\u4E2D\u6CA1\u6709\u9879\u76EE\u3002',
		'No match found.': '\u672A\u627E\u5230\u5339\u914D\u9879\u3002',
		'Note: You can load external scripts from following domains:':
			'Note: You can load external scripts from following domains:',
		'Note: You can load external scripts only from following domains:':
			'\u6CE8\u610F\uFF1A\u60A8\u53EA\u80FD\u4ECE\u4EE5\u4E0B\u57DF\u52A0\u8F7D\u5916\u90E8\u811A\u672C\uFF1A',
		'Nothing saved here.':
			'\u8FD9\u91CC\u6CA1\u6709\u4FDD\u5B58\u7684\u5185\u5BB9\u3002',
		'Once you stop typing, the preview waits for this much time before getting updated. Too low value might choke your browser!':
			'\u4E00\u65E6\u60A8\u505C\u6B62\u8F93\u5165\uFF0C\u9884\u89C8\u5C06\u5728\u6B64\u65F6\u95F4\u5185\u7B49\u5F85\u66F4\u65B0\u3002\u503C\u8FC7\u4F4E\u53EF\u80FD\u4F1A\u4F7F\u60A8\u7684\u6D4F\u89C8\u5668\u5D29\u6E83\uFF01',
		Open: '\u6253\u5F00',
		'Open Web Maker anytime by clicking the<0><1/></0> button in top-right side of your browser.':
			'\u901A\u8FC7\u70B9\u51FB\u6D4F\u89C8\u5668\u53F3\u4E0A\u89D2\u7684<0><1/></0>\u6309\u94AE\u968F\u65F6\u6253\u5F00Web Maker\u3002',
		'Open Web Maker anytime by visiting <0>https://webmaker.app/create/</0> - Even when you are offline! It just works! \uD83D\uDE31 <1>Drag the following bookmarklet</1> on your bookmark bar to create a quick access shortcut:':
			'\u901A\u8FC7\u8BBF\u95EE<0>https://webmaker.app/create/</0>\u968F\u65F6\u6253\u5F00Web Maker - \u5373\u4F7F\u5728\u79BB\u7EBF\u65F6\u4E5F\u53EF\u4EE5\uFF01\u5B83\u5C31\u662F\u597D\u7528\uFF01\uD83D\uDE31 <1>\u5C06\u4EE5\u4E0B\u4E66\u7B7E\u62D6\u5230\u60A8\u7684\u4E66\u7B7E\u680F</1>\u4EE5\u521B\u5EFA\u5FEB\u901F\u8BBF\u95EE\u5FEB\u6377\u65B9\u5F0F\uFF1A',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'\u6253\u5F00\u5DF2\u4FDD\u5B58\u7684\u521B\u4F5C (Ctrl/\u2318 + O)',
		'Open list of saved creations':
			'\u6253\u5F00\u5DF2\u4FDD\u5B58\u521B\u4F5C\u7684\u5217\u8868',
		'Or, make a one time donation':
			'\u6216\u8005\uFF0C\u8FDB\u884C\u4E00\u6B21\u6027\u6350\u8D60',
		'Other font from system':
			'\u7CFB\u7EDF\u4E2D\u7684\u5176\u4ED6\u5B57\u4F53',
		Participants: '\u53C2\u4E0E\u8005',
		'Powered by cdnjs': '\u7531cdnjs\u63D0\u4F9B\u652F\u6301',
		'Preserve console logs': '\u4FDD\u7559\u63A7\u5236\u53F0\u65E5\u5FD7',
		'Preserve last written code':
			'\u4FDD\u7559\u6700\u540E\u7F16\u5199\u7684\u4EE3\u7801',
		'Preserves the console logs across your preview refreshes':
			'\u5728\u60A8\u7684\u9884\u89C8\u5237\u65B0\u4E4B\u95F4\u4FDD\u7559\u63A7\u5236\u53F0\u65E5\u5FD7',
		'Preview refresh wait time':
			'\u9884\u89C8\u5237\u65B0\u7B49\u5F85\u65F6\u95F4',
		'Preview will refresh when you resize the preview pane':
			'\u5F53\u60A8\u8C03\u6574\u9884\u89C8\u7A97\u683C\u5927\u5C0F\u65F6\uFF0C\u9884\u89C8\u5C06\u5237\u65B0',
		'Put each library in new line':
			'\u5C06\u6BCF\u4E2A\u5E93\u653E\u5728\u65B0\u884C\u4E2D',
		'Read more': '\u9605\u8BFB\u66F4\u591A',
		'Read the documentation.': '\u9605\u8BFB\u6587\u6863\u3002',
		'Realign code': '\u91CD\u65B0\u5BF9\u9F50\u4EE3\u7801',
		'Refresh preview': '\u5237\u65B0\u9884\u89C8',
		'Refresh preview on resize':
			'\u5728\u8C03\u6574\u5927\u5C0F\u65F6\u5237\u65B0\u9884\u89C8',
		"Refreshes the preview as you code. Otherwise use the 'Run' button":
			'\u5728\u60A8\u7F16\u7801\u65F6\u5237\u65B0\u9884\u89C8\u3002\u5426\u5219\u8BF7\u4F7F\u7528\u201C\u8FD0\u884C\u201D\u6309\u94AE',
		'Replace new tab page': '\u66FF\u6362\u65B0\u6807\u7B7E\u9875',
		'Report a bug': '\u62A5\u544A\u4E00\u4E2A\u9519\u8BEF',
		'Review Web Maker': '\u8BC4\u4EF7 Web Maker',
		Run: '\u8FD0\u884C',
		'Run Prettier': '\u8FD0\u884C Prettier',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'\u8FD0\u884C\u9884\u89C8 (Ctrl/\u2318 + Shift + 5)',
		Save: '\u4FDD\u5B58',
		'Save as HTML file': '\u53E6\u5B58\u4E3A HTML \u6587\u4EF6',
		'Save current creation (Ctrl/\u2318 + S)':
			'\u4FDD\u5B58\u5F53\u524D\u521B\u4F5C (Ctrl/\u2318 + S)',
		'Save current creations': '\u4FDD\u5B58\u5F53\u524D\u521B\u4F5C',
		'Search files': '\u641C\u7D22\u6587\u4EF6',
		'Search your creations here...':
			'\u5728\u8FD9\u91CC\u641C\u7D22\u4F60\u7684\u521B\u4F5C...',
		'See Changelog': 'See Changelog',
		'See awesome libraries used':
			'\u67E5\u770B\u4F7F\u7528\u7684\u7CBE\u5F69\u5E93',
		'See changelog': '\u67E5\u770B\u66F4\u65B0\u65E5\u5FD7',
		'See profile or Logout':
			'\u67E5\u770B\u4E2A\u4EBA\u8D44\u6599\u6216\u767B\u51FA',
		'Select next match': '\u9009\u62E9\u4E0B\u4E00\u4E2A\u5339\u914D\u9879',
		'Select previous match': '\u9009\u62E9\u4E0A\u4E00\u4E2A\u5339\u914D\u9879',
		Settings: '\u8BBE\u7F6E',
		Share: '\u5206\u4EAB',
		'Share Link': '\u5206\u4EAB\u94FE\u63A5',
		'Share Web Maker': '\u5206\u4EAB Web Maker',
		'Share this creation publicly':
			'\u516C\u5F00\u5206\u4EAB\u8FD9\u4E2A\u521B\u4F5C',
		'Share this link with others to let them join your session.':
			'\u4E0E\u4ED6\u4EBA\u5206\u4EAB\u6B64\u94FE\u63A5\u4EE5\u8BA9\u4ED6\u4EEC\u52A0\u5165\u4F60\u7684\u4F1A\u8BDD\u3002',
		Signup: 'Signup',
		'Single line comment': '\u5355\u884C\u6CE8\u91CA',
		Spaces: '\u7A7A\u683C',
		'Start Blank': '\u5F00\u59CB\u7A7A\u767D',
		'Start Blank in File Mode':
			'\u4EE5\u6587\u4EF6\u6A21\u5F0F\u5F00\u59CB\u7A7A\u767D',
		'Start New Collab Session':
			'\u5F00\u59CB\u65B0\u7684\u534F\u4F5C\u4F1A\u8BDD',
		"Start a collaborative editing session and invite others to code together in real-time. Everyone can see each other's cursors and edits.":
			'\u5F00\u59CB\u4E00\u4E2A\u534F\u4F5C\u7F16\u8F91\u4F1A\u8BDD\uFF0C\u5E76\u9080\u8BF7\u5176\u4ED6\u4EBA\u5B9E\u65F6\u4E00\u8D77\u7F16\u7801\u3002\u6BCF\u4E2A\u4EBA\u90FD\u53EF\u4EE5\u770B\u5230\u5F7C\u6B64\u7684\u5149\u6807\u548C\u7F16\u8F91\u3002',
		'Start a new creation': '\u5F00\u59CB\u4E00\u4E2A\u65B0\u521B\u4F5C',
		'Start multiplayer collaboration session':
			'\u5F00\u59CB\u591A\u4EBA\u534F\u4F5C\u4F1A\u8BDD',
		Submit: '\u63D0\u4EA4',
		'Submitted on:': '\u63D0\u4EA4\u65F6\u95F4\uFF1A',
		'Submitting...': '\u63D0\u4EA4\u4E2D...',
		'Support the Developer': '\u652F\u6301\u5F00\u53D1\u8005',
		'Support the developer': 'Support the developer',
		'Support the developer by pledging some amount':
			'Support the developer by pledging some amount',
		'Switch to full screen preview': 'Switch to full screen preview',
		'Switch to layout with all vertical panes':
			'\u5207\u6362\u5230\u6240\u6709\u5782\u76F4\u7A97\u683C\u7684\u5E03\u5C40',
		'Switch to layout with preview on bottom':
			'\u5207\u6362\u5230\u5E95\u90E8\u9884\u89C8\u7684\u5E03\u5C40',
		'Switch to layout with preview on left':
			'\u5207\u6362\u5230\u5DE6\u4FA7\u9884\u89C8\u7684\u5E03\u5C40',
		'Switch to layout with preview on left"':
			'Switch to layout with preview on left"',
		'Switch to layout with preview on right':
			'\u5207\u6362\u5230\u53F3\u4FA7\u9884\u89C8\u7684\u5E03\u5C40',
		'Switch to lighter version for better performance. Removes things like blur etc.':
			'\u5207\u6362\u5230\u66F4\u8F7B\u7684\u7248\u672C\u4EE5\u83B7\u5F97\u66F4\u597D\u7684\u6027\u80FD\u3002\u79FB\u9664\u6A21\u7CCA\u7B49\u6548\u679C\u3002',
		Tabs: '\u6807\u7B7E',
		'Take screenshot of preview':
			'\u622A\u53D6\u9884\u89C8\u7684\u5C4F\u5E55\u622A\u56FE',
		Theme: '\u4E3B\u9898',
		'Toggle code pane': '\u5207\u6362\u4EE3\u7801\u7A97\u683C',
		'Toggle console': '\u5207\u6362\u63A7\u5236\u53F0',
		'Toggle full screen preview': '\u5207\u6362\u5168\u5C4F\u9884\u89C8',
		'Toggle wrapping of long sentences onto new line':
			'\u5207\u6362\u957F\u53E5\u5B50\u6362\u884C\u5230\u65B0\u884C',
		'Turning this on will start showing Web Maker in every new tab you open':
			'\u5F00\u542F\u6B64\u529F\u80FD\u5C06\u5728\u60A8\u6253\u5F00\u7684\u6BCF\u4E2A\u65B0\u6807\u7B7E\u4E2D\u663E\u793A Web Maker',
		'Turns on the auto-completion suggestions as you type':
			'\u5728\u60A8\u8F93\u5165\u65F6\u5F00\u542F\u81EA\u52A8\u5B8C\u6210\u5EFA\u8BAE',
		"Tweet about 'Web Maker'": "\u53D1\u63A8\u6587\u5173\u4E8E 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'\u5C06\u60A8\u7684\u529F\u80FD\u8BF7\u6C42\u3001\u8BC4\u8BBA\u548C\u5EFA\u8BAE\u53D1\u63A8\u7ED9 <0>@webmakerApp</0>',
		'Type here to search libraries':
			'\u5728\u8FD9\u91CC\u8F93\u5165\u4EE5\u641C\u7D22\u5E93',
		'Upgrade to PRO': '\u5347\u7EA7\u5230 PRO',
		'Upgrade to PRO and get some advanced superpowers!':
			'\u5347\u7EA7\u5230 PRO \u5E76\u83B7\u5F97\u4E00\u4E9B\u9AD8\u7EA7\u8D85\u80FD\u529B\uFF01',
		'Upload Image': '\u4E0A\u4F20\u56FE\u7247',
		'Upload/Use assets': '\u4E0A\u4F20/\u4F7F\u7528\u8D44\u6E90',
		'Use Monaco Editor': '\u4F7F\u7528 Monaco \u7F16\u8F91\u5668',
		'Use experimental Monaco editor':
			'\u4F7F\u7528\u5B9E\u9A8C\u6027 Monaco \u7F16\u8F91\u5668',
		'Vote for features you want to see or suggest new ones.':
			'\u6295\u7968\u652F\u6301\u60A8\u60F3\u8981\u770B\u5230\u7684\u529F\u80FD\u6216\u5EFA\u8BAE\u65B0\u529F\u80FD\u3002',
		'Welcome to Web Maker': '\u6B22\u8FCE\u6765\u5230 Web Maker',
		'Yes, please import': '\u662F\u7684\uFF0C\u8BF7\u5BFC\u5165',
		'You have <0>{oldSavedCreationsCount}</0> creations saved in your local machine. Do you want to import those creations in your account so they are more secure and accessible anywhere?':
			function (a) {
				return [
					'\u60A8\u5728\u672C\u5730\u8BA1\u7B97\u673A\u4E0A\u4FDD\u5B58\u4E86 <0>',
					a('oldSavedCreationsCount'),
					'</0> \u4E2A\u521B\u4F5C\u3002\u60A8\u60F3\u5C06\u8FD9\u4E9B\u521B\u4F5C\u5BFC\u5165\u5230\u60A8\u7684\u5E10\u6237\u4E2D\uFF0C\u4EE5\u4FBF\u5B83\u4EEC\u66F4\u5B89\u5168\u5E76\u4E14\u53EF\u4EE5\u968F\u65F6\u8BBF\u95EE\u5417\uFF1F'
				];
			}
	}
};
