/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			if (ord) return 'other';
			return n == 1 ? 'one' : 'other';
		}
	},
	messages: {
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'"Oops! El archivo seleccionado est\xE1 da\xF1ado. Seleccione un archivo que se gener\xF3 haciendo clic en el bot\xF3n "Exportar".',
		'Add Library': 'A\xF1adir librer\xEDa',
		'Add a JS/CSS library': 'A\xF1adir una librer\xEDa JS/CSS',
		'Add library': 'A\xF1adir librer\xEDa',
		Assets: 'Assets',
		Chat: 'Chat',
		'Choose from popular libraries': 'Elija entre las librer\xEDas populares',
		'Clear console (CTRL + L)': 'Borrar consola (CTRL + L)',
		'Clear console (works when console input is focused)':
			'Borrar consola (funciona cuando la entrada de la consola est\xE1 enfocada)',
		'Close saved creations pane': 'Cerrar el panel creaciones guardadas',
		'Close saved creations panel & modals':
			'Cerrar el panel de creaciones guardadas y modales',
		Console: 'Consola',
		'Detach preview': 'Separar la vista previa',
		Discuss: 'Discuss',
		Donate: 'Donar',
		'Double click to toggle console':
			'Haga doble clic para alternar la consola',
		'Download game as zip': 'Descargar juego como zip',
		'Edit on CodePen': 'Editar en CodePen',
		Editor: 'Editor',
		'Emmet code completion': 'Finalizaci\xF3n del c\xF3digo Emmet',
		Export: 'Exportar',
		'Export all your creations into a single importable file.':
			'Exporta todas tus creaciones en un \xFAnico archivo importable.',
		Find: 'Buscar',
		'Find & replace': 'Buscar y reemplazar',
		Fork: 'Fork',
		'Fork this creation': 'Fork this creation',
		Get: 'Get',
		Global: 'Global',
		Help: 'Ayuda',
		Import: 'Importar',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			'Importa tus creaciones. S\xF3lo se puede importar el archivo que se exporta a trav\xE9s del bot\xF3n "Exportar".',
		'Indent code left': 'Indentar c\xF3digo a la izquierda',
		'Indent code right': 'Indentar c\xF3digo a la derecha',
		'Keyboard Shortcuts': 'Atajos de Teclado',
		'Keyboard shortcuts': 'Atajos de teclado',
		License: 'Licencia',
		'Like this app? Please <0>rate it here</0>.':
			'Like this app? Please <0>rate it here</0>.',
		'Login/Signup': 'Iniciar sesi\xF3n/Registrarse',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>',
		'Mail me': 'Mail me',
		Manage: 'Manage',
		'Manage your PRO subscription': 'Manage your PRO subscription',
		'My Library': 'My Library',
		'My Library ({0})': 'Mi biblioteca',
		New: 'Nuevo',
		'No match found.': 'No se encontr\xF3 ninguna coincidencia.',
		'Note: You can load external scripts only from following domains:':
			'Nota: Puedes cargar scripts externos s\xF3lo de los siguientes dominios:',
		'Nothing saved here.': 'Aqu\xED no hay nada guardado.',
		Open: 'Abrir',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'Abrir una creaci\xF3n guardada (Ctrl/\u2318 + O)',
		'Open list of saved creations': 'Abrir lista de creaciones guardadas',
		'Powered by cdnjs': 'Impulsado por cdnjs',
		'Put each library in new line':
			'Poner cada biblioteca en una nueva l\xEDnea',
		'Read more': 'Leer m\xE1s',
		'Read the documentation.': 'Leer la documentaci\xF3n.',
		'Realign code': 'Reajustar el c\xF3digo',
		'Refresh preview': 'Actualizar la vista previa',
		'Report a bug': 'Reporta un error',
		'Review Web Maker': 'Rese\xF1a de Web Maker',
		Run: 'Ejecutar',
		'Run Prettier': 'Ejecutar Prettier',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'Ejecutar vista previa (Ctrl/\u2318 + Shift + 5)',
		Save: 'Guardar',
		'Save as HTML file': 'Guardar como archivo HTML',
		'Save current creation (Ctrl/\u2318 + S)':
			'Guardar la creaci\xF3n actual (Ctrl/\u2318 + S)',
		'Save current creations': 'Guardar las creaciones actuales',
		'Search your creations here...': 'Busca tus creaciones aqu\xED...',
		'See awesome libraries used':
			'Vea las incre\xEDbles librer\xEDas utilizadas',
		'See changelog': 'Ver registro de cambios',
		'See profile or Logout': 'Ver perfil o cerrar sesi\xF3n',
		'Select next match': 'Seleccione el siguiente partido',
		'Select previous match': 'Seleccione el partido anterior',
		Settings: 'Ajustes',
		Share: 'Share',
		'Share Web Maker': 'Share Web Maker',
		'Share this creation publicly': 'Share this creation publicly',
		'Single line comment': 'Comentario de una sola l\xEDnea',
		'Start a new creation': 'Iniciar una nueva creaci\xF3n',
		'Support the developer': 'Apoyar al desarrollador',
		'Support the developer by pledging some amount':
			'Apoyar al desarrollador donando alguna cantidad',
		'Switch to full screen preview':
			'Cambiar a vista previa de pantalla completa',
		'Switch to layout with all vertical panes':
			'Cambiar a la disposici\xF3n con todos los paneles verticales',
		'Switch to layout with preview on bottom':
			'Cambiar al dise\xF1o con vista previa en la parte inferior',
		'Switch to layout with preview on left':
			'Cambiar al dise\xF1o con vista previa a la izquierda',
		'Switch to layout with preview on right':
			'Cambiar al dise\xF1o con vista previa a la derecha',
		'Take screenshot of preview':
			'Tomar captura de pantalla de la vista previa',
		'Toggle console': 'Alternar consola',
		'Toggle full screen preview': 'Toggle full screen preview',
		"Tweet about 'Web Maker'": "Tuitea sobre 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>',
		'Type here to search libraries':
			'Escriba aqu\xED para buscar en las librer\xEDas',
		'Upgrade to PRO and get some advanced superpowers!':
			'Upgrade to PRO and get some advanced superpowers!',
		'Upload Image': 'Cargar imagen',
		'Upload/Use assets': 'Upload/Use assets'
	}
};
