/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			if (ord) return 'other';
			return n == 1 ? 'one' : 'other';
		}
	},
	messages: {
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" es <0>c\xF3digo abierto</0> bajo la <1>Licencia MIT</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'"Oops! El archivo seleccionado est\xE1 da\xF1ado. Seleccione un archivo que se gener\xF3 haciendo clic en el bot\xF3n "Exportar".',
		'(Experimental) Switches from CodeMirror to Monaco. Many other settings might not be available in Monaco.':
			'(Experimental) Cambia de CodeMirror a Monaco. Muchas otras configuraciones pueden no estar disponibles en Monaco.',
		'2 files mode creations available in Free plan. To create unlimited files mode creations, upgrade to <0/>.':
			'2 creaciones en modo de archivos disponibles en el plan gratuito. Para crear creaciones en modo de archivos ilimitadas, actualiza a <0/>.',
		'3 separate panes to write HTML, CSS and JavaScript. Good for quickly testing something.':
			'3 paneles separados para escribir HTML, CSS y JavaScript. Bueno para probar algo r\xE1pidamente.',
		'A blazing-fast, offline code editor for the web. Three things to know before you start.':
			'Un editor de c\xF3digo ultrarr\xE1pido y offline para la web. Tres cosas que debes saber antes de empezar.',
		'Add Library': 'A\xF1adir librer\xEDa',
		'Add a JS/CSS library': 'A\xF1adir una librer\xEDa JS/CSS',
		'Add collection': 'Agregar colecci\xF3n',
		"Add files locally, usable only on this browser. Won't work for others if you share this publicly.":
			'Agregar archivos localmente, utilizables solo en este navegador. No funcionar\xE1 para otros si lo compartes p\xFAblicamente.',
		'Add library': 'A\xF1adir librer\xEDa',
		'Add the closing tag automatically on seeing an opening tag in HTML':
			'Agregar la etiqueta de cierre autom\xE1ticamente al ver una etiqueta de apertura en HTML',
		Advanced: 'Avanzado',
		All: 'Todo',
		Assets: 'Recursos',
		'Assets feature is available in PRO plan.':
			'La funci\xF3n de recursos est\xE1 disponible en el plan PRO.',
		'Atomic CSS configuration': 'Configuraci\xF3n de Atomic CSS',
		'Auto-close tags': 'Cerrar etiquetas autom\xE1ticamente',
		'Auto-complete suggestions': 'Sugerencias de autocompletar',
		'Auto-preview': 'Auto-previsualizaci\xF3n',
		'Auto-save': 'Guardado autom\xE1tico',
		'Auto-save keeps saving your code at regular intervals after you hit save manually the first time':
			'El guardado autom\xE1tico sigue guardando tu c\xF3digo a intervalos regulares despu\xE9s de que lo guardes manualmente la primera vez',
		Chat: 'Chat',
		'Choose from popular libraries': 'Elija entre las librer\xEDas populares',
		'Clear console (CTRL + L)': 'Borrar consola (CTRL + L)',
		'Clear console (works when console input is focused)':
			'Borrar consola (funciona cuando la entrada de la consola est\xE1 enfocada)',
		'Click the Web Maker icon in the top-right of your browser any time you want to start tinkering.':
			'Haz clic en el icono de Web Maker en la esquina superior derecha de tu navegador cada vez que quieras empezar a experimentar.',
		'Click to change': 'Haz clic para cambiar',
		'Click to edit': 'Haz clic para editar',
		'Close saved creations pane': 'Cerrar el panel creaciones guardadas',
		'Close saved creations panel & modals':
			'Cerrar el panel de creaciones guardadas y modales',
		Cloud: 'Nube',
		'Code blast!': '\xA1Explosi\xF3n de c\xF3digo!',
		Collab: 'Colaborar',
		'Collab Session': 'Sesi\xF3n de colaboraci\xF3n',
		'Collaboration unavailable offline':
			'Colaboraci\xF3n no disponible sin conexi\xF3n',
		'Collection name': 'Nombre de la colecci\xF3n',
		'Coming from the Chrome extension? <0>Learn how to import your creations</0>.':
			'\xBFVienes de la extensi\xF3n de Chrome? <0>Aprende c\xF3mo importar tus creaciones</0>.',
		'Configure and customize settings by clicking the gear icon (<0><1/></0>) in bottom right of the app.':
			'Configura y personaliza la configuraci\xF3n haciendo clic en el \xEDcono de engranaje (<0><1/></0>) en la esquina inferior derecha de la aplicaci\xF3n.',
		Console: 'Consola',
		'Contact the Developer': 'Contacta al desarrollador',
		'Copy URL (or keep clicking to copy other formats)':
			'Copiar URL (o sigue haciendo clic para copiar otros formatos)',
		'Copy link': 'Copiar enlace',
		'Create New': 'Crear nuevo',
		'Custom font name here': 'Nombre de fuente personalizada aqu\xED',
		'Customize editor, theme, key bindings and more from the settings gear in the bottom-right corner.':
			'Personaliza el editor, el tema, los atajos de teclado y m\xE1s desde el engranaje de configuraci\xF3n en la esquina inferior derecha.',
		'Default CSS preprocessor': 'Preprocesador CSS predeterminado',
		'Default HTML preprocessor': 'Preprocesador HTML predeterminado',
		'Default JavaScript preprocessor':
			'Preprocesador JavaScript predeterminado',
		'Default Preprocessors': 'Preprocesadores predeterminados',
		Delete: 'Eliminar',
		'Detach preview': 'Separar la vista previa',
		Discuss: 'Discutir',
		"Don't ask me again": 'No me preguntes de nuevo',
		Donate: 'Donar',
		'Double click to toggle code pane':
			'Haz doble clic para alternar el panel de c\xF3digo',
		'Double click to toggle console':
			'Haga doble clic para alternar la consola',
		'Download game as zip': 'Descargar juego como zip',
		'Drop files or click here to add':
			'Suelta archivos o haz clic aqu\xED para agregar',
		'Drop files or click here to upload':
			'Suelta archivos o haz clic aqu\xED para subir',
		'Edit on CodePen': 'Editar en CodePen',
		Editor: 'Editor',
		'Emmet code completion': 'Finalizaci\xF3n del c\xF3digo Emmet',
		'Enjoy wonderful particle blasts while you type':
			'Disfruta de maravillosas explosiones de part\xEDculas mientras escribes',
		Export: 'Exportar',
		'Export all your creations into a single importable file.':
			'Exporta todas tus creaciones en un \xFAnico archivo importable.',
		'Fast/light-weight version': 'Versi\xF3n r\xE1pida/ligera',
		'Feedback & Suggestions': 'Comentarios y Sugerencias',
		'Fetching files...': 'Cargando archivos...',
		'File should be max 300KB in size':
			'El archivo debe tener un tama\xF1o m\xE1ximo de 300KB',
		'Files modes is currently only available in Web app. <0>Try the Web app now</0>.':
			'Los modos de archivos actualmente solo est\xE1n disponibles en la aplicaci\xF3n web. <0>Prueba la aplicaci\xF3n web ahora</0>.',
		Find: 'Buscar',
		'Find & replace': 'Buscar y reemplazar',
		'Focus CSS pane': 'Enfocar panel de CSS',
		'Focus HTML pane': 'Enfocar panel de HTML',
		'Focus JS pane': 'Enfocar panel de JS',
		'Focus preview': 'Enfocar vista previa',
		'Follow <0>@webmakerApp</0> for new features and release notes.':
			'Sigue a <0>@webmakerApp</0> para nuevas funciones y notas de lanzamiento.',
		'Follow <0>@webmakerApp</0> to know about the new upcoming features!':
			'\xA1Sigue a <0>@webmakerApp</0> para conocer las nuevas funciones que se avecinan!',
		Font: 'Fuente',
		'Font Size': 'Tama\xF1o de fuente',
		Fork: 'Hacer un fork',
		'Fork this creation': 'Hacer un fork de esta creaci\xF3n',
		'Format Code': 'Formatear c\xF3digo',
		'Format code': 'Formatear c\xF3digo',
		'Free plan includes 2 Files mode creations. Upgrade to <0/> for unlimited Files mode, cloud assets & more':
			'El plan gratuito incluye 2 creaciones en modo Archivos. Actualiza a <0/> para tener modo Archivos ilimitado, activos en la nube y m\xE1s',
		Fun: 'Diversi\xF3n',
		General: 'General',
		Get: 'Obtener',
		Global: 'Global',
		'Grid view': 'Vista de cuadr\xEDcula',
		Help: 'Ayuda',
		'Hi, <0>Kushagra</0> here! Web Maker is a free and open-source project. To keep myself motivated for working on such open-source and free <1>side projects</1>, I am accepting donations. Your pledge, no matter how small, will act as an appreciation towards my work and keep me going forward making Web Maker more awesome\uD83D\uDD25. So please consider donating. \uD83D\uDE4F\uD83C\uDFFC (could be as small as $1/month).':
			'\xA1Hola, <0>Kushagra</0> aqu\xED! Web Maker es un proyecto gratuito y de c\xF3digo abierto. Para mantenerme motivado para trabajar en proyectos <1>laterales</1> de c\xF3digo abierto y gratuitos, estoy aceptando donaciones. Tu contribuci\xF3n, sin importar cu\xE1n peque\xF1a sea, actuar\xE1 como un agradecimiento hacia mi trabajo y me mantendr\xE1 avanzando para hacer que Web Maker sea m\xE1s incre\xEDble\uD83D\uDD25. As\xED que por favor considera donar. \uD83D\uDE4F\uD83C\uDFFC (podr\xEDa ser tan peque\xF1o como $1/mes).',
		'Hover/Focus to preview': 'Pasa el cursor/enfoca para previsualizar',
		'I wish Web Maker could...': 'Desear\xEDa que Web Maker pudiera...',
		'If any loop iteration takes more than the defined time, it is detected as a potential infinite loop and further iterations are stopped.':
			'Si alguna iteraci\xF3n de bucle toma m\xE1s tiempo del definido, se detecta como un posible bucle infinito y se detienen las iteraciones posteriores.',
		'If you are an existing Chrome extension user, you can import your creations from there to here. <0>Learn how to export/import</0>.':
			'Si eres un usuario existente de la extensi\xF3n de Chrome, puedes importar tus creaciones de all\xED a aqu\xED. <0>Aprende c\xF3mo exportar/importar</0>.',
		Import: 'Importar',
		'Import your creations in your account':
			'Importa tus creaciones en tu cuenta',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			'Importa tus creaciones. S\xF3lo se puede importar el archivo que se exporta a trav\xE9s del bot\xF3n "Exportar".',
		'Indent code left': 'Indentar c\xF3digo a la izquierda',
		'Indent code right': 'Indentar c\xF3digo a la derecha',
		Indentation: 'Sangrado',
		'Indentation Size': 'Tama\xF1o de sangrado',
		"It's okay if you don't want to. You can simply logout and access them anytime on this browser.":
			'Est\xE1 bien si no quieres. Simplemente puedes cerrar sesi\xF3n y acceder a ellos en cualquier momento en este navegador.',
		'Join a community of 70,000+ Developers':
			'\xDAnete a una comunidad de m\xE1s de 70,000 desarrolladores',
		'Js13kGames Mode': 'Modo Js13kGames',
		'Key bindings': 'Atajos de teclado',
		'Keyboard Shortcuts': 'Atajos de Teclado',
		'Keyboard shortcuts': 'Atajos de teclado',
		Language: 'Idioma',
		'Leave Session': 'Salir de la sesi\xF3n',
		'Leave a Review': 'Deja una rese\xF1a',
		"Let's start": 'Empecemos',
		'Lets start!': '\xA1Empecemos!',
		License: 'Licencia',
		'Like this app? Please <0>rate it here</0>.':
			'\xBFTe gusta esta aplicaci\xF3n? Por favor <0>calif\xEDcalo aqu\xED</0>.',
		'Line wrap': 'Ajuste de l\xEDnea',
		'List view': 'Vista de lista',
		'Loads the last open creation when app starts':
			'Carga la \xFAltima creaci\xF3n abierta cuando la aplicaci\xF3n se inicia',
		Local: 'Local',
		'Login & upgrade to PRO': 'Iniciar sesi\xF3n y actualizar a PRO',
		'Login / Signup': 'Iniciar sesi\xF3n / Registrarse',
		'Login with Github': 'Iniciar sesi\xF3n con Github',
		'Login with Google': 'Iniciar sesi\xF3n con Google',
		'Login/Signup': 'Iniciar sesi\xF3n/Registrarse',
		'Made with <0>\u2764\uFE0F</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Hecho con <0>\u2764\uFE0F</0>& <1>\uD83D\uDE4C</1> por <2>Kushagra Gour</2>',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Hecho con <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> por <2>Kushagra Gour</2>',
		'Mail me': 'Env\xEDame un correo',
		'Make a monthly pledge on Patreon': 'Haz una promesa mensual en Patreon',
		'Make it yours': 'Hazlo tuyo',
		'Make the app ready to build some games for <0>Js13kGames</0>.':
			'Prepara la aplicaci\xF3n para construir algunos juegos para <0>Js13kGames</0>.',
		Manage: 'Administrar',
		'Manage your PRO subscription': 'Gestiona tu suscripci\xF3n PRO',
		'Manage your code in files. Just like you would have files on your local machine.':
			'Administra tu c\xF3digo en archivos. Tal como tendr\xEDas archivos en tu m\xE1quina local.',
		'Max 300KB per file': 'M\xE1x 300KB por archivo',
		'Max 5MB per file': 'M\xE1x 5MB por archivo',
		'Maximize pane': 'Maximizar panel',
		'Maximum time allowed in a loop iteration':
			'Tiempo m\xE1ximo permitido en una iteraci\xF3n de bucle',
		'Minimise pane': 'Minimizar panel',
		'Most recent first': 'M\xE1s reciente primero',
		'Most upvoted first': 'M\xE1s votados primero',
		'Multiplayer session active': 'Sesi\xF3n multijugador activa',
		'My Library': 'Mi Biblioteca',
		'My Library ({0})': 'Mi biblioteca',
		New: 'Nuevo',
		'No feedback yet. Be the first!':
			'\xA1No hay comentarios a\xFAn. S\xE9 el primero!',
		'No files uploaded yet': 'No se han subido archivos a\xFAn',
		'No items in this collection.': 'No hay elementos en esta colecci\xF3n.',
		'No match found.': 'No se encontr\xF3 ninguna coincidencia.',
		'Note: You can load external scripts only from following domains:':
			'Nota: Puedes cargar scripts externos s\xF3lo de los siguientes dominios:',
		'Nothing saved here.': 'Aqu\xED no hay nada guardado.',
		'Once you stop typing, the preview waits for this much time before getting updated. Too low value might choke your browser!':
			'Una vez que dejes de escribir, la vista previa espera este tiempo antes de actualizarse. \xA1Un valor demasiado bajo podr\xEDa ahogar tu navegador!',
		Open: 'Abrir',
		'Open Web Maker anytime by clicking the<0><1/></0> button in top-right side of your browser.':
			'Abre Web Maker en cualquier momento haciendo clic en el bot\xF3n<0><1/></0> en la esquina superior derecha de tu navegador.',
		'Open Web Maker anytime by visiting <0>https://webmaker.app/create/</0> - Even when you are offline! It just works! \uD83D\uDE31 <1>Drag the following bookmarklet</1> on your bookmark bar to create a quick access shortcut:':
			'Abre Web Maker en cualquier momento visitando <0>https://webmaker.app/create/</0> - \xA1Incluso cuando est\xE9s desconectado! \xA1Simplemente funciona! \uD83D\uDE31 <1>Arrastra el siguiente bookmarklet</1> a tu barra de marcadores para crear un acceso r\xE1pido:',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'Abrir una creaci\xF3n guardada (Ctrl/\u2318 + O)',
		'Open anywhere, even offline': 'Abre en cualquier lugar, incluso offline',
		'Open from your toolbar': 'Abre desde tu barra de herramientas',
		'Open list of saved creations': 'Abrir lista de creaciones guardadas',
		'Or, make a one time donation': 'O, haz una donaci\xF3n \xFAnica',
		'Other font from system': 'Otra fuente del sistema',
		'PRO unlocks unlimited public creations, unlimited Files mode projects, cloud asset hosting and real-time multiplayer collab.':
			'PRO desbloquea creaciones p\xFAblicas ilimitadas, proyectos en modo Archivos ilimitados, alojamiento de activos en la nube y colaboraci\xF3n multijugador en tiempo real.',
		Participants: 'Participantes',
		'Powered by cdnjs': 'Impulsado por cdnjs',
		'Preserve console logs': 'Conservar registros de la consola',
		'Preserve last written code': 'Conservar el \xFAltimo c\xF3digo escrito',
		'Preserves the console logs across your preview refreshes':
			'Conserva los registros de la consola a trav\xE9s de tus actualizaciones de vista previa',
		'Preview refresh wait time':
			'Tiempo de espera para la actualizaci\xF3n de la vista previa',
		'Preview will refresh when you resize the preview pane':
			'La vista previa se actualizar\xE1 cuando cambies el tama\xF1o del panel de vista previa',
		'Put each library in new line':
			'Poner cada biblioteca en una nueva l\xEDnea',
		'Read more': 'Leer m\xE1s',
		'Read the documentation': 'Lee la documentaci\xF3n',
		'Read the documentation.': 'Leer la documentaci\xF3n.',
		'Realign code': 'Reajustar el c\xF3digo',
		'Refresh preview': 'Actualizar la vista previa',
		'Refresh preview on resize':
			'Actualizar vista previa al cambiar de tama\xF1o',
		"Refreshes the preview as you code. Otherwise use the 'Run' button":
			"Actualiza la vista previa mientras codificas. De lo contrario, usa el bot\xF3n 'Ejecutar'",
		'Replace new tab page': 'Reemplazar la p\xE1gina de nueva pesta\xF1a',
		'Report a Bug': 'Reportar un error',
		'Report a bug': 'Reporta un error',
		'Review Web Maker': 'Rese\xF1a de Web Maker',
		Run: 'Ejecutar',
		'Run Prettier': 'Ejecutar Prettier',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'Ejecutar vista previa (Ctrl/\u2318 + Shift + 5)',
		Save: 'Guardar',
		'Save as HTML file': 'Guardar como archivo HTML',
		'Save current creation (Ctrl/\u2318 + S)':
			'Guardar la creaci\xF3n actual (Ctrl/\u2318 + S)',
		'Save current creations': 'Guardar las creaciones actuales',
		'Search files': 'Buscar archivos',
		'Search your creations here...': 'Busca tus creaciones aqu\xED...',
		'See PRO': 'Ver PRO',
		'See awesome libraries used':
			'Vea las incre\xEDbles librer\xEDas utilizadas',
		'See changelog': 'Ver registro de cambios',
		'See profile or Logout': 'Ver perfil o cerrar sesi\xF3n',
		'Select next match': 'Seleccione el siguiente partido',
		'Select previous match': 'Seleccione el partido anterior',
		Settings: 'Ajustes',
		Share: 'Compartir',
		'Share Link': 'Compartir enlace',
		'Share Web Maker': 'Compartir Web Maker',
		'Share this creation publicly':
			'Compartir esta creaci\xF3n p\xFAblicamente',
		'Share this link with others to let them join your session.':
			'Comparte este enlace con otros para permitirles unirse a tu sesi\xF3n.',
		'Single line comment': 'Comentario de una sola l\xEDnea',
		Spaces: 'Espacios',
		'Start Blank': 'Comenzar en blanco',
		'Start Blank in File Mode': 'Comenzar en blanco en modo archivo',
		'Start New Collab Session': 'Iniciar nueva sesi\xF3n de colaboraci\xF3n',
		"Start a collaborative editing session and invite others to code together in real-time. Everyone can see each other's cursors and edits.":
			'Inicia una sesi\xF3n de edici\xF3n colaborativa e invita a otros a codificar juntos en tiempo real. Todos pueden ver los cursores y ediciones de los dem\xE1s.',
		'Start a new creation': 'Iniciar una nueva creaci\xF3n',
		'Start multiplayer collaboration session':
			'Iniciar sesi\xF3n de colaboraci\xF3n multijugador',
		'Stay in the loop': 'Mantente al tanto',
		Submit: 'Enviar',
		'Submitted on:': 'Enviado el:',
		'Submitting...': 'Enviando...',
		'Support the Developer': 'Apoya al desarrollador',
		'Support the developer': 'Apoyar al desarrollador',
		'Support the developer by pledging some amount':
			'Apoyar al desarrollador donando alguna cantidad',
		'Switch to full screen preview':
			'Cambiar a vista previa de pantalla completa',
		'Switch to layout with all vertical panes':
			'Cambiar a la disposici\xF3n con todos los paneles verticales',
		'Switch to layout with preview on bottom':
			'Cambiar al dise\xF1o con vista previa en la parte inferior',
		'Switch to layout with preview on left':
			'Cambiar al dise\xF1o con vista previa a la izquierda',
		'Switch to layout with preview on right':
			'Cambiar al dise\xF1o con vista previa a la derecha',
		'Switch to lighter version for better performance. Removes things like blur etc.':
			'Cambia a una versi\xF3n m\xE1s ligera para un mejor rendimiento. Elimina cosas como el desenfoque, etc.',
		'Switch to tabbed layout': 'Cambiar a dise\xF1o de pesta\xF1as',
		Tabs: 'Pesta\xF1as',
		'Take screenshot of preview':
			'Tomar captura de pantalla de la vista previa',
		Theme: 'Tema',
		'Toggle code pane': 'Alternar panel de c\xF3digo',
		'Toggle console': 'Alternar consola',
		'Toggle full screen preview': 'Alternar vista previa en pantalla completa',
		'Toggle wrapping of long sentences onto new line':
			'Alternar el ajuste de oraciones largas en una nueva l\xEDnea',
		'Turning this on will start showing Web Maker in every new tab you open':
			'Activar esto comenzar\xE1 a mostrar Web Maker en cada nueva pesta\xF1a que abras',
		'Turns on the auto-completion suggestions as you type':
			'Activa las sugerencias de autocompletado mientras escribes',
		"Tweet about 'Web Maker'": "Tuitea sobre 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'Env\xEDa tus solicitudes de funciones, comentarios y sugerencias a <0>@webmakerApp</0>',
		'Type here to search libraries':
			'Escriba aqu\xED para buscar en las librer\xEDas',
		'Upgrade to PRO': 'Actualiza a PRO',
		'Upgrade to PRO and get some advanced superpowers!':
			'\xA1Actualiza a PRO y obt\xE9n algunos superpoderes avanzados!',
		'Upload Image': 'Cargar imagen',
		'Upload assets to the cloud for use across devices.':
			'Sube activos a la nube para usarlos en varios dispositivos.',
		'Upload/Use assets': 'Subir/Usar activos',
		'Use Monaco Editor': 'Usar Monaco Editor',
		'Use experimental Monaco editor': 'Usar editor Monaco experimental',
		'Visit <0>https://webmaker.app/create/</0> any time \u2014 it works offline. Drag the bookmarklet onto your bookmark bar for one-click access:':
			'Visita <0>https://webmaker.app/create/</0> en cualquier momento \u2014 funciona offline. Arrastra el marcador a tu barra de marcadores para acceso con un clic:',
		'Vote for features you want to see or suggest new ones.':
			'Vota por las funciones que quieres ver o sugiere nuevas.',
		'Want more super-powers?': '\xBFQuieres m\xE1s superpoderes?',
		'Welcome to Web Maker': 'Bienvenido a Web Maker',
		'Yes, please import': 'S\xED, por favor importa',
		'You have <0>{oldSavedCreationsCount}</0> creations saved in your local machine. Do you want to import those creations in your account so they are more secure and accessible anywhere?':
			function (a) {
				return [
					'Tienes <0>',
					a('oldSavedCreationsCount'),
					'</0> creaciones guardadas en tu m\xE1quina local. \xBFQuieres importar esas creaciones a tu cuenta para que sean m\xE1s seguras y accesibles desde cualquier lugar?'
				];
			}
	}
};
