/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			var s = String(n).split('.'),
				v0 = !s[1];
			if (ord) return 'other';
			return n == 1 && v0 ? 'one' : 'other';
		}
	},
	messages: {
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" is <0>open-source</0> onder de <1>MIT Licentie</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'\'Oeps! Geselecteerd bestand is beschadigd. Kies een bestand dat is gegenereerd door op de "Export"-knop te klikken.',
		'(Experimental) Switches from CodeMirror to Monaco. Many other settings might not be available in Monaco.':
			'(Experimenteel) Schakelt over van CodeMirror naar Monaco. Veel andere instellingen zijn mogelijk niet beschikbaar in Monaco.',
		'2 files mode creations available in Free plan. To create unlimited files mode creations, upgrade to <0/>.':
			'2 bestanden modus creaties beschikbaar in het Gratis plan. Om onbeperkte bestanden modus creaties te maken, upgrade naar <0/>.',
		'3 separate panes to write HTML, CSS and JavaScript. Good for quickly testing something.':
			'3 aparte panelen om HTML, CSS en JavaScript te schrijven. Goed voor het snel testen van iets.',
		'A blazing-fast, offline code editor for the web. Three things to know before you start.':
			'Een razendsnelle, offline code-editor voor het web. Drie dingen om te weten voordat je begint.',
		'Add Library': 'Bibliotheek toevoegen',
		'Add a JS/CSS library': 'Voeg een JS/CSS-bibliotheek toe',
		'Add collection': 'Verzameling toevoegen',
		"Add files locally, usable only on this browser. Won't work for others if you share this publicly.":
			'Voeg bestanden lokaal toe, alleen bruikbaar op deze browser. Werkt niet voor anderen als je dit openbaar deelt.',
		'Add library': 'Bibliotheek toevoegen',
		'Add the closing tag automatically on seeing an opening tag in HTML':
			'Voeg automatisch de sluit-tag toe bij het zien van een openingstag in HTML',
		Advanced: 'Geavanceerd',
		All: 'Alle',
		Assets: 'Middelen',
		'Assets feature is available in PRO plan.':
			'De middelenfunctie is beschikbaar in het PRO-plan.',
		'Atomic CSS configuration': 'Atomic CSS-configuratie',
		'Auto-close tags': 'Automatisch sluiten van tags',
		'Auto-complete suggestions': 'Automatische aanvulsuggesties',
		'Auto-preview': 'Auto-preview',
		'Auto-save': 'Automatisch opslaan',
		'Auto-save keeps saving your code at regular intervals after you hit save manually the first time':
			'Automatisch opslaan blijft je code op regelmatige intervallen opslaan nadat je de eerste keer handmatig op opslaan hebt gedrukt',
		'Choose from popular libraries': 'Kies uit populaire bibliotheken',
		'Clear console (CTRL + L)': 'Console wissen (CTRL + L)',
		'Clear console (works when console input is focused)':
			'Console wissen (werkt wanneer console-invoer is gefocust)',
		'Click the Web Maker icon in the top-right of your browser any time you want to start tinkering.':
			'Klik op het Web Maker-pictogram in de rechterbovenhoek van je browser wanneer je wilt beginnen met experimenteren.',
		'Click to change': 'Klik om te wijzigen',
		'Click to edit': 'Klik om te bewerken',
		'Close saved creations pane': 'Sluit het paneel met opgeslagen creaties',
		'Close saved creations panel & modals':
			'Sluit het paneel met opgeslagen creaties en modals',
		Cloud: 'Cloud',
		'Code blast!': 'Code explosie!',
		Collab: 'Samenwerken',
		'Collab Session': 'Samenwerkingssessie',
		'Collaboration unavailable offline':
			'Samenwerking offline niet beschikbaar',
		'Collection name': 'Collectienaam',
		'Coming from the Chrome extension? <0>Learn how to import your creations</0>.':
			'Kom je van de Chrome-extensie? <0>Leer hoe je je creaties kunt importeren</0>.',
		'Configure and customize settings by clicking the gear icon (<0><1/></0>) in bottom right of the app.':
			'Configureer en pas instellingen aan door op het tandwielpictogram (<0><1/></0>) rechtsonder in de app te klikken.',
		Console: 'Console',
		'Contact the Developer': 'Neem contact op met de ontwikkelaar',
		'Copy URL (or keep clicking to copy other formats)':
			'Kopieer URL (of blijf klikken om andere formaten te kopi\xEBren)',
		'Copy link': 'Kopieer link',
		'Create New': 'Nieuwe maken',
		'Custom font name here': 'Aangepaste lettertype naam hier',
		'Customize editor, theme, key bindings and more from the settings gear in the bottom-right corner.':
			'Pas de editor, het thema, de sneltoetsen en meer aan via het instellingenwiel in de rechterbenedenhoek.',
		'Default CSS preprocessor': 'Standaard CSS-preprocessor',
		'Default HTML preprocessor': 'Standaard HTML-preprocessor',
		'Default JavaScript preprocessor': 'Standaard JavaScript-preprocessor',
		'Default Preprocessors': 'Standaard preprocessors',
		Delete: 'Verwijderen',
		'Detach preview': 'Ontkoppel voorbeeld',
		Discuss: 'Bespreken',
		"Don't ask me again": 'Vraag het me niet opnieuw',
		'Double click to toggle code pane':
			'Dubbelklik om het codepaneel te schakelen',
		'Double click to toggle console': 'Dubbelklik om de console te schakelen',
		'Download game as zip': 'Download spel als zip',
		'Drop files or click here to add':
			'Sleep bestanden hierheen of klik hier om toe te voegen',
		'Drop files or click here to upload':
			'Sleep bestanden of klik hier om te uploaden',
		'Edit on CodePen': 'Bewerken op CodePen',
		Editor: 'Editor',
		'Emmet code completion': 'Emmet code voltooiing',
		'Enjoy wonderful particle blasts while you type':
			'Geniet van prachtige deeltjesexplosies terwijl je typt',
		Export: 'Exporteren',
		'Export all your creations into a single importable file.':
			'Exporteer al je creaties naar een enkel importeerbaar bestand.',
		'Fast/light-weight version': 'Snelle/lichtgewicht versie',
		'Feedback & Suggestions': 'Feedback & Suggesties',
		'Fetching files...': 'Bestanden ophalen...',
		'File should be max 300KB in size': 'Bestand mag maximaal 300KB groot zijn',
		'Files modes is currently only available in Web app. <0>Try the Web app now</0>.':
			'Bestandmodi zijn momenteel alleen beschikbaar in de webapp. <0>Probeer de webapp nu</0>.',
		Find: 'Zoeken',
		'Find & replace': 'Zoeken & vervangen',
		'Focus CSS pane': 'Focus CSS-paneel',
		'Focus HTML pane': 'Focus HTML-paneel',
		'Focus JS pane': 'Focus JS-paneel',
		'Focus preview': 'Focus preview',
		'Follow <0>@webmakerApp</0> for new features and release notes.':
			'Volg <0>@webmakerApp</0> voor nieuwe functies en release-opmerkingen.',
		'Follow <0>@webmakerApp</0> to know about the new upcoming features!':
			'Volg <0>@webmakerApp</0> om op de hoogte te blijven van de nieuwe aankomende functies!',
		Font: 'Lettertype',
		'Font Size': 'Lettergrootte',
		Fork: 'Fork',
		'Fork this creation': 'Fork deze creatie',
		'Format Code': 'Code formatteren',
		'Format code': 'Code formatteren',
		'Free plan includes 2 Files mode creations. Upgrade to <0/> for unlimited Files mode, cloud assets & more':
			'Gratis plan omvat 2 creaties in de Bestandenmodus. Upgrade naar <0/> voor onbeperkte Bestandenmodus, cloud-assets en meer',
		Fun: 'Plezier',
		General: 'Algemeen',
		Get: 'Krijg',
		Global: 'Globaal',
		'Grid view': 'Rasterweergave',
		Help: 'Help',
		'Hi, <0>Kushagra</0> here! Web Maker is a free and open-source project. To keep myself motivated for working on such open-source and free <1>side projects</1>, I am accepting donations. Your pledge, no matter how small, will act as an appreciation towards my work and keep me going forward making Web Maker more awesome\uD83D\uDD25. So please consider donating. \uD83D\uDE4F\uD83C\uDFFC (could be as small as $1/month).':
			'Hoi, <0>Kushagra</0> hier! Web Maker is een gratis en open-source project. Om mezelf gemotiveerd te houden om aan zulke open-source en gratis <1>zijprojecten</1> te werken, accepteer ik donaties. Jouw belofte, hoe klein ook, zal als waardering voor mijn werk dienen en me helpen om Web Maker nog geweldig te maken\uD83D\uDD25. Dus overweeg alsjeblieft om te doneren. \uD83D\uDE4F\uD83C\uDFFC (kan zo klein zijn als $1/maand).',
		'Hover/Focus to preview': 'Hover/Focussen om een voorbeeld te bekijken',
		'I wish Web Maker could...': 'Ik wens dat Web Maker kon...',
		'If any loop iteration takes more than the defined time, it is detected as a potential infinite loop and further iterations are stopped.':
			'Als een loopiteratie meer tijd kost dan de gedefinieerde tijd, wordt deze gedetecteerd als een potenti\xEBle oneindige loop en worden verdere iteraties gestopt.',
		'If you are an existing Chrome extension user, you can import your creations from there to here. <0>Learn how to export/import</0>.':
			'Als je een bestaande Chrome-extensie gebruiker bent, kun je je creaties van daar naar hier importeren. <0>Leer hoe je kunt exporteren/importeren</0>.',
		Import: 'Importeren',
		'Import your creations in your account':
			'Importeer je creaties in je account',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			"Importeer je creaties. Alleen het bestand dat je via de 'Exporteren' knop exporteert, kan worden ge\xEFmporteerd.",
		'Indent code left': 'Code naar links inspringen',
		'Indent code right': 'Code naar rechts inspringen',
		Indentation: 'Inspringing',
		'Indentation Size': 'Inspringgrootte',
		"It's okay if you don't want to. You can simply logout and access them anytime on this browser.":
			'Het is prima als je dat niet wilt. Je kunt gewoon uitloggen en ze op elk moment in deze browser openen.',
		'Join a community of 70,000+ Developers':
			'Sluit je aan bij een community van 70.000+ ontwikkelaars',
		'Js13kGames Mode': 'Js13kGames Modus',
		'Key bindings': 'Toetsenbordinstellingen',
		'Keyboard Shortcuts': 'Toetsenbord sneltoetsen',
		'Keyboard shortcuts': 'Toetsenbord sneltoetsen',
		Language: 'Taal',
		'Leave Session': 'Verlaat sessie',
		'Leave a Review': 'Laat een beoordeling achter',
		"Let's start": 'Laten we beginnen',
		'Lets start!': 'Laten we beginnen!',
		License: 'Licentie',
		'Like this app? Please <0>rate it here</0>.':
			'Vind je deze app leuk? Beoordeel het alsjeblieft <0>hier</0>.',
		'Line wrap': 'Regelomloop',
		'List view': 'Lijstweergave',
		'Loads the last open creation when app starts':
			'Laadt de laatste open creatie wanneer de app start',
		Local: 'Lokaal',
		'Login & upgrade to PRO': 'Inloggen & upgraden naar PRO',
		'Login / Signup': 'Inloggen / Aanmelden',
		'Login with Github': 'Inloggen met Github',
		'Login with Google': 'Inloggen met Google',
		'Login/Signup': 'Inloggen/Aanmelden',
		'Made with <0>\u2764\uFE0F</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Gemaakt met <0>\u2764\uFE0F</0>& <1>\uD83D\uDE4C</1> door <2>Kushagra Gour</2>',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Gemaakt met <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> door <2>Kushagra Gour</2>',
		'Mail me': 'Mail me',
		'Make a monthly pledge on Patreon':
			'Doe een maandelijkse belofte op Patreon',
		'Make it yours': 'Maak het van jou',
		'Make the app ready to build some games for <0>Js13kGames</0>.':
			'Maak de app klaar om wat spellen voor <0>Js13kGames</0> te bouwen.',
		Manage: 'Beheren',
		'Manage your PRO subscription': 'Beheer je PRO-abonnement',
		'Manage your code in files. Just like you would have files on your local machine.':
			'Beheer je code in bestanden. Net zoals je bestanden op je lokale machine zou hebben.',
		'Max 300KB per file': 'Max 300KB per bestand',
		'Max 5MB per file': 'Max 5MB per bestand',
		'Maximize pane': 'Maximaliseer paneel',
		'Maximum time allowed in a loop iteration':
			'Maximale tijd toegestaan in een lusiteratie',
		'Minimise pane': 'Minimaliseer paneel',
		'Most recent first': 'Meest recent eerst',
		'Most upvoted first': 'Meest omhooggestemd eerst',
		'Multiplayer session active': 'Multiplayer sessie actief',
		'My Library': 'Mijn Bibliotheek',
		New: 'Nieuw',
		'No feedback yet. Be the first!': 'Nog geen feedback. Wees de eerste!',
		'No files uploaded yet': 'Nog geen bestanden ge\xFCpload',
		'No items in this collection.': 'Geen items in deze collectie.',
		'No match found.': 'Geen overeenkomst gevonden.',
		'Note: You can load external scripts only from following domains:':
			'Opmerking: Je kunt externe scripts alleen laden van de volgende domeinen:',
		'Nothing saved here.': 'Hier is niets opgeslagen.',
		'Once you stop typing, the preview waits for this much time before getting updated. Too low value might choke your browser!':
			'Zodra je stopt met typen, wacht de preview deze tijd voordat hij wordt bijgewerkt. Een te lage waarde kan je browser verstoren!',
		Open: 'Openen',
		'Open Web Maker anytime by clicking the<0><1/></0> button in top-right side of your browser.':
			'Open Web Maker op elk moment door op de<0><1/></0> knop in de rechterbovenhoek van je browser te klikken.',
		'Open Web Maker anytime by visiting <0>https://webmaker.app/create/</0> - Even when you are offline! It just works! \uD83D\uDE31 <1>Drag the following bookmarklet</1> on your bookmark bar to create a quick access shortcut:':
			'Open Web Maker op elk moment door te bezoeken <0>https://webmaker.app/create/</0> - Zelfs wanneer je offline bent! Het werkt gewoon! \uD83D\uDE31 <1>Sleep de volgende bookmarklet</1> naar je bladwijzerbalk om een snelkoppeling te maken:',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'Open een opgeslagen creatie (Ctrl/\u2318 + O)',
		'Open anywhere, even offline': 'Open overal, zelfs offline',
		'Open from your toolbar': 'Open vanuit je werkbalk',
		'Open list of saved creations': 'Open lijst van opgeslagen creaties',
		'Or, make a one time donation': 'Of, doe een eenmalige donatie',
		'Other font from system': 'Andere lettertype van systeem',
		'PRO unlocks unlimited public creations, unlimited Files mode projects, cloud asset hosting and real-time multiplayer collab.':
			'PRO ontgrendelt onbeperkte openbare creaties, onbeperkte projecten in de Bestandenmodus, cloud asset hosting en realtime multiplayer samenwerking.',
		Participants: 'Deelnemers',
		'Powered by cdnjs': 'Aangedreven door cdnjs',
		'Preserve console logs': 'Console logs behouden',
		'Preserve last written code': 'Laatst geschreven code behouden',
		'Preserves the console logs across your preview refreshes':
			'Behoudt de console logs tijdens je preview vernieuwingen',
		'Preview refresh wait time': 'Wachtijd voor preview vernieuwing',
		'Preview will refresh when you resize the preview pane':
			'Preview wordt vernieuwd wanneer je het previewvenster vergroot of verkleint',
		'Put each library in new line':
			'Plaats elke bibliotheek op een nieuwe regel',
		'Read more': 'Lees meer',
		'Read the documentation': 'Lees de documentatie',
		'Read the documentation.': 'Lees de documentatie.',
		'Realign code': 'Code opnieuw uitlijnen',
		'Refresh preview': 'Preview vernieuwen',
		'Refresh preview on resize':
			'Preview vernieuwen bij het aanpassen van de grootte',
		"Refreshes the preview as you code. Otherwise use the 'Run' button":
			"Vernieuwt de preview terwijl je codeert. Gebruik anders de 'Run' knop",
		'Replace new tab page': 'Vervang nieuwe tabblad pagina',
		'Report a Bug': 'Rapporteer een bug',
		'Report a bug': 'Meld een bug',
		'Review Web Maker': 'Beoordeel Web Maker',
		Run: 'Uitvoeren',
		'Run Prettier': 'Run Prettier',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'Voer voorbeeld uit (Ctrl/\u2318 + Shift + 5)',
		Save: 'Opslaan',
		'Save as HTML file': 'Opslaan als HTML-bestand',
		'Save current creation (Ctrl/\u2318 + S)':
			'Huidige creatie opslaan (Ctrl/\u2318 + S)',
		'Save current creations': 'Huidige creaties opslaan',
		'Search files': 'Zoek bestanden',
		'Search your creations here...': 'Zoek hier je creaties...',
		'See PRO': 'Bekijk PRO',
		'See awesome libraries used':
			'Bekijk geweldige bibliotheken die zijn gebruikt',
		'See changelog': 'Bekijk changelog',
		'See profile or Logout': 'Bekijk profiel of Uitloggen',
		'Select next match': 'Selecteer volgende overeenkomst',
		'Select previous match': 'Selecteer vorige overeenkomst',
		Settings: 'Instellingen',
		Share: 'Delen',
		'Share Link': 'Deel Link',
		'Share Web Maker': 'Deel Web Maker',
		'Share this creation publicly': 'Deel deze creatie openbaar',
		'Share this link with others to let them join your session.':
			'Deel deze link met anderen zodat ze zich bij je sessie kunnen voegen.',
		'Single line comment': 'Enkele regel commentaar',
		Spaces: 'Spaties',
		'Start Blank': 'Begin Leeg',
		'Start Blank in File Mode': 'Begin Leeg in Bestandsmodus',
		'Start New Collab Session': 'Start Nieuwe Samenwerkingssessie',
		"Start a collaborative editing session and invite others to code together in real-time. Everyone can see each other's cursors and edits.":
			'Start een samenwerkingssessie en nodig anderen uit om samen in real-time te coderen. Iedereen kan elkaars cursors en bewerkingen zien.',
		'Start a new creation': 'Begin een nieuwe creatie',
		'Start multiplayer collaboration session':
			'Start multiplayer samenwerking sessie',
		'Stay in the loop': 'Blijf op de hoogte',
		Submit: 'Indienen',
		'Submitted on:': 'Ingediend op:',
		'Submitting...': 'Indienen...',
		'Support the Developer': 'Steun de Ontwikkelaar',
		'Switch to layout with all vertical panes':
			'Overschakelen naar lay-out met alle verticale panelen',
		'Switch to layout with preview on bottom':
			'Overschakelen naar lay-out met voorbeeld onderaan',
		'Switch to layout with preview on left':
			'Overschakelen naar lay-out met voorbeeld aan de linkerkant',
		'Switch to layout with preview on right':
			'Overschakelen naar lay-out met voorbeeld aan de rechterkant',
		'Switch to lighter version for better performance. Removes things like blur etc.':
			'Overschakelen naar lichtere versie voor betere prestaties. Verwijdert dingen zoals vervaging etc.',
		'Switch to tabbed layout': 'Schakel over naar tabbladindeling',
		Tabs: 'Tabs',
		'Take screenshot of preview': 'Neem screenshot van voorbeeld',
		Theme: 'Thema',
		'Toggle code pane': 'Schakel codepaneel in/uit',
		'Toggle console': 'Schakel console in/uit',
		'Toggle full screen preview': 'Schakel voorbeeld op volledig scherm in/uit',
		'Toggle wrapping of long sentences onto new line':
			'Schakel het afbreken van lange zinnen naar een nieuwe regel in/uit',
		'Turning this on will start showing Web Maker in every new tab you open':
			'Als je dit aanzet, wordt Web Maker in elke nieuwe tab die je opent weergegeven',
		'Turns on the auto-completion suggestions as you type':
			'Zet de auto-aanvulsuggesties aan terwijl je typt',
		"Tweet about 'Web Maker'": "Tweet over 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'Tweet je functie verzoeken, opmerkingen en suggesties naar <0>@webmakerApp</0>',
		'Type here to search libraries': 'Typ hier om bibliotheken te zoeken',
		'Upgrade to PRO': 'Upgrade naar PRO',
		'Upgrade to PRO and get some advanced superpowers!':
			'Upgrade naar PRO en krijg enkele geavanceerde superkrachten!',
		'Upload Image': 'Afbeelding uploaden',
		'Upload assets to the cloud for use across devices.':
			'Upload middelen naar de cloud voor gebruik op verschillende apparaten.',
		'Upload/Use assets': 'Upload/Gebruik middelen',
		'Use Monaco Editor': 'Gebruik Monaco Editor',
		'Use experimental Monaco editor': 'Gebruik experimentele Monaco editor',
		'Visit <0>https://webmaker.app/create/</0> any time \u2014 it works offline. Drag the bookmarklet onto your bookmark bar for one-click access:':
			'Bezoek <0>https://webmaker.app/create/</0> op elk moment \u2014 het werkt offline. Sleep de bookmarklet naar je bladwijzerbalk voor \xE9\xE9n-klik toegang:',
		'Vote for features you want to see or suggest new ones.':
			'Stem op functies die je wilt zien of stel nieuwe voor.',
		'Want more super-powers?': 'Wil je meer superkrachten?',
		'Welcome to Web Maker': 'Welkom bij Web Maker',
		'Yes, please import': 'Ja, graag importeren',
		'You have <0>{oldSavedCreationsCount}</0> creations saved in your local machine. Do you want to import those creations in your account so they are more secure and accessible anywhere?':
			function (a) {
				return [
					'Je hebt <0>',
					a('oldSavedCreationsCount'),
					'</0> creaties opgeslagen op je lokale machine. Wil je die creaties importeren in je account zodat ze veiliger en overal toegankelijk zijn?'
				];
			}
	}
};
