/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			var s = String(n).split('.'),
				v0 = !s[1];
			if (ord) return 'other';
			return n == 1 && v0 ? 'one' : 'other';
		}
	},
	messages: {
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker" ist <0>Open-Source</0> unter der <1>MIT-Lizenz</1>',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'\'Ups! Die ausgew\xE4hlte Datei ist besch\xE4digt. Bitte w\xE4hlen Sie eine Datei aus, die durch Klicken auf die "Exportieren"-Schaltfl\xE4che erstellt wurde.',
		'(Experimental) Switches from CodeMirror to Monaco. Many other settings might not be available in Monaco.':
			'(Experimentell) Wechselt von CodeMirror zu Monaco. Viele andere Einstellungen sind m\xF6glicherweise in Monaco nicht verf\xFCgbar.',
		'2 files mode creations available in Free plan. To create unlimited files mode creations, upgrade to <0/>.':
			'2 Dateimodi-Kreationen sind im kostenlosen Plan verf\xFCgbar. Um unbegrenzte Dateimodi-Kreationen zu erstellen, upgraden Sie auf <0/>.',
		'3 separate panes to write HTML, CSS and JavaScript. Good for quickly testing something.':
			'3 separate panes zum Schreiben von HTML, CSS und JavaScript. Gut, um schnell etwas zu testen.',
		'Add Library': 'Bibliothek hinzuf\xFCgen',
		'Add a JS/CSS library': 'JS/CSS-Bibliothek hinzuf\xFCgen',
		'Add collection': 'Sammlung hinzuf\xFCgen',
		'Add library': 'Bibliothek hinzuf\xFCgen',
		'Add the closing tag automatically on seeing an opening tag in HTML':
			'F\xFCgen Sie das schlie\xDFende Tag automatisch hinzu, wenn Sie ein \xF6ffnendes Tag in HTML sehen',
		Advanced: 'Erweitert',
		All: 'Alle',
		Assets: 'Assets',
		'Assets feature is available in PRO plan.':
			'Die Assets-Funktion ist im PRO-Plan verf\xFCgbar.',
		'Atomic CSS configuration': 'Atomic CSS-Konfiguration',
		'Auto-close tags': 'Tags automatisch schlie\xDFen',
		'Auto-complete suggestions': 'Auto-Vervollst\xE4ndigungs-Vorschl\xE4ge',
		'Auto-preview': 'Auto-Vorschau',
		'Auto-save': 'Auto-Speichern',
		'Auto-save keeps saving your code at regular intervals after you hit save manually the first time':
			'Auto-Speichern speichert Ihren Code in regelm\xE4\xDFigen Abst\xE4nden, nachdem Sie beim ersten Mal manuell auf Speichern geklickt haben.',
		'Choose from popular libraries': 'W\xE4hlen Sie aus beliebten Bibliotheken',
		'Clear console (CTRL + L)': 'Konsole leeren (STRG + L)',
		'Clear console (works when console input is focused)':
			'Konsole leeren (funktioniert, wenn der Konsoleneingang fokussiert ist)',
		'Click to change': 'Klicken Sie, um zu \xE4ndern',
		'Click to edit': 'Klicken Sie, um zu bearbeiten',
		'Close saved creations pane':
			'Gespeicherten Kreationen-Bereich schlie\xDFen',
		'Close saved creations panel & modals':
			'Gespeichertes Kreationen-Panel & Modale schlie\xDFen',
		'Code blast!': 'Code-Explosion!',
		Collab: 'Collab',
		'Collab Session': 'Collab-Sitzung',
		'Collaboration unavailable offline':
			'Zusammenarbeit offline nicht verf\xFCgbar',
		'Collection name': 'Sammlungsname',
		'Configure and customize settings by clicking the gear icon (<0><1/></0>) in bottom right of the app.':
			'Konfigurieren und anpassen der Einstellungen, indem Sie auf das Zahnrad-Symbol (<0><1/></0>) in der unteren rechten Ecke der App klicken.',
		Console: 'Konsole',
		'Copy URL (or keep clicking to copy other formats)':
			'URL kopieren (oder weiter klicken, um andere Formate zu kopieren)',
		'Copy link': 'Link kopieren',
		'Create New': 'Neu erstellen',
		'Custom font name here': 'Benutzerdefinierter Schriftartname hier',
		'Default CSS preprocessor': 'Standard CSS-Pr\xE4prozessor',
		'Default HTML preprocessor': 'Standard HTML-Pr\xE4prozessor',
		'Default JavaScript preprocessor': 'Standard JavaScript-Pr\xE4prozessor',
		'Default Preprocessors': 'Standard-Pr\xE4prozessoren',
		Delete: 'L\xF6schen',
		'Detach preview': 'Vorschau abtrennen',
		Discuss: 'Diskutieren',
		"Don't ask me again": 'Nicht mehr fragen',
		'Double click to toggle code pane':
			'Doppelklicken, um den Codebereich umzuschalten',
		'Double click to toggle console':
			'Doppelklicken, um die Konsole umzuschalten',
		'Download game as zip': 'Spiel als Zip herunterladen',
		'Drop files or click here to upload':
			'Dateien hier ablegen oder klicken, um hochzuladen',
		'Edit on CodePen': 'Bearbeiten auf CodePen',
		Editor: 'Editor',
		'Emmet code completion': 'Emmet-Codevervollst\xE4ndigung',
		'Enjoy wonderful particle blasts while you type':
			'Genie\xDFen Sie wunderbare Partikelexplosionen, w\xE4hrend Sie tippen',
		Export: 'Exportieren',
		'Export all your creations into a single importable file.':
			'Exportieren Sie alle Ihre Kreationen in eine einzige importierbare Datei.',
		'Fast/light-weight version': 'Schnelle/leichte Version',
		'Feedback & Suggestions': 'Feedback & Vorschl\xE4ge',
		'Fetching files...': 'Dateien werden abgerufen...',
		'File should be max 300KB in size':
			'Die Datei sollte maximal 300KB gro\xDF sein',
		'Files modes is currently only available in Web app. <0>Try the Web app now</0>.':
			'Dateimodi sind derzeit nur in der Webanwendung verf\xFCgbar. <0>Probiere jetzt die Webanwendung aus</0>.',
		Find: 'Finden',
		'Find & replace': 'Suchen & Ersetzen',
		'Follow <0>@webmakerApp</0> to know about the new upcoming features!':
			'Folge <0>@webmakerApp</0>, um \xFCber die neuen kommenden Funktionen informiert zu werden!',
		Font: 'Schriftart',
		'Font Size': 'Schriftgr\xF6\xDFe',
		Fork: 'Fork',
		'Fork this creation': 'Fork diese Kreation',
		'Format Code': 'Code formatieren',
		'Format code': 'Code formatieren',
		Fun: 'Spa\xDF',
		General: 'Allgemein',
		Get: 'Holen',
		Global: 'Global',
		'Grid view': 'Rasteransicht',
		Help: 'Hilfe',
		'Hi, <0>Kushagra</0> here! Web Maker is a free and open-source project. To keep myself motivated for working on such open-source and free <1>side projects</1>, I am accepting donations. Your pledge, no matter how small, will act as an appreciation towards my work and keep me going forward making Web Maker more awesome\uD83D\uDD25. So please consider donating. \uD83D\uDE4F\uD83C\uDFFC (could be as small as $1/month).':
			'Hallo, <0>Kushagra</0> hier! Web Maker ist ein kostenloses und Open-Source-Projekt. Um mich motiviert zu halten, an solchen Open-Source- und kostenlosen <1>Nebenprojekten</1> zu arbeiten, nehme ich Spenden an. Dein Beitrag, egal wie klein, wird als Wertsch\xE4tzung f\xFCr meine Arbeit angesehen und hilft mir, Web Maker noch gro\xDFartiger zu machen\uD83D\uDD25. Bitte ziehe in Betracht, zu spenden. \uD83D\uDE4F\uD83C\uDFFC (kann so klein sein wie $1/Monat).',
		'Hover/Focus to preview': 'Hover/Fokus zur Vorschau',
		'I wish Web Maker could...': 'Ich w\xFCnschte, Web Maker k\xF6nnte...',
		'If any loop iteration takes more than the defined time, it is detected as a potential infinite loop and further iterations are stopped.':
			'Wenn eine Schleifeniteration l\xE4nger als die definierte Zeit ben\xF6tigt, wird sie als potenzielle Endlosschleife erkannt und weitere Iterationen werden gestoppt.',
		'If you are an existing Chrome extension user, you can import your creations from there to here. <0>Learn how to export/import</0>.':
			'Wenn du ein bestehender Chrome-Erweiterungsbenutzer bist, kannst du deine Kreationen von dort hierher importieren. <0>Erfahre, wie man exportiert/importiert</0>.',
		Import: 'Importieren',
		'Import your creations in your account':
			'Importiere deine Kreationen in dein Konto',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			"Importiere deine Kreationen. Nur die Datei, die du \xFCber die Schaltfl\xE4che 'Exportieren' exportierst, kann importiert werden.",
		'Indent code left': 'Code nach links einr\xFCcken',
		'Indent code right': 'Code nach rechts einr\xFCcken',
		Indentation: 'Einr\xFCckung',
		'Indentation Size': 'Einr\xFCckungsgr\xF6\xDFe',
		"It's okay if you don't want to. You can simply logout and access them anytime on this browser.":
			'Es ist in Ordnung, wenn du nicht m\xF6chtest. Du kannst dich einfach abmelden und sie jederzeit in diesem Browser abrufen.',
		'Join a community of 70,000+ Developers':
			'Tritt einer Community von \xFCber 70.000 Entwicklern bei',
		'Js13kGames Mode': 'Js13kGames Modus',
		'Key bindings': 'Tastenkombinationen',
		'Keyboard Shortcuts': 'Tastenk\xFCrzel',
		'Keyboard shortcuts': 'Tastenk\xFCrzel',
		Language: 'Sprache',
		'Leave Session': 'Sitzung verlassen',
		'Lets start!': 'Lass uns anfangen!',
		License: 'Lizenz',
		'Like this app? Please <0>rate it here</0>.':
			'Gef\xE4llt dir diese App? Bitte <0>bewerte sie hier</0>.',
		'Line wrap': 'Zeilenumbruch',
		'List view': 'Listenansicht',
		'Loads the last open creation when app starts':
			'L\xE4dt die letzte offene Kreation, wenn die App startet',
		'Login & upgrade to PRO': 'Einloggen & auf PRO upgraden',
		'Login / Signup': 'Einloggen / Registrieren',
		'Login with Github': 'Einloggen mit Github',
		'Login with Google': 'Einloggen mit Google',
		'Login/Signup': 'Einloggen/Registrieren',
		'Made with <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'Hergestellt mit <0>\uD83D\uDC96</0>& <1>\uD83D\uDE4C</1> von <2>Kushagra Gour</2>',
		'Mail me': 'Schreib mir',
		'Make a monthly pledge on Patreon':
			'Mach ein monatliches Versprechen auf Patreon',
		'Make the app ready to build some games for <0>Js13kGames</0>.':
			'Mach die App bereit, um einige Spiele f\xFCr <0>Js13kGames</0> zu erstellen.',
		Manage: 'Verwalten',
		'Manage your PRO subscription': 'Verwalte dein PRO-Abonnement',
		'Manage your code in files. Just like you would have files on your local machine.':
			'Verwalte deinen Code in Dateien. So wie du Dateien auf deinem lokalen Computer h\xE4ttest.',
		'Maximize pane': 'Pane maximieren',
		'Maximum time allowed in a loop iteration':
			'Maximale Zeit, die in einer Schleifeniteration erlaubt ist',
		'Minimise pane': 'Pane minimieren',
		'Most recent first': 'Neueste zuerst',
		'Most upvoted first': 'Am meisten hochgevotet zuerst',
		'Multiplayer session active': 'Multiplayer-Sitzung aktiv',
		'My Library': 'Meine Bibliothek',
		New: 'Neu',
		'No feedback yet. Be the first!': 'Noch kein Feedback. Sei der Erste!',
		'No files uploaded yet': 'Noch keine Dateien hochgeladen',
		'No items in this collection.': 'Keine Elemente in dieser Sammlung.',
		'No match found.': 'Kein Treffer gefunden.',
		'Note: You can load external scripts only from following domains:':
			'Hinweis: Sie k\xF6nnen externe Skripte nur von folgenden Domains laden:',
		'Nothing saved here.': 'Hier ist nichts gespeichert.',
		'Once you stop typing, the preview waits for this much time before getting updated. Too low value might choke your browser!':
			'Sobald Sie mit dem Tippen aufh\xF6ren, wartet die Vorschau diese Zeit, bevor sie aktualisiert wird. Ein zu niedriger Wert k\xF6nnte Ihren Browser \xFCberlasten!',
		Open: '\xD6ffnen',
		'Open Web Maker anytime by clicking the<0><1/></0> button in top-right side of your browser.':
			'\xD6ffnen Sie Web Maker jederzeit, indem Sie auf die Schaltfl\xE4che<0><1/></0> in der oberen rechten Ecke Ihres Browsers klicken.',
		'Open Web Maker anytime by visiting <0>https://webmaker.app/create/</0> - Even when you are offline! It just works! \uD83D\uDE31 <1>Drag the following bookmarklet</1> on your bookmark bar to create a quick access shortcut:':
			'\xD6ffnen Sie Web Maker jederzeit, indem Sie <0>https://webmaker.app/create/</0> besuchen - Auch wenn Sie offline sind! Es funktioniert einfach! \uD83D\uDE31 <1>Ziehen Sie das folgende Bookmarklet</1> auf Ihre Lesezeichenleiste, um eine Schnellzugriffsverkn\xFCpfung zu erstellen:',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'\xD6ffnen Sie eine gespeicherte Kreation (Ctrl/\u2318 + O)',
		'Open list of saved creations':
			'Liste der gespeicherten Kreationen \xF6ffnen',
		'Or, make a one time donation': 'Oder, machen Sie eine einmalige Spende',
		'Other font from system': 'Andere Schriftart vom System',
		Participants: 'Teilnehmer',
		'Powered by cdnjs': 'Betrieben von cdnjs',
		'Preserve console logs': 'Konsoleprotokolle beibehalten',
		'Preserve last written code': 'Letzten geschriebenen Code beibehalten',
		'Preserves the console logs across your preview refreshes':
			'Beibehaltung der Konsolenprotokolle \xFCber Ihre Vorschauaktualisierungen hinweg',
		'Preview refresh wait time': 'Wartezeit f\xFCr die Vorschauaktualisierung',
		'Preview will refresh when you resize the preview pane':
			'Die Vorschau wird aktualisiert, wenn Sie den Vorschau-Bereich \xE4ndern',
		'Put each library in new line': 'Jede Bibliothek in eine neue Zeile setzen',
		'Read more': 'Mehr lesen',
		'Read the documentation.': 'Lesen Sie die Dokumentation.',
		'Realign code': 'Code neu ausrichten',
		'Refresh preview': 'Vorschau aktualisieren',
		'Refresh preview on resize':
			'Vorschau bei Gr\xF6\xDFen\xE4nderung aktualisieren',
		"Refreshes the preview as you code. Otherwise use the 'Run' button":
			"Aktualisiert die Vorschau, w\xE4hrend Sie codieren. Andernfalls verwenden Sie die Schaltfl\xE4che 'Ausf\xFChren'",
		'Replace new tab page': 'Ersetze die neue Tab-Seite',
		'Report a bug': 'Einen Fehler melden',
		'Review Web Maker': 'Bewerte Web Maker',
		Run: 'Ausf\xFChren',
		'Run Prettier': 'Prettier ausf\xFChren',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'Vorschau ausf\xFChren (Ctrl/\u2318 + Shift + 5)',
		Save: 'Speichern',
		'Save as HTML file': 'Als HTML-Datei speichern',
		'Save current creation (Ctrl/\u2318 + S)':
			'Aktuelle Kreation speichern (Ctrl/\u2318 + S)',
		'Save current creations': 'Aktuelle Kreationen speichern',
		'Search files': 'Dateien suchen',
		'Search your creations here...': 'Suche deine Kreationen hier...',
		'See awesome libraries used':
			'Sieh dir die gro\xDFartigen verwendeten Bibliotheken an',
		'See changelog': '\xC4nderungsprotokoll ansehen',
		'See profile or Logout': 'Profil ansehen oder abmelden',
		'Select next match': 'N\xE4chste \xDCbereinstimmung ausw\xE4hlen',
		'Select previous match': 'Vorherige \xDCbereinstimmung ausw\xE4hlen',
		Settings: 'Einstellungen',
		Share: 'Teilen',
		'Share Link': 'Link teilen',
		'Share Web Maker': 'Web Maker teilen',
		'Share this creation publicly': 'Diese Kreation \xF6ffentlich teilen',
		'Share this link with others to let them join your session.':
			'Teile diesen Link mit anderen, damit sie deiner Sitzung beitreten k\xF6nnen.',
		'Single line comment': 'Einzeiliger Kommentar',
		Spaces: 'Leerzeichen',
		'Start Blank': 'Leer starten',
		'Start Blank in File Mode': 'Leer im Dateimodus starten',
		'Start New Collab Session': 'Neue Kollab-Sitzung starten',
		"Start a collaborative editing session and invite others to code together in real-time. Everyone can see each other's cursors and edits.":
			'Starte eine kollaborative Bearbeitungssitzung und lade andere ein, gemeinsam in Echtzeit zu programmieren. Jeder kann die Cursors und \xC4nderungen der anderen sehen.',
		'Start a new creation': 'Eine neue Kreation starten',
		'Start multiplayer collaboration session':
			'Starte die Multiplayer-Zusammenarbeitssitzung',
		Submit: 'Einreichen',
		'Submitted on:': 'Eingereicht am:',
		'Submitting...': 'Wird eingereicht...',
		'Support the Developer': 'Unterst\xFCtze den Entwickler',
		'Switch to layout with all vertical panes':
			'Wechsle zu einem Layout mit allen vertikalen Fenstern',
		'Switch to layout with preview on bottom':
			'Wechsle zu einem Layout mit Vorschau unten',
		'Switch to layout with preview on left':
			'Wechsle zu einem Layout mit Vorschau links',
		'Switch to layout with preview on right':
			'Wechsle zu einem Layout mit Vorschau rechts',
		'Switch to lighter version for better performance. Removes things like blur etc.':
			'Wechsle zu einer leichteren Version f\xFCr bessere Leistung. Entfernt Dinge wie Unsch\xE4rfe usw.',
		Tabs: 'Tabs',
		'Take screenshot of preview': 'Screenshot der Vorschau machen',
		Theme: 'Thema',
		'Toggle code pane': 'Codefenster umschalten',
		'Toggle console': 'Konsole umschalten',
		'Toggle full screen preview': 'Vollbildvorschau umschalten',
		'Toggle wrapping of long sentences onto new line':
			'Umschalten des Umbruchs langer S\xE4tze auf neue Zeile',
		'Turning this on will start showing Web Maker in every new tab you open':
			'Wenn du dies aktivierst, wird Web Maker in jedem neuen Tab angezeigt, den du \xF6ffnest',
		'Turns on the auto-completion suggestions as you type':
			'Aktiviert die Auto-Vervollst\xE4ndigungsvorschl\xE4ge w\xE4hrend des Tippens',
		"Tweet about 'Web Maker'": "Tweet \xFCber 'Web Maker'",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'Tweet deine Funktionsanfragen, Kommentare & Vorschl\xE4ge an <0>@webmakerApp</0>',
		'Type here to search libraries': 'Hier eingeben, um Bibliotheken zu suchen',
		'Upgrade to PRO': 'Upgrade auf PRO',
		'Upgrade to PRO and get some advanced superpowers!':
			'Upgrade auf PRO und erhalte einige fortgeschrittene Superkr\xE4fte!',
		'Upload Image': 'Bild hochladen',
		'Upload/Use assets': 'Assets hochladen/benutzen',
		'Use Monaco Editor': 'Verwende den Monaco Editor',
		'Use experimental Monaco editor':
			'Verwende den experimentellen Monaco Editor',
		'Vote for features you want to see or suggest new ones.':
			'Stimme f\xFCr Funktionen ab, die du sehen m\xF6chtest, oder schlage neue vor.',
		'Welcome to Web Maker': 'Willkommen bei Web Maker',
		'Yes, please import': 'Ja, bitte importieren',
		'You have <0>{oldSavedCreationsCount}</0> creations saved in your local machine. Do you want to import those creations in your account so they are more secure and accessible anywhere?':
			function (a) {
				return [
					'Du hast <0>',
					a('oldSavedCreationsCount'),
					'</0> Kreationen auf deinem lokalen Computer gespeichert. M\xF6chtest du diese Kreationen in dein Konto importieren, damit sie sicherer und \xFCberall zug\xE4nglich sind?'
				];
			}
	}
};
