/* eslint-disable */ export default {
	languageData: {
		plurals: function (n, ord) {
			if (ord) return 'other';
			return 'other';
		}
	},
	messages: {
		'"Web Maker" is <0>open-source</0> under the <1>MIT License</1>':
			'"Web Maker"\uB294 <1>MIT \uB77C\uC774\uC120\uC2A4</1> \uD558\uC5D0 <0>\uC624\uD508\uC18C\uC2A4</0>\uB85C \uC81C\uACF5\uB429\uB2C8\uB2E4',
		'\'Oops! Selected file is corrupted. Please select a file that was generated by clicking the "Export" button.':
			'\'\uC557! \uC120\uD0DD\uD55C \uD30C\uC77C\uC774 \uC190\uC0C1\uB418\uC5C8\uC2B5\uB2C8\uB2E4. "\uB0B4\uBCF4\uB0B4\uAE30" \uBC84\uD2BC\uC744 \uD074\uB9AD\uD574 \uC0DD\uC131\uB41C \uD30C\uC77C\uC744 \uC120\uD0DD\uD574 \uC8FC\uC138\uC694.',
		'(Experimental) Switches from CodeMirror to Monaco. Many other settings might not be available in Monaco.':
			'(\uC2E4\uD5D8\uC801 \uAE30\uB2A5) CodeMirror\uC5D0\uC11C Monaco\uB85C \uC804\uD658\uD569\uB2C8\uB2E4. Monaco\uC5D0\uC11C\uB294 \uB2E4\uB978 \uC124\uC815 \uC911 \uC77C\uBD80\uB97C \uC0AC\uC6A9\uD560 \uC218 \uC5C6\uC744 \uC218 \uC788\uC2B5\uB2C8\uB2E4.',
		'(the <0>gist</0> scope is pre-selected).':
			'(<0>gist</0> \uBC94\uC704\uAC00 \uBBF8\uB9AC \uC120\uD0DD\uB418\uC5B4 \uC788\uC2B5\uB2C8\uB2E4).',
		'3 separate panes to write HTML, CSS and JavaScript. Good for quickly testing something.':
			'HTML, CSS, JavaScript\uB97C \uC791\uC131\uD558\uB294 3\uAC1C\uC758 \uBD84\uB9AC\uB41C \uD328\uB110\uC785\uB2C8\uB2E4. \uBE60\uB974\uAC8C \uD14C\uC2A4\uD2B8\uD558\uAE30 \uC88B\uC2B5\uB2C8\uB2E4.',
		'A blazing-fast, offline code editor for the web. Three things to know before you start.':
			'\uC6F9\uC744 \uC704\uD55C \uCD08\uACE0\uC18D \uC624\uD504\uB77C\uC778 \uCF54\uB4DC \uC5D0\uB514\uD130\uC785\uB2C8\uB2E4. \uC2DC\uC791\uD558\uAE30 \uC804\uC5D0 \uC54C\uC544\uB450\uBA74 \uC88B\uC740 \uC138 \uAC00\uC9C0\uAC00 \uC788\uC2B5\uB2C8\uB2E4.',
		'Add Library': '\uB77C\uC774\uBE0C\uB7EC\uB9AC \uCD94\uAC00',
		'Add a JS/CSS library':
			'JS/CSS \uB77C\uC774\uBE0C\uB7EC\uB9AC \uCD94\uAC00',
		'Add collection': '\uCEEC\uB809\uC158 \uCD94\uAC00',
		"Add files locally, usable only on this browser. Won't work for others if you share this publicly.":
			'\uD30C\uC77C\uC744 \uB85C\uCEEC\uC5D0 \uCD94\uAC00\uD558\uBA74 \uC774 \uBE0C\uB77C\uC6B0\uC800\uC5D0\uC11C\uB9CC \uC0AC\uC6A9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4. \uACF5\uAC1C\uC801\uC73C\uB85C \uACF5\uC720\uD574\uB3C4 \uB2E4\uB978 \uC0AC\uB78C\uC5D0\uAC8C\uB294 \uC791\uB3D9\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.',
		'Add library': '\uB77C\uC774\uBE0C\uB7EC\uB9AC \uCD94\uAC00',
		'Add some code before exporting.':
			'\uB0B4\uBCF4\uB0B4\uAE30 \uC804\uC5D0 \uCF54\uB4DC\uB97C \uC791\uC131\uD574 \uC8FC\uC138\uC694.',
		'Add the closing tag automatically on seeing an opening tag in HTML':
			'HTML\uC5D0\uC11C \uC5EC\uB294 \uD0DC\uADF8\uB97C \uC785\uB825\uD558\uBA74 \uC790\uB3D9\uC73C\uB85C \uB2EB\uB294 \uD0DC\uADF8\uB97C \uCD94\uAC00\uD569\uB2C8\uB2E4',
		Advanced: '\uACE0\uAE09',
		All: '\uC804\uCCB4',
		Assets: '\uC5D0\uC14B',
		'Atomic CSS configuration': 'Atomic CSS \uC124\uC815',
		'Auto-close tags': '\uD0DC\uADF8 \uC790\uB3D9 \uB2EB\uAE30',
		'Auto-complete suggestions': '\uC790\uB3D9 \uC644\uC131 \uC81C\uC548',
		'Auto-preview': '\uC790\uB3D9 \uBBF8\uB9AC\uBCF4\uAE30',
		'Auto-save': '\uC790\uB3D9 \uC800\uC7A5',
		'Auto-save keeps saving your code at regular intervals after you hit save manually the first time':
			'\uC790\uB3D9 \uC800\uC7A5\uC740 \uCC98\uC74C \uC218\uB3D9\uC73C\uB85C \uC800\uC7A5\uD55C \uC774\uD6C4 \uC77C\uC815 \uAC04\uACA9\uC73C\uB85C \uCF54\uB4DC\uB97C \uACC4\uC18D \uC800\uC7A5\uD569\uB2C8\uB2E4',
		Back: '\uB4A4\uB85C',
		"Can't connect?": '\uC5F0\uACB0\uC774 \uC548 \uB418\uB098\uC694?',
		Cancelled: '\uCDE8\uC18C\uB428',
		'Choose from popular libraries':
			'\uC778\uAE30 \uB77C\uC774\uBE0C\uB7EC\uB9AC\uC5D0\uC11C \uC120\uD0DD',
		'Clear console (CTRL + L)': '\uCF58\uC194 \uC9C0\uC6B0\uAE30 (CTRL + L)',
		'Clear console (works when console input is focused)':
			'\uCF58\uC194 \uC9C0\uC6B0\uAE30 (\uCF58\uC194 \uC785\uB825\uCC3D\uC5D0 \uD3EC\uCEE4\uC2A4\uAC00 \uC788\uC744 \uB54C \uB3D9\uC791)',
		'Click the Web Maker icon in the top-right of your browser any time you want to start tinkering.':
			'\uC791\uC5C5\uC744 \uC2DC\uC791\uD558\uACE0 \uC2F6\uC744 \uB54C \uC5B8\uC81C\uB4E0\uC9C0 \uBE0C\uB77C\uC6B0\uC800 \uC624\uB978\uCABD \uC704\uC758 Web Maker \uC544\uC774\uCF58\uC744 \uD074\uB9AD\uD558\uC138\uC694.',
		'Click to change': '\uD074\uB9AD\uD558\uC5EC \uBCC0\uACBD',
		'Click to edit': '\uD074\uB9AD\uD558\uC5EC \uD3B8\uC9D1',
		'Close saved creations pane':
			'\uC800\uC7A5\uB41C \uC791\uD488 \uD328\uB110 \uB2EB\uAE30',
		'Close saved creations panel & modals':
			'\uC800\uC7A5\uB41C \uC791\uD488 \uD328\uB110 \uBC0F \uBAA8\uB2EC \uB2EB\uAE30',
		Cloud: '\uD074\uB77C\uC6B0\uB4DC',
		'Code blast!': '\uCF54\uB4DC \uBE14\uB77C\uC2A4\uD2B8!',
		Collab: '\uD611\uC5C5',
		'Collab Session': '\uD611\uC5C5 \uC138\uC158',
		'Collaboration unavailable offline':
			'\uC624\uD504\uB77C\uC778\uC5D0\uC11C\uB294 \uD611\uC5C5\uC744 \uC0AC\uC6A9\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4',
		'Collection name': '\uCEEC\uB809\uC158 \uC774\uB984',
		'Coming from the Chrome extension? <0>Learn how to import your creations</0>.':
			'Chrome \uD655\uC7A5 \uD504\uB85C\uADF8\uB7A8\uC5D0\uC11C \uB118\uC5B4\uC624\uC168\uB098\uC694? <0>\uC791\uD488\uC744 \uAC00\uC838\uC624\uB294 \uBC29\uBC95 \uC54C\uC544\uBCF4\uAE30</0>.',
		'Connect GitHub': 'GitHub \uC5F0\uACB0',
		'Connect GitHub to update this gist or push a new version.':
			'\uC774 gist\uB97C \uC5C5\uB370\uC774\uD2B8\uD558\uAC70\uB098 \uC0C8 \uBC84\uC804\uC744 \uD478\uC2DC\uD558\uB824\uBA74 GitHub\uC5D0 \uC5F0\uACB0\uD558\uC138\uC694.',
		'Connected as {login}': function (a) {
			return [a('login'), '(\uC73C)\uB85C \uC5F0\uACB0\uB428'];
		},
		'Connecting to GitHub\u2026':
			'GitHub\uC5D0 \uC5F0\uACB0\uD558\uB294 \uC911\u2026',
		Console: '\uCF58\uC194',
		'Contact the Developer':
			'\uAC1C\uBC1C\uC790\uC5D0\uAC8C \uBB38\uC758\uD558\uAE30',
		'Copy URL (or keep clicking to copy other formats)':
			'URL \uBCF5\uC0AC (\uACC4\uC18D \uD074\uB9AD\uD558\uBA74 \uB2E4\uB978 \uD615\uC2DD\uC73C\uB85C \uBCF5\uC0AC)',
		'Copy gist URL': 'gist URL \uBCF5\uC0AC',
		'Copy link': '\uB9C1\uD06C \uBCF5\uC0AC',
		'Copy public URL': '\uACF5\uAC1C URL \uBCF5\uC0AC',
		'Copy the token and paste it below.':
			'\uD1A0\uD070\uC744 \uBCF5\uC0AC\uD558\uC5EC \uC544\uB798\uC5D0 \uBD99\uC5EC\uB123\uC73C\uC138\uC694.',
		'Could not connect to GitHub.':
			'GitHub\uC5D0 \uC5F0\uACB0\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.',
		'Could not validate token.':
			'\uD1A0\uD070\uC744 \uD655\uC778\uD560 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.',
		'Create New': '\uC0C8\uB85C \uB9CC\uB4E4\uAE30',
		'Create new Gist': '\uC0C8 Gist \uB9CC\uB4E4\uAE30',
		'Creating new Gist\u2026': '\uC0C8 Gist \uB9CC\uB4DC\uB294 \uC911\u2026',
		'Custom font name here':
			'\uC5EC\uAE30\uC5D0 \uC0AC\uC6A9\uC790 \uC9C0\uC815 \uD3F0\uD2B8 \uC774\uB984 \uC785\uB825',
		'Customize editor, theme, key bindings and more from the settings gear in the bottom-right corner.':
			'\uC624\uB978\uCABD \uD558\uB2E8\uC758 \uC124\uC815 \uD1B1\uB2C8\uBC14\uD034\uC5D0\uC11C \uC5D0\uB514\uD130, \uD14C\uB9C8, \uD0A4 \uBC14\uC778\uB529 \uB4F1\uC744 \uC0AC\uC6A9\uC790 \uC9C0\uC815\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.',
		'Default CSS preprocessor': '\uAE30\uBCF8 CSS \uC804\uCC98\uB9AC\uAE30',
		'Default HTML preprocessor': '\uAE30\uBCF8 HTML \uC804\uCC98\uB9AC\uAE30',
		'Default JavaScript preprocessor':
			'\uAE30\uBCF8 JavaScript \uC804\uCC98\uB9AC\uAE30',
		'Default Preprocessors': '\uAE30\uBCF8 \uC804\uCC98\uB9AC\uAE30',
		Delete: '\uC0AD\uC81C',
		Description: '\uC124\uBA85',
		'Detach preview': '\uBBF8\uB9AC\uBCF4\uAE30 \uBD84\uB9AC',
		'Disconnect GitHub': 'GitHub \uC5F0\uACB0 \uD574\uC81C',
		Discuss: '\uD1A0\uB860\uD558\uAE30',
		"Don't ask me again": '\uB2E4\uC2DC \uBB3B\uC9C0 \uC54A\uAE30',
		'Double click to toggle code pane':
			'\uB354\uBE14 \uD074\uB9AD\uD558\uC5EC \uCF54\uB4DC \uD328\uB110 \uC804\uD658',
		'Double click to toggle console':
			'\uB354\uBE14 \uD074\uB9AD\uD558\uC5EC \uCF58\uC194 \uC804\uD658',
		'Download game as zip':
			'\uAC8C\uC784\uC744 zip\uC73C\uB85C \uB2E4\uC6B4\uB85C\uB4DC',
		'Drop files or click here to add':
			'\uD30C\uC77C\uC744 \uB4DC\uB86D\uD558\uAC70\uB098 \uC5EC\uAE30\uB97C \uD074\uB9AD\uD558\uC5EC \uCD94\uAC00',
		'Drop files or click here to upload':
			'\uD30C\uC77C\uC744 \uB4DC\uB86D\uD558\uAC70\uB098 \uC5EC\uAE30\uB97C \uD074\uB9AD\uD558\uC5EC \uC5C5\uB85C\uB4DC',
		'Edit on CodePen': 'CodePen\uC5D0\uC11C \uD3B8\uC9D1',
		Editor: '\uC5D0\uB514\uD130',
		'Emmet code completion': 'Emmet \uCF54\uB4DC \uC644\uC131',
		'Enjoy wonderful particle blasts while you type':
			'\uD0C0\uC774\uD551\uD560 \uB54C\uB9C8\uB2E4 \uBA4B\uC9C4 \uD30C\uD2F0\uD074 \uD6A8\uACFC\uB97C \uC990\uACA8\uBCF4\uC138\uC694',
		Export: '\uB0B4\uBCF4\uB0B4\uAE30',
		'Export all your creations into a single importable file.':
			'\uBAA8\uB4E0 \uC791\uD488\uC744 \uAC00\uC838\uC62C \uC218 \uC788\uB294 \uD558\uB098\uC758 \uD30C\uC77C\uB85C \uB0B4\uBCF4\uB0C5\uB2C8\uB2E4.',
		'Export as new gist': '\uC0C8 gist\uB85C \uB0B4\uBCF4\uB0B4\uAE30',
		'Export to Gist': 'Gist\uB85C \uB0B4\uBCF4\uB0B4\uAE30',
		'Export to GitHub Gist': 'GitHub Gist\uB85C \uB0B4\uBCF4\uB0B4\uAE30',
		'Exported to Gist': 'Gist\uB85C \uB0B4\uBCF4\uB0C4',
		'Exporting to Gist\u2026':
			'Gist\uB85C \uB0B4\uBCF4\uB0B4\uB294 \uC911\u2026',
		'Fast/light-weight version':
			'\uBE60\uB974\uACE0 \uAC00\uBCBC\uC6B4 \uBC84\uC804',
		'Feedback & Suggestions': '\uD53C\uB4DC\uBC31 \uBC0F \uC81C\uC548',
		'Fetching files...':
			'\uD30C\uC77C\uC744 \uBD88\uB7EC\uC624\uB294 \uC911...',
		'Files modes is currently only available in Web app. <0>Try the Web app now</0>.':
			'\uD30C\uC77C \uBAA8\uB4DC\uB294 \uD604\uC7AC \uC6F9 \uC571\uC5D0\uC11C\uB9CC \uC0AC\uC6A9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4. <0>\uC9C0\uAE08 \uC6F9 \uC571 \uC0AC\uC6A9\uD574\uBCF4\uAE30</0>.',
		Find: '\uCC3E\uAE30',
		'Find & replace': '\uCC3E\uAE30 \uBC0F \uBC14\uAFB8\uAE30',
		'Focus CSS pane': 'CSS \uD328\uB110\uB85C \uD3EC\uCEE4\uC2A4 \uC774\uB3D9',
		'Focus HTML pane':
			'HTML \uD328\uB110\uB85C \uD3EC\uCEE4\uC2A4 \uC774\uB3D9',
		'Focus JS pane': 'JS \uD328\uB110\uB85C \uD3EC\uCEE4\uC2A4 \uC774\uB3D9',
		'Focus preview':
			'\uBBF8\uB9AC\uBCF4\uAE30\uB85C \uD3EC\uCEE4\uC2A4 \uC774\uB3D9',
		'Follow <0>@webmakerApp</0> for new features and release notes.':
			'\uC0C8\uB85C\uC6B4 \uAE30\uB2A5\uACFC \uB9B4\uB9AC\uC2A4 \uB178\uD2B8\uB97C \uD655\uC778\uD558\uB824\uBA74 <0>@webmakerApp</0>\uC744 \uD314\uB85C\uC6B0\uD558\uC138\uC694.',
		Font: '\uD3F0\uD2B8',
		'Font Size': '\uD3F0\uD2B8 \uD06C\uAE30',
		Fork: '\uD3EC\uD06C',
		'Fork this creation': '\uC774 \uC791\uD488 \uD3EC\uD06C\uD558\uAE30',
		'Format Code': '\uCF54\uB4DC \uC11C\uC2DD \uC9C0\uC815',
		'Format code': '\uCF54\uB4DC \uC11C\uC2DD \uC9C0\uC815',
		'Free plan includes 2 Files mode creations. Upgrade to <0/> for unlimited Files mode, cloud assets & more':
			'\uBB34\uB8CC \uD50C\uB79C\uC5D0\uB294 \uD30C\uC77C \uBAA8\uB4DC \uC791\uD488 2\uAC1C\uAC00 \uD3EC\uD568\uB429\uB2C8\uB2E4. \uBB34\uC81C\uD55C \uD30C\uC77C \uBAA8\uB4DC, \uD074\uB77C\uC6B0\uB4DC \uC5D0\uC14B \uB4F1\uC744 \uC0AC\uC6A9\uD558\uB824\uBA74 <0/>\uB85C \uC5C5\uADF8\uB808\uC774\uB4DC\uD558\uC138\uC694',
		Fun: '\uC7AC\uBBF8',
		General: '\uC77C\uBC18',
		Get: '\uBC1B\uAE30',
		'Gist URL copied': 'Gist URL \uBCF5\uC0AC\uB428',
		'Gist export is only available on the <0>web version</0> of Web-Maker.':
			'Gist \uB0B4\uBCF4\uB0B4\uAE30\uB294 Web-Maker\uC758 <0>\uC6F9 \uBC84\uC804</0>\uC5D0\uC11C\uB9CC \uC0AC\uC6A9\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.',
		'Gist updated': 'Gist \uC5C5\uB370\uC774\uD2B8\uB428',
		'Gist was deleted on GitHub':
			'GitHub\uC5D0\uC11C Gist\uAC00 \uC0AD\uC81C\uB418\uC5C8\uC2B5\uB2C8\uB2E4',
		'GitHub access expired':
			'GitHub \uC561\uC138\uC2A4\uAC00 \uB9CC\uB8CC\uB418\uC5C8\uC2B5\uB2C8\uB2E4',
		'GitHub access expired. Please reconnect.':
			'GitHub \uC561\uC138\uC2A4\uAC00 \uB9CC\uB8CC\uB418\uC5C8\uC2B5\uB2C8\uB2E4. \uB2E4\uC2DC \uC5F0\uACB0\uD574 \uC8FC\uC138\uC694.',
		'GitHub connected': 'GitHub \uC5F0\uACB0\uB428',
		'GitHub disconnected': 'GitHub \uC5F0\uACB0 \uD574\uC81C\uB428',
		Global: '\uC804\uC5ED',
		'Grid view': '\uADF8\uB9AC\uB4DC \uBCF4\uAE30',
		Help: '\uB3C4\uC6C0\uB9D0',
		'Hi, <0>Kushagra</0> here! Web Maker is a free and open-source project. To keep myself motivated for working on such open-source and free <1>side projects</1>, I am accepting donations. Your pledge, no matter how small, will act as an appreciation towards my work and keep me going forward making Web Maker more awesome\uD83D\uDD25. So please consider donating. \uD83D\uDE4F\uD83C\uDFFC (could be as small as $1/month).':
			'\uC548\uB155\uD558\uC138\uC694, <0>Kushagra</0>\uC785\uB2C8\uB2E4! Web Maker\uB294 \uBB34\uB8CC \uC624\uD508\uC18C\uC2A4 \uD504\uB85C\uC81D\uD2B8\uC785\uB2C8\uB2E4. \uC774\uB7F0 \uC624\uD508\uC18C\uC2A4 <1>\uC0AC\uC774\uB4DC \uD504\uB85C\uC81D\uD2B8</1>\uB97C \uACC4\uC18D \uB9CC\uB4E4\uC5B4 \uB098\uAC08 \uB3D9\uAE30\uB97C \uC720\uC9C0\uD558\uAE30 \uC704\uD574 \uD6C4\uC6D0\uC744 \uBC1B\uACE0 \uC788\uC2B5\uB2C8\uB2E4. \uC544\uBB34\uB9AC \uC791\uC740 \uAE08\uC561\uC774\uB77C\uB3C4 \uC5EC\uB7EC\uBD84\uC758 \uD6C4\uC6D0\uC740 \uC81C \uC791\uC5C5\uC5D0 \uB300\uD55C \uAC10\uC0AC\uC758 \uD45C\uC2DC\uAC00 \uB418\uACE0, Web Maker\uB97C \uB354 \uBA4B\uC9C0\uAC8C\uD83D\uDD25 \uB9CC\uB4E4\uC5B4\uAC00\uB294 \uC6D0\uB3D9\uB825\uC774 \uB429\uB2C8\uB2E4. \uADF8\uB7EC\uB2C8 \uD6C4\uC6D0\uC744 \uACE0\uB824\uD574 \uC8FC\uC138\uC694. \uD83D\uDE4F\uD83C\uDFFC (\uC6D4 $1\uCC98\uB7FC \uC791\uC740 \uAE08\uC561\uB3C4 \uC88B\uC2B5\uB2C8\uB2E4).',
		'Hover/Focus to preview':
			'\uBBF8\uB9AC\uBCF4\uB824\uBA74 \uB9C8\uC6B0\uC2A4\uB97C \uC62C\uB9AC\uAC70\uB098 \uD3EC\uCEE4\uC2A4\uD558\uC138\uC694',
		'I wish Web Maker could...':
			'Web Maker\uAC00 \uC774\uB7F0 \uAE30\uB2A5\uC774 \uC788\uC73C\uBA74 \uC88B\uACA0\uC5B4\uC694...',
		'If any loop iteration takes more than the defined time, it is detected as a potential infinite loop and further iterations are stopped.':
			'\uBC18\uBCF5\uBB38\uC758 \uD55C \uD68C\uCC28\uAC00 \uC9C0\uC815\uB41C \uC2DC\uAC04\uBCF4\uB2E4 \uC624\uB798 \uAC78\uB9AC\uBA74 \uC7A0\uC7AC\uC801\uC778 \uBB34\uD55C \uB8E8\uD504\uB85C \uAC10\uC9C0\uB418\uC5B4 \uC774\uD6C4 \uBC18\uBCF5\uC774 \uC911\uB2E8\uB429\uB2C8\uB2E4.',
		Import: '\uAC00\uC838\uC624\uAE30',
		'Import your creations in your account':
			'\uACC4\uC815\uC73C\uB85C \uC791\uD488 \uAC00\uC838\uC624\uAE30',
		"Import your creations. Only the file that you export through the 'Export' button can be imported.":
			"\uC791\uD488\uC744 \uAC00\uC838\uC635\uB2C8\uB2E4. '\uB0B4\uBCF4\uB0B4\uAE30' \uBC84\uD2BC\uC73C\uB85C \uB0B4\uBCF4\uB0B8 \uD30C\uC77C\uB9CC \uAC00\uC838\uC62C \uC218 \uC788\uC2B5\uB2C8\uB2E4.",
		'Include README.md and webmaker.json':
			'README.md\uC640 webmaker.json \uD3EC\uD568',
		'Indent code left':
			'\uCF54\uB4DC \uC67C\uCABD\uC73C\uB85C \uB4E4\uC5EC\uC4F0\uAE30',
		'Indent code right':
			'\uCF54\uB4DC \uC624\uB978\uCABD\uC73C\uB85C \uB4E4\uC5EC\uC4F0\uAE30',
		Indentation: '\uB4E4\uC5EC\uC4F0\uAE30',
		'Indentation Size': '\uB4E4\uC5EC\uC4F0\uAE30 \uD06C\uAE30',
		"It's okay if you don't want to. You can simply logout and access them anytime on this browser.":
			'\uC6D0\uD558\uC9C0 \uC54A\uC73C\uC154\uB3C4 \uAD1C\uCC2E\uC2B5\uB2C8\uB2E4. \uADF8\uB0E5 \uB85C\uADF8\uC544\uC6C3\uD558\uBA74 \uC774 \uBE0C\uB77C\uC6B0\uC800\uC5D0\uC11C \uC5B8\uC81C\uB4E0\uC9C0 \uC811\uADFC\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4.',
		'Join a community of 70,000+ Developers':
			'7\uB9CC \uBA85 \uC774\uC0C1\uC758 \uAC1C\uBC1C\uC790 \uCEE4\uBBA4\uB2C8\uD2F0\uC5D0 \uCC38\uC5EC\uD558\uC138\uC694',
		'Js13kGames Mode': 'Js13kGames \uBAA8\uB4DC',
		'Key bindings': '\uD0A4 \uBC14\uC778\uB529',
		'Keyboard Shortcuts': '\uD0A4\uBCF4\uB4DC \uB2E8\uCD95\uD0A4',
		'Keyboard shortcuts': '\uD0A4\uBCF4\uB4DC \uB2E8\uCD95\uD0A4',
		Language: '\uC5B8\uC5B4',
		'Leave Session': '\uC138\uC158 \uB098\uAC00\uAE30',
		'Leave a Review': '\uB9AC\uBDF0 \uB0A8\uAE30\uAE30',
		"Let's start": '\uC2DC\uC791\uD558\uAE30',
		'Like this app? Please <0>rate it here</0>.':
			'\uC774 \uC571\uC774 \uB9C8\uC74C\uC5D0 \uB4DC\uC2DC\uB098\uC694? <0>\uC5EC\uAE30\uC11C \uD3C9\uAC00\uD574 \uC8FC\uC138\uC694</0>.',
		'Line wrap': '\uC904 \uBC14\uAFC8',
		'Linked gist': '\uC5F0\uACB0\uB41C gist',
		'List view': '\uBAA9\uB85D \uBCF4\uAE30',
		'Loads the last open creation when app starts':
			'\uC571 \uC2DC\uC791 \uC2DC \uB9C8\uC9C0\uB9C9\uC73C\uB85C \uC5F4\uC5C8\uB358 \uC791\uD488\uC744 \uBD88\uB7EC\uC635\uB2C8\uB2E4',
		Local: '\uB85C\uCEEC',
		'Login & upgrade to PRO':
			'\uB85C\uADF8\uC778\uD558\uACE0 PRO\uB85C \uC5C5\uADF8\uB808\uC774\uB4DC',
		'Login / Signup': '\uB85C\uADF8\uC778 / \uD68C\uC6D0\uAC00\uC785',
		'Login with Github': 'GitHub\uB85C \uB85C\uADF8\uC778',
		'Login with Google': 'Google\uB85C \uB85C\uADF8\uC778',
		'Login/Signup': '\uB85C\uADF8\uC778/\uD68C\uC6D0\uAC00\uC785',
		'Made with <0>\u2764\uFE0F</0>& <1>\uD83D\uDE4C</1> by <2>Kushagra Gour</2>':
			'<2>Kushagra Gour</2>\uAC00 <0>\u2764\uFE0F</0>\uC640 <1>\uD83D\uDE4C</1>\uB85C \uB9CC\uB4E4\uC5C8\uC2B5\uB2C8\uB2E4',
		'Make a monthly pledge on Patreon':
			'Patreon\uC5D0\uC11C \uC6D4\uAC04 \uD6C4\uC6D0\uD558\uAE30',
		'Make it yours':
			'\uB098\uB9CC\uC758 \uAC83\uC73C\uB85C \uB9CC\uB4DC\uC138\uC694',
		'Make the app ready to build some games for <0>Js13kGames</0>.':
			'<0>Js13kGames</0>\uC6A9 \uAC8C\uC784\uC744 \uB9CC\uB4E4 \uC218 \uC788\uB3C4\uB85D \uC571\uC744 \uC900\uBE44\uD569\uB2C8\uB2E4.',
		Manage: '\uAD00\uB9AC',
		'Manage your PRO subscription': 'PRO \uAD6C\uB3C5 \uAD00\uB9AC',
		'Manage your code in files. Just like you would have files on your local machine.':
			'\uB85C\uCEEC \uCEF4\uD4E8\uD130\uC758 \uD30C\uC77C\uCC98\uB7FC \uCF54\uB4DC\uB97C \uD30C\uC77C\uB85C \uAD00\uB9AC\uD569\uB2C8\uB2E4.',
		'Max 10MB per file': '\uD30C\uC77C\uB2F9 \uCD5C\uB300 10MB',
		'Max 300KB per file': '\uD30C\uC77C\uB2F9 \uCD5C\uB300 300KB',
		'Maximize pane': '\uD328\uB110 \uCD5C\uB300\uD654',
		'Maximum time allowed in a loop iteration':
			'\uBC18\uBCF5\uBB38 \uD55C \uD68C\uCC28\uC5D0 \uD5C8\uC6A9\uB418\uB294 \uCD5C\uB300 \uC2DC\uAC04',
		'Minimise pane': '\uD328\uB110 \uCD5C\uC18C\uD654',
		'Most recent first': '\uCD5C\uC2E0\uC21C',
		'Most upvoted first': '\uCD94\uCC9C\uC21C',
		'Multiplayer session active':
			'\uBA40\uD2F0\uD50C\uB808\uC774\uC5B4 \uC138\uC158 \uC9C4\uD589 \uC911',
		'My Library': '\uB0B4 \uB77C\uC774\uBE0C\uB7EC\uB9AC',
		New: '\uC0C8\uB85C \uB9CC\uB4E4\uAE30',
		'New gist created': '\uC0C8 gist \uC0DD\uC131\uB428',
		No: '\uC544\uB2C8\uC694',
		'No feedback yet. Be the first!':
			'\uC544\uC9C1 \uD53C\uB4DC\uBC31\uC774 \uC5C6\uC2B5\uB2C8\uB2E4. \uCCAB \uBC88\uC9F8\uAC00 \uB418\uC5B4\uBCF4\uC138\uC694!',
		'No files uploaded yet':
			'\uC544\uC9C1 \uC5C5\uB85C\uB4DC\uB41C \uD30C\uC77C\uC774 \uC5C6\uC2B5\uB2C8\uB2E4',
		'No items in this collection.':
			'\uC774 \uCEEC\uB809\uC158\uC5D0 \uD56D\uBAA9\uC774 \uC5C6\uC2B5\uB2C8\uB2E4.',
		'No match found.':
			'\uC77C\uCE58\uD558\uB294 \uD56D\uBAA9\uC744 \uCC3E\uC744 \uC218 \uC5C6\uC2B5\uB2C8\uB2E4.',
		'Note: You can load external scripts only from following domains:':
			'\uCC38\uACE0: \uB2E4\uC74C \uB3C4\uBA54\uC778\uC5D0\uC11C\uB9CC \uC678\uBD80 \uC2A4\uD06C\uB9BD\uD2B8\uB97C \uBD88\uB7EC\uC62C \uC218 \uC788\uC2B5\uB2C8\uB2E4:',
		'Nothing saved here.':
			'\uC800\uC7A5\uB41C \uD56D\uBAA9\uC774 \uC5C6\uC2B5\uB2C8\uB2E4.',
		'Once you stop typing, the preview waits for this much time before getting updated. Too low value might choke your browser!':
			'\uC785\uB825\uC744 \uBA48\uCD94\uBA74 \uBBF8\uB9AC\uBCF4\uAE30\uAC00 \uC5C5\uB370\uC774\uD2B8\uB418\uAE30\uAE4C\uC9C0 \uC774 \uC2DC\uAC04\uB9CC\uD07C \uAE30\uB2E4\uB9BD\uB2C8\uB2E4. \uAC12\uC774 \uB108\uBB34 \uB0AE\uC73C\uBA74 \uBE0C\uB77C\uC6B0\uC800\uAC00 \uBC84\uBC85\uC77C \uC218 \uC788\uC2B5\uB2C8\uB2E4!',
		Open: '\uC5F4\uAE30',
		'Open GitHub\'s "New token" page':
			'GitHub\uC758 "\uC0C8 \uD1A0\uD070" \uD398\uC774\uC9C0 \uC5F4\uAE30',
		'Open a saved creation (Ctrl/\u2318 + O)':
			'\uC800\uC7A5\uB41C \uC791\uD488 \uC5F4\uAE30 (Ctrl/\u2318 + O)',
		'Open anywhere, even offline':
			'\uC624\uD504\uB77C\uC778 \uC0C1\uD0DC\uC5D0\uC11C\uB3C4 \uC5B4\uB514\uC11C\uB098 \uC5F4\uAE30',
		'Open from your toolbar': '\uD234\uBC14\uC5D0\uC11C \uC5F4\uAE30',
		'Open list of saved creations':
			'\uC800\uC7A5\uB41C \uC791\uD488 \uBAA9\uB85D \uC5F4\uAE30',
		'Or, make a one time donation':
			'\uB610\uB294 \uC77C\uD68C\uC131 \uD6C4\uC6D0\uD558\uAE30',
		'Other font from system':
			'\uC2DC\uC2A4\uD15C\uC758 \uB2E4\uB978 \uD3F0\uD2B8',
		'PRO unlocks unlimited public creations, unlimited Files mode projects, cloud asset hosting and real-time multiplayer collab.':
			'PRO\uB294 \uBB34\uC81C\uD55C \uACF5\uAC1C \uC791\uD488, \uBB34\uC81C\uD55C \uD30C\uC77C \uBAA8\uB4DC \uD504\uB85C\uC81D\uD2B8, \uD074\uB77C\uC6B0\uB4DC \uC5D0\uC14B \uD638\uC2A4\uD305, \uC2E4\uC2DC\uAC04 \uBA40\uD2F0\uD50C\uB808\uC774\uC5B4 \uD611\uC5C5\uC744 \uC81C\uACF5\uD569\uB2C8\uB2E4.',
		Participants: '\uCC38\uAC00\uC790',
		"Paste a GitHub personal access token with the <0>gist</0> scope. It's stored only on this device.":
			'<0>gist</0> \uBC94\uC704\uAC00 \uD3EC\uD568\uB41C GitHub \uAC1C\uC778 \uC561\uC138\uC2A4 \uD1A0\uD070\uC744 \uBD99\uC5EC\uB123\uC73C\uC138\uC694. \uC774 \uAE30\uAE30\uC5D0\uB9CC \uC800\uC7A5\uB429\uB2C8\uB2E4.',
		'Paste a token to continue.':
			'\uACC4\uC18D\uD558\uB824\uBA74 \uD1A0\uD070\uC744 \uBD99\uC5EC\uB123\uC73C\uC138\uC694.',
		'Permission denied. Make sure your token has the "gist" scope.':
			'\uAD8C\uD55C\uC774 \uAC70\uBD80\uB418\uC5C8\uC2B5\uB2C8\uB2E4. \uD1A0\uD070\uC5D0 "gist" \uBC94\uC704\uAC00 \uC788\uB294\uC9C0 \uD655\uC778\uD558\uC138\uC694.',
		'Personal access token': '\uAC1C\uC778 \uC561\uC138\uC2A4 \uD1A0\uD070',
		'Pick an expiration, scroll down, and click <0>Generate token</0>.':
			'\uB9CC\uB8CC \uAE30\uAC04\uC744 \uC120\uD0DD\uD558\uACE0 \uC544\uB798\uB85C \uC2A4\uD06C\uB864\uD55C \uD6C4 <0>Generate token</0>\uC744 \uD074\uB9AD\uD558\uC138\uC694.',
		'Powered by cdnjs': 'cdnjs \uC81C\uACF5',
		'Preserve console logs': '\uCF58\uC194 \uB85C\uADF8 \uBCF4\uC874',
		'Preserve last written code':
			'\uB9C8\uC9C0\uB9C9\uC73C\uB85C \uC791\uC131\uD55C \uCF54\uB4DC \uBCF4\uC874',
		'Preserves the console logs across your preview refreshes':
			'\uBBF8\uB9AC\uBCF4\uAE30\uB97C \uC0C8\uB85C\uACE0\uCE68\uD574\uB3C4 \uCF58\uC194 \uB85C\uADF8\uB97C \uBCF4\uC874\uD569\uB2C8\uB2E4',
		'Preview refresh wait time':
			'\uBBF8\uB9AC\uBCF4\uAE30 \uC0C8\uB85C\uACE0\uCE68 \uB300\uAE30 \uC2DC\uAC04',
		'Preview will refresh when you resize the preview pane':
			'\uBBF8\uB9AC\uBCF4\uAE30 \uD328\uB110 \uD06C\uAE30\uB97C \uC870\uC815\uD558\uBA74 \uBBF8\uB9AC\uBCF4\uAE30\uAC00 \uC0C8\uB85C\uACE0\uCE68\uB429\uB2C8\uB2E4',
		Public: '\uACF5\uAC1C',
		'Public URL': '\uACF5\uAC1C URL',
		'Push this creation to a GitHub gist.':
			'\uC774 \uC791\uD488\uC744 GitHub gist\uC5D0 \uD478\uC2DC\uD569\uB2C8\uB2E4.',
		'Put each library in new line':
			'\uAC01 \uB77C\uC774\uBE0C\uB7EC\uB9AC\uB97C \uC0C8 \uC904\uC5D0 \uC785\uB825\uD558\uC138\uC694',
		'Read more': '\uB354 \uC77D\uAE30',
		'Read the documentation': '\uBB38\uC11C \uC77D\uAE30',
		'Realign code': '\uCF54\uB4DC \uC7AC\uC815\uB82C',
		'Refresh preview': '\uBBF8\uB9AC\uBCF4\uAE30 \uC0C8\uB85C\uACE0\uCE68',
		'Refresh preview on resize':
			'\uD06C\uAE30 \uC870\uC815 \uC2DC \uBBF8\uB9AC\uBCF4\uAE30 \uC0C8\uB85C\uACE0\uCE68',
		"Refreshes the preview as you code. Otherwise use the 'Run' button":
			"\uCF54\uB4DC\uB97C \uC791\uC131\uD558\uBA74\uC11C \uBBF8\uB9AC\uBCF4\uAE30\uB97C \uC0C8\uB85C\uACE0\uCE68\uD569\uB2C8\uB2E4. \uADF8\uB807\uC9C0 \uC54A\uC73C\uBA74 '\uC2E4\uD589' \uBC84\uD2BC\uC744 \uC0AC\uC6A9\uD558\uC138\uC694",
		'Replace new tab page': '\uC0C8 \uD0ED \uD398\uC774\uC9C0 \uB300\uCCB4',
		'Report a Bug': '\uBC84\uADF8 \uC2E0\uACE0',
		'Requires the <0>gist</0> scope.':
			'<0>gist</0> \uBC94\uC704\uAC00 \uD544\uC694\uD569\uB2C8\uB2E4.',
		Run: '\uC2E4\uD589',
		'Run Prettier': 'Prettier \uC2E4\uD589',
		'Run preview (Ctrl/\u2318 + Shift + 5)':
			'\uBBF8\uB9AC\uBCF4\uAE30 \uC2E4\uD589 (Ctrl/\u2318 + Shift + 5)',
		Save: '\uC800\uC7A5',
		'Save as HTML file': 'HTML \uD30C\uC77C\uB85C \uC800\uC7A5',
		'Save current creation (Ctrl/\u2318 + S)':
			'\uD604\uC7AC \uC791\uD488 \uC800\uC7A5 (Ctrl/\u2318 + S)',
		'Save current creations': '\uD604\uC7AC \uC791\uD488 \uC800\uC7A5',
		'Save token': '\uD1A0\uD070 \uC800\uC7A5',
		'Search files': '\uD30C\uC77C \uAC80\uC0C9',
		'Search your creations here...':
			'\uC5EC\uAE30\uC11C \uC791\uD488 \uAC80\uC0C9...',
		Secret: '\uBE44\uACF5\uAC1C',
		'See PRO': 'PRO \uBCF4\uAE30',
		'See awesome libraries used':
			'\uC0AC\uC6A9\uB41C \uBA4B\uC9C4 \uB77C\uC774\uBE0C\uB7EC\uB9AC \uBCF4\uAE30',
		'See changelog': '\uBCC0\uACBD \uC774\uB825 \uBCF4\uAE30',
		'See profile or Logout':
			'\uD504\uB85C\uD544 \uBCF4\uAE30 \uB610\uB294 \uB85C\uADF8\uC544\uC6C3',
		'Select next match': '\uB2E4\uC74C \uD56D\uBAA9 \uC120\uD0DD',
		'Select previous match': '\uC774\uC804 \uD56D\uBAA9 \uC120\uD0DD',
		Settings: '\uC124\uC815',
		Share: '\uACF5\uC720',
		'Share link': '\uACF5\uC720 \uB9C1\uD06C',
		'Share this creation publicly':
			'\uC774 \uC791\uD488 \uACF5\uAC1C\uC801\uC73C\uB85C \uACF5\uC720',
		'Share this link with others to let them join your session.':
			'\uC774 \uB9C1\uD06C\uB97C \uB2E4\uB978 \uC0AC\uB78C\uACFC \uACF5\uC720\uD558\uC5EC \uC138\uC158\uC5D0 \uCC38\uC5EC\uC2DC\uD0A4\uC138\uC694.',
		'Single line comment': '\uD55C \uC904 \uC8FC\uC11D',
		'Something went wrong talking to GitHub.':
			'GitHub\uC640 \uD1B5\uC2E0\uD558\uB294 \uC911 \uBB38\uC81C\uAC00 \uBC1C\uC0DD\uD588\uC2B5\uB2C8\uB2E4.',
		Spaces: '\uACF5\uBC31',
		'Start Blank': '\uBE48 \uC791\uD488\uC73C\uB85C \uC2DC\uC791',
		'Start Blank in File Mode':
			'\uD30C\uC77C \uBAA8\uB4DC\uC5D0\uC11C \uBE48 \uC791\uD488\uC73C\uB85C \uC2DC\uC791',
		'Start New Collab Session': '\uC0C8 \uD611\uC5C5 \uC138\uC158 \uC2DC\uC791',
		"Start a collaborative editing session and invite others to code together in real-time. Everyone can see each other's cursors and edits.":
			'\uD611\uC5C5 \uD3B8\uC9D1 \uC138\uC158\uC744 \uC2DC\uC791\uD558\uACE0 \uB2E4\uB978 \uC0AC\uB78C\uC744 \uCD08\uB300\uD574 \uC2E4\uC2DC\uAC04\uC73C\uB85C \uD568\uAED8 \uCF54\uB529\uD558\uC138\uC694. \uBAA8\uB450\uAC00 \uC11C\uB85C\uC758 \uCEE4\uC11C\uC640 \uD3B8\uC9D1 \uB0B4\uC6A9\uC744 \uBCFC \uC218 \uC788\uC2B5\uB2C8\uB2E4.',
		'Start a new creation': '\uC0C8 \uC791\uD488 \uC2DC\uC791',
		'Start multiplayer collaboration session':
			'\uBA40\uD2F0\uD50C\uB808\uC774\uC5B4 \uD611\uC5C5 \uC138\uC158 \uC2DC\uC791',
		'Stay in the loop':
			'\uC18C\uC2DD\uC744 \uACC4\uC18D \uBC1B\uC544\uBCF4\uC138\uC694',
		Submit: '\uC81C\uCD9C',
		'Submitted on:': '\uC81C\uCD9C\uC77C:',
		'Submitting...': '\uC81C\uCD9C \uC911...',
		'Support the Developer': '\uAC1C\uBC1C\uC790 \uD6C4\uC6D0\uD558\uAE30',
		'Switch to layout with all vertical panes':
			'\uBAA8\uB4E0 \uD328\uB110\uC744 \uC138\uB85C\uB85C \uBC30\uCE58\uD558\uB294 \uB808\uC774\uC544\uC6C3\uC73C\uB85C \uC804\uD658',
		'Switch to layout with preview on bottom':
			'\uBBF8\uB9AC\uBCF4\uAE30\uAC00 \uC544\uB798\uC5D0 \uC788\uB294 \uB808\uC774\uC544\uC6C3\uC73C\uB85C \uC804\uD658',
		'Switch to layout with preview on left':
			'\uBBF8\uB9AC\uBCF4\uAE30\uAC00 \uC67C\uCABD\uC5D0 \uC788\uB294 \uB808\uC774\uC544\uC6C3\uC73C\uB85C \uC804\uD658',
		'Switch to layout with preview on right':
			'\uBBF8\uB9AC\uBCF4\uAE30\uAC00 \uC624\uB978\uCABD\uC5D0 \uC788\uB294 \uB808\uC774\uC544\uC6C3\uC73C\uB85C \uC804\uD658',
		'Switch to lighter version for better performance. Removes things like blur etc.':
			'\uB354 \uB098\uC740 \uC131\uB2A5\uC744 \uC704\uD574 \uAC00\uBCBC\uC6B4 \uBC84\uC804\uC73C\uB85C \uC804\uD658\uD569\uB2C8\uB2E4. \uBE14\uB7EC \uB4F1\uC758 \uD6A8\uACFC\uAC00 \uC81C\uAC70\uB429\uB2C8\uB2E4.',
		'Switch to tabbed layout':
			'\uD0ED \uB808\uC774\uC544\uC6C3\uC73C\uB85C \uC804\uD658',
		Tabs: '\uD0ED',
		'Take screenshot of preview':
			'\uBBF8\uB9AC\uBCF4\uAE30 \uC2A4\uD06C\uB9B0\uC0F7 \uCD2C\uC601',
		"That token didn't work. Double-check you copied it correctly and that it hasn't expired.":
			'\uD574\uB2F9 \uD1A0\uD070\uC774 \uC791\uB3D9\uD558\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4. \uC62C\uBC14\uB974\uAC8C \uBCF5\uC0AC\uD588\uB294\uC9C0, \uB9CC\uB8CC\uB418\uC9C0 \uC54A\uC558\uB294\uC9C0 \uB2E4\uC2DC \uD655\uC778\uD574 \uC8FC\uC138\uC694.',
		Theme: '\uD14C\uB9C8',
		'This gist was deleted on GitHub. Create a new one to re-link.':
			'\uC774 gist\uB294 GitHub\uC5D0\uC11C \uC0AD\uC81C\uB418\uC5C8\uC2B5\uB2C8\uB2E4. \uB2E4\uC2DC \uC5F0\uACB0\uD558\uB824\uBA74 \uC0C8\uB85C \uB9CC\uB4DC\uC138\uC694.',
		'This token is missing the "gist" scope. Recreate it on GitHub with "gist" checked.':
			'\uC774 \uD1A0\uD070\uC5D0\uB294 "gist" \uBC94\uC704\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. GitHub\uC5D0\uC11C "gist"\uB97C \uCCB4\uD06C\uD558\uC5EC \uB2E4\uC2DC \uB9CC\uB4DC\uC138\uC694.',
		'Toggle code pane': '\uCF54\uB4DC \uD328\uB110 \uC804\uD658',
		'Toggle console': '\uCF58\uC194 \uC804\uD658',
		'Toggle full screen preview':
			'\uC804\uCCB4 \uD654\uBA74 \uBBF8\uB9AC\uBCF4\uAE30 \uC804\uD658',
		'Toggle wrapping of long sentences onto new line':
			'\uAE34 \uBB38\uC7A5\uC744 \uC0C8 \uC904\uB85C \uC904\uBC14\uAFC8\uD558\uB294 \uAE30\uB2A5 \uC804\uD658',
		'Turning this on will start showing Web Maker in every new tab you open':
			'\uC774 \uC635\uC158\uC744 \uCF1C\uBA74 \uC0C8 \uD0ED\uC744 \uC5F4 \uB54C\uB9C8\uB2E4 Web Maker\uAC00 \uD45C\uC2DC\uB429\uB2C8\uB2E4',
		'Turns on the auto-completion suggestions as you type':
			'\uC785\uB825 \uC2DC \uC790\uB3D9 \uC644\uC131 \uC81C\uC548\uC744 \uCF2D\uB2C8\uB2E4',
		"Tweet about 'Web Maker'":
			"'Web Maker'\uC5D0 \uB300\uD574 \uD2B8\uC717\uD558\uAE30",
		'Tweet out your feature requests, comments & suggestions to <0>@webmakerApp</0>':
			'\uAE30\uB2A5 \uC694\uCCAD, \uC758\uACAC, \uC81C\uC548\uC744 <0>@webmakerApp</0>\uC5D0 \uD2B8\uC717\uD574 \uC8FC\uC138\uC694',
		'Type here to search libraries':
			'\uC5EC\uAE30\uC5D0 \uC785\uB825\uD558\uC5EC \uB77C\uC774\uBE0C\uB7EC\uB9AC \uAC80\uC0C9',
		'Update Gist': 'Gist \uC5C5\uB370\uC774\uD2B8',
		'Updating Gist\u2026': 'Gist \uC5C5\uB370\uC774\uD2B8 \uC911\u2026',
		'Upgrade to PRO': 'PRO\uB85C \uC5C5\uADF8\uB808\uC774\uB4DC',
		'Upgrade to PRO and get some advanced superpowers!':
			'PRO\uB85C \uC5C5\uADF8\uB808\uC774\uB4DC\uD558\uACE0 \uACE0\uAE09 \uAE30\uB2A5\uC744 \uC0AC\uC6A9\uD574 \uBCF4\uC138\uC694!',
		'Upload Image': '\uC774\uBBF8\uC9C0 \uC5C5\uB85C\uB4DC',
		'Upload assets to the cloud for use across devices.':
			'\uC5EC\uB7EC \uAE30\uAE30\uC5D0\uC11C \uC0AC\uC6A9\uD560 \uC218 \uC788\uB3C4\uB85D \uC5D0\uC14B\uC744 \uD074\uB77C\uC6B0\uB4DC\uC5D0 \uC5C5\uB85C\uB4DC\uD569\uB2C8\uB2E4.',
		'Upload/Use assets': '\uC5D0\uC14B \uC5C5\uB85C\uB4DC/\uC0AC\uC6A9',
		'Use Monaco Editor': 'Monaco \uC5D0\uB514\uD130 \uC0AC\uC6A9',
		'Use a personal access token instead':
			'\uB300\uC2E0 \uAC1C\uC778 \uC561\uC138\uC2A4 \uD1A0\uD070 \uC0AC\uC6A9',
		'Use experimental Monaco editor':
			'\uC2E4\uD5D8\uC801\uC778 Monaco \uC5D0\uB514\uD130 \uC0AC\uC6A9',
		Visibility: '\uACF5\uAC1C \uBC94\uC704',
		'Visit <0>https://webmaker.app/create/</0> any time \u2014 it works offline. Drag the bookmarklet onto your bookmark bar for one-click access:':
			'\uC5B8\uC81C\uB4E0\uC9C0 <0>https://webmaker.app/create/</0>\uB97C \uBC29\uBB38\uD558\uC138\uC694 \u2014 \uC624\uD504\uB77C\uC778\uC5D0\uC11C\uB3C4 \uC791\uB3D9\uD569\uB2C8\uB2E4. \uBD81\uB9C8\uD074\uB9BF\uC744 \uBD81\uB9C8\uD06C \uBC14\uB85C \uB4DC\uB798\uADF8\uD558\uBA74 \uD55C \uBC88\uC758 \uD074\uB9AD\uC73C\uB85C \uC811\uADFC\uD560 \uC218 \uC788\uC2B5\uB2C8\uB2E4:',
		'Vote for features you want to see or suggest new ones.':
			'\uC6D0\uD558\uB294 \uAE30\uB2A5\uC5D0 \uD22C\uD45C\uD558\uAC70\uB098 \uC0C8\uB85C\uC6B4 \uAE30\uB2A5\uC744 \uC81C\uC548\uD558\uC138\uC694.',
		'Want more super-powers?':
			'\uB354 \uB9CE\uC740 \uAC15\uB825\uD55C \uAE30\uB2A5\uC744 \uC6D0\uD558\uC2DC\uB098\uC694?',
		Yes: '\uC608',
		'Yes, please import': '\uC608, \uAC00\uC838\uC624\uAE30',
		'You have <0>{oldSavedCreationsCount}</0> creations saved in your local machine. Do you want to import those creations in your account so they are more secure and accessible anywhere?':
			function (a) {
				return [
					'\uB85C\uCEEC \uCEF4\uD4E8\uD130\uC5D0 <0>',
					a('oldSavedCreationsCount'),
					'</0>\uAC1C\uC758 \uC791\uD488\uC774 \uC800\uC7A5\uB418\uC5B4 \uC788\uC2B5\uB2C8\uB2E4. \uB354 \uC548\uC804\uD558\uACE0 \uC5B4\uB514\uC11C\uB098 \uC811\uADFC\uD560 \uC218 \uC788\uB3C4\uB85D \uC774 \uC791\uD488\uB4E4\uC744 \uACC4\uC815\uC73C\uB85C \uAC00\uC838\uC624\uC2DC\uACA0\uC2B5\uB2C8\uAE4C?'
				];
			}
	}
};
